### ISSUE TITLE
demo run why error 

### ISSUE THREAD

**Issue by controZheng** [transitive-bullshit/chatgpt-api#103]
![image](https://user-images.githubusercontent.com/42229960/207010945-c8de4ed2-7bac-4b9c-ab76-33789e86505a.png)

**Comment by transitive-bullshit** [comment]
Please see the top section of the readme for an update; in short, OpenAI added additional protections that make it more difficult to use the API: https://github.com/transitive-bullshit/chatgpt-api#update-december-11-2022
