### ISSUE TITLE
I overcome Cloudflare with puppeteer

### ISSUE THREAD

**Issue by zenxds** [transitive-bullshit/chatgpt-api#104]
the code is here

```
const fs = require('fs')
const puppeteer = require('puppeteer-extra')
puppeteer.use(require('puppeteer-extra-plugin-stealth')())

const sleep = duration => new Promise(resolve => setTimeout(resolve, duration))

async function start() {
  const browser = await puppeteer.launch({
    executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    headless: false,
    args: ['--proxy-server=127.0.0.1:7890'],
    ignoreHTTPSErrors: true
  })
  const page = (await browser.pages())[0]

  await page.goto('https://chat.openai.com')
  await page.waitForSelector('#__next .btn-primary')
  // wait for networkidle
  await sleep(10 * 1000)
  await page.click('#__next .btn-primary')

  await page.waitForNavigation({
    waitUntil: 'networkidle0'
  })

  await page.type('#username', 'username')
  await page.click('button[name="action"]')

  await page.waitForSelector('#password')

  // await page.screenshot({
  //   path: 'screenshot.png'
  // })

  await page.type('#password', 'password')
  await page.click('button[name="action"]')

  await page.waitForNavigation({
    waitUntil: 'networkidle0'
  })

  fs.writeFileSync('cookies.json', JSON.stringify(await page.cookies()))

  // await sleep(60 * 1000)
  await browser.close()
}

start()
  .then(() => {
    process.exit(0)
  })
  .catch(() => {
    process.exit(1)
  })
```

**Comment by transitive-bullshit** [comment]
Thanks @zenxds.

This very similar to my approach in https://github.com/transitive-bullshit/chatgpt-twitter-bot/pull/5, but I haven't gotten it to work consistently yet due to Cloudflare countermeasures.

What are you using for your local proxy server?

**Comment by ikechan8370** [comment]
I try to solve it with quite similar code, and it works well on my PC. But in another enviroment I always met cloudflare's hCaptcha, even with the puppeteer-extra-plugin-stealth.

**Comment by dockercore** [comment]
牛逼 😊

**Comment by zenxds** [comment]
> 

Because the service is not available in my country

**Comment by Lesiuk** [comment]
https://2captcha.com/pl/p/hcaptcha can solve hcaptcha very cheap

**Comment by transitive-bullshit** [comment]
Thanks everyone for contributing to help; I just updated the repo + docs to help w/ the puppeteer solution.

https://github.com/transitive-bullshit/chatgpt-api/blob/main/demos/openai-auth-puppeteer.ts

**Comment by transitive-bullshit** [comment]
@Tarhyru headless will be the eventual solution, but right now Cloudflare can sometimes prompt you to complete CAPTCHAS which isn't handled in the automated solution.

I'm working on improving this.

**Comment by transitive-bullshit** [comment]
@zenxds thanks a lot for posting your solution. It forced me to re-test my assumptions in the branch I was working on.

Closing this as completed for now.
