### ISSUE TITLE
How to update cf_clearance & __Secure-next-auth.session-token?

### ISSUE THREAD

**Issue by adimenia** [transitive-bullshit/chatgpt-api#128]
Hello

How do I update __Secure-next-auth? Session-token & cf_clearance settings in the extension? in the details section in the VScode plugin, it says the extension will prompt entering those values, but I don't get it. Is there a configuration somewhere where is can set those values?

**Comment by transitive-bullshit** [comment]
OpenAI changed how things work a few days ago when they added Cloudflare protections. I don't know which vscode extension you're talking about (there are a bunch of them), but generally a browser will need to popup and you'll need to bypass any captchas while it logs you in. You'd need to provide a standard email & password option.

**Comment by timkmecl** [comment]
What if I want to login to OpenAI using Google account, does this work?

**Comment by tpholston** [comment]
> What if I want to login to OpenAI using Google account, does this work?

I just created a pull request to add Google account login functionality. https://github.com/transitive-bullshit/chatgpt-api/pull/129
