### ISSUE TITLE
Getting 403 Error- tried exactly same 

### ISSUE THREAD

**Issue by suhail-ak-2** [transitive-bullshit/chatgpt-api#135]
ChatGPTError: ChatGPT failed to refresh auth token. Error: 403 Forbidden
    at ChatGPTAPI.refreshAccessToken (/Users/suhail/Downloads/chatgpt-api-main/src/chatgpt-api.ts:406:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ChatGPTAPI.ensureAuth (/Users/suhail/Downloads/chatgpt-api-main/src/chatgpt-api.ts:320:12)
    at main (/Users/suhail/Downloads/chatgpt-api-main/demos/demo-conversation.ts:27:3) {
  response: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 403,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Forbidden',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  },
  statusCode: 403,
  statusText: 'Forbidden',
  originalError: ChatGPTError: 403 Forbidden
      at <anonymous> (/Users/suhail/Downloads/chatgpt-api-main/src/chatgpt-api.ts:358:25)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at ChatGPTAPI.refreshAccessToken (/Users/suhail/Downloads/chatgpt-api-main/src/chatgpt-api.ts:352:19)
      at ChatGPTAPI.ensureAuth (/Users/suhail/Downloads/chatgpt-api-main/src/chatgpt-api.ts:320:12)
      at main (/Users/suhail/Downloads/chatgpt-api-main/demos/demo-conversation.ts:27:3) {
    response: Response {
      [Symbol(realm)]: null,
      [Symbol(state)]: [Object],
      [Symbol(headers)]: [HeadersList]
    },
    statusCode: 403,
    statusText: 'Forbidden'
  }
}

**Cookies i am getting**

AUTH CREDENTIALS:  {
  authInfo: {
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36',
    clearanceToken: 'WbxtUC3wTXXW6PKUAsBCpx8HDCoZwW3ZDlP4INfZrwo-1671008838-0-1-fcff497e.ac4f6c79.8d786573-160',
    sessionToken: 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..rEkzooanE_J_5dCD.uAdYn8Ap7yk7DWwv2R4O27ci_e8SkUzePu9F6inF2HwTIFpF1JX-zcUa_xBv_fcnjPIWD97mbYY0DI_L2BNaP3T28APQ_FkYh8vCfLhTiA8M6YFvtrSZE_ne-ueY8oKhrY8ouxVnDoGB5FaGZ2Z00PcLlC084MOZ709jjHbcwYK7O3XRHayS6Z0p9h3AlFrdOt9t18VbPq-bK90_s2NBEgEcC2P0Fu000C0B16Dzm9bvHRnaFQT0vEMFCG3Rp3G31AMlJVrNfxLPrre06CuMzAwz1mIsFqa4OSUapbFRqEJS4l8fmx8Qyd1GvRm17BTvE8fCxZk3cP1opel-iKFaf2QFUorczrNsOQcUYI2K_2B0_lI7M6U_PY1dmjEjAdjmRBAggKIAxH9-OQmE4Sv_O7ZJJjPne_KIKa-LbuuhOsEcjNKRCjxegFgZQ2wK_jSzG00fgK3AoIdb_sjhmH_4eO0KgGXXaZSSZEhKN6TmEl75LATTRDb8tpB455ZdLAqQfQ5FwfGZWdoaVkjFmrN6ET2yFkH_8dyjMM2_nny-k2Qpm_9fH8a7oACmZRTcmF_bZsOQ4iYNjTd2aDX9xU8NoUNsWhehrNl2aTBFH6tMxlEq3nk2SGseRgDgYp_m_ZJi0QG7sDzRhcq7bO6xzlMrO1TRmj6aNyeEpLFo_uPr68-rn5STYFZNhCj3BKnhwpWDsx4HujWutL7X17lvNBs1_rFKUdOlJkNiCM_9FFmiE_PWk8JF9fFYxZENZoFYO2rzoeMi1zUpIFWNj8lwimHH75zMlHf7NfrRRXSHvGEd6T9xaBrLV7z_ctIy4-EVyUmmuJW28FyvGesqbHriDeuQsOySZ-_vhmAcg6DKFCjWL42jj5cCkO3nu3u-IVXAxzd4j-tgSvq6YiNMyfIeQyMqhx6cER1nW65YBhox-flgdB6JteGrdXvSr3aZAAR-HT-SHgtqt20blCKpKUBMin6-EqOPNmDL--a8f2PeeoB6en2DD80ipgawSR5IFDfMT8PXBX4JjDQLXA-WKhfsDKifIGZLWRDqbv4ZEZZPwL9bb2KrnAzNbaQhBSTNBpMO-Lxvprl8z6e72PmjLWNWxvRNhqxiXNiWIhRi_1V2xXDgl42CTynweci5BcqISCEDtJ0c1pyGDbJajRrlp0vYJa3UZb8yp7Y9y1Mg-vn6uTZSVV0Sl-HJjrNvH9cyJiIy1qndpEUnYIRIfQs58SNw25UN07VObVHFoUWYBJn6ylhwRFxsYpj3bmptn9Ml_7AGrqE4a0oUOI2TFjyeiyn6IZLAVuPhWAU8JRtNXL810BeUwgMUtrRJ_MaXA8H7qEtv_KxLubgtT3c07ykiPjB1-PsP09gSIh1ESeYqv06etBjf6L672-hXE8sBcWMFY0g75aNc12SjUHg4YmhmfCoXhdVaT09m2Utb7SL8nv4NZHJV01Y_yPWBDvjZEPEceA4nklpoPq4FvYKfr9yd6Mr3P0IX3kU_hnq6Nn1KY_8RY2s4zhhDQHqjM_zjoy1RTPuhVMOxbkqKr-69U_1E_8Au89gl_pmxXjmdzgiHSaMie89DSBN8AypDIe5DwWFUZNueZk1ivRYpAeW191EWqePjPGcjH_jAXkejUM0mE_p5nI3DoBzBbub6xEUeAbfSGW5lNzAqj4TqwhQOht1ZIwx4OUcKT1GXp11z75gx0kkZJ1KejOlFu7YVwxE9HWGZAfbSPo5PhM61VRpY1awqGFJW8M_FZ5K0vVc04OzFtzGe0LB3joGJPjkTiEe5v-5N_mGfRHaDllmoH7Jiz0ogwbX1DQfxC8z6oYMoeTWV04LeQiYaEdFLv8LLeCGmSmGe_CxBoZeoyS4q-FSM2FW0RTTJ9t05qFDKd3hpdjVpvUrhT-htBobEuY6RPcwPDjmFYZspMZYx9NK0IdM1Qs1dbF0rdqTN-dNBdwbGS9ClZW6W5WLrFzKvzeN0TTej5l42wZX2fEYoE_oCvwluGS-vV40VqhH0kH0003S1Bn9YjvQxGx047NMK2O0QEdXwEynrnNpHF5y3xXE1JPL5Pt_h_fNLcC2QHHVX0R7TM1tt4bodkQAj0UJbkH_W-iiZR5rceb9kHis8y3GX-eC91r8OTW56VraOX1XrXmP3IS3pob4HHEUkhtbGHY_slI8mCC1ODR5xhgPLw6-FHfLwqdvgTEQRw8VAJmKoo1vgpCN-vtYp-z-ZK7JzlpkyrT4vSr5Nuw9zrE_NQJNh2HanahnNGDpDaC3heYc_NAjL7ZIdOBedsehAIIgF1tV5fP4UMmtaeJ63rBX6KnB4kx0Borg3eKy2ne_GLHh8CZRdrxXWabeq1Lg3nSVLSn7bIBW9I3Q.PnGPZXI7clE5Npn00Zc9Sg',
    cookies: {
      '__Secure-next-auth.callback-url': [Object],
      '__Host-next-auth.csrf-token': [Object],
      cf_clearance: [Object],
      cf_chl_2: [Object],
      '__Secure-next-auth.session-token': [Object],
      __cf_bm: [Object],
      cf_chl_rc_m: [Object]
    }
  }
}

**Comment by transitive-bullshit** [comment]
Please triple check everything in this comment: https://github.com/transitive-bullshit/chatgpt-api/issues/96#issuecomment-1350275343

If you're still getting 403s, then open a new issue with more detail than this one. What node.js version, what platform? What's the exact code you're using to access the API? etc.
