### ISSUE TITLE
Cannot find module 'unsupported'

### ISSUE THREAD

**Issue by dogukanakkaya** [transitive-bullshit/chatgpt-api#137]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Verify resrictions

- [X] I verify that I've double-checked all of the restrictions.

### Environment details

Node.js Version 19.2,
Brave Browser
MacOS Monterey 12.5
M1 Chip

### Link to the code that reproduces this issue

https://github.com/dogukanakkaya/chatgpt-code-vscode-extension

### Describe the Bug

When you upgrade chatgpt-api to `>=2.3.0` webpack errors 
```
Cannot find module 'unsupported'
```

### To Reproduce

to reproduce upgrade chatgpt-api module to `>=2.3.0` and try to run the extension

### Expected Behavior

It should work fine

### Note
Might be related to something else but version `2.2.0` works just fine.

**Comment by dogukanakkaya** [comment]
I have an idea for a hacky workaround but since it's not an urgent requirement I'll keep using `v2.2.0` until the solution you mention is here.

**Comment by timkmecl** [comment]
@dogukanakkaya Would you mind telling me about this hacky workaround that you mentioned? I am having a similar problem with my vscode extension.

**Comment by dogukanakkaya** [comment]
I was thinking about spinning a Node Server inside the extension and doing all the logic there. After that, communicate with that server via HTTP or whatever. But it's not ideal really, it will probably be slow and consume a lot of memory for a extension.

**Comment by dogukanakkaya** [comment]
Also seems like for VSCode extension development, we cannot upgrade above `v2.2.0` because of Node `>=18` requirement. For now latest VSCode runs Electron with Node 16 and this cannot be changed (https://github.com/Microsoft/vscode/issues/18253#issuecomment-271235914).
