### ISSUE TITLE
Error with running the demo

### ISSUE THREAD

**Issue by deezed420** [transitive-bullshit/chatgpt-api#138]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Verify resrictions

- [X] I verify that I've double-checked all of the restrictions.

### Environment details

Windows 11
Node js 9

### Link to the code that reproduces this issue

npx tsx demos/demo-conversation.ts

### Describe the Bug

It just doesnt run and any time I install esm, esbuild-kit or tsx it still doesnt work

### To Reproduce

run the demo file

### Expected Behavior

i wanted the demo to run lol

**Comment by MarvynSTAR** [comment]
Can you tell us more about the problem or the error that occurs? Without more information we can’t help you.

**Comment by transitive-bullshit** [comment]
Make sure you've installed the local NPM dependencies.

@deezed420 you're using Node.js 9, which is not supported. This package requires node >= 18.

**Comment by transitive-bullshit** [comment]
> It just doesnt run and any time I install esm, esbuild-kit or tsx it still doesnt work

You should never have to manually install any of these things. Just clone the repo, run `npm install` (or `yarn install` or `pnpm install`) and then run the demo with `npx tsx src/demo.ts`.

If you're running a really old version of Node.js, however, none of this will work.

**Comment by deezed420** [comment]
sorry I was running Node 19.

**Comment by deezed420** [comment]
and yes I will try cloning the repo and seeing if it works.
