### ISSUE TITLE
At capacity false positives

### ISSUE THREAD

**Issue by luphoria** [transitive-bullshit/chatgpt-api#141]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Verify resrictions

- [X] I verify that I've double-checked all of the restrictions.

### Environment details

Node.js version: v19.2.0
Browser version: ungoogled-chromium (flatpak)
OS: Arch Linux

### Link to the code that reproduces this issue

https://github.com/transitive-bullshit/chatgpt-api/blob/main/src/openai-auth.ts#L237

### Describe the Bug

Currently, the way that this api checks if ChatGPT is at capacity is with the banner message. But, this banner message isn't indicative of ChatGPT being down - just indicates that it will be slow. There is a separate page for when ChatGPT is completely unavailable.
I disabled the check by commenting [L237 of src/openai-auth.ts](https://github.com/transitive-bullshit/chatgpt-api/blob/main/src/openai-auth.ts#L237) to verify that yes, ChatGPT was still up.

### To Reproduce

- Clone https://github.com/transitive-bullshit/chatgpt-api/
- `npm i`
- npx tsx demos/demo.ts
- Enter captchas
- Crash:
```
ChatGPTError: ChatGPT is at capacity: JSHandle@node
    at checkForChatGPTAtCapacity (/home/trent/DeadNetGPT/chatgpt-api/src/openai-auth.ts:243:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Timeout.waitForCapacityText (/home/trent/DeadNetGPT/chatgpt-api/src/openai-auth.ts:128:15) {
  statusCode: 503
}
ChatGPTError: ChatGPT is at capacity: JSHandle@node
    at checkForChatGPTAtCapacity (/home/trent/DeadNetGPT/chatgpt-api/src/openai-auth.ts:243:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Timeout.waitForCapacityText (/home/trent/DeadNetGPT/chatgpt-api/src/openai-auth.ts:128:15) {
  statusCode: 503
}
```

### Expected Behavior

At most, chatgpt being slow at time of command execution should be a warning, definitely not an error and exit.

**Comment by transitive-bullshit** [comment]
@luphoria sorry; this made it's way in by accident. Removed this erroneous check in https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v2.3.3

**Comment by transitive-bullshit** [comment]
Thanks!
