### ISSUE TITLE
ChatGPTAPIBrowser  + Google -> JSHandles can be evaluated only in the context they were created!

### ISSUE THREAD

**Issue by giugrilli** [transitive-bullshit/chatgpt-api#151]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Verify resrictions

- [X] I verify that I've double-checked all of the restrictions.

### Environment details

macos, chrome

### Link to the code that reproduces this issue

none

### Describe the Bug

on api.init()
JSHandles can be evaluated only in the context they were created!

### To Reproduce

use the demos ChatGPTAPIBrowser + google login

### Expected Behavior

not failing

**Comment by giugrilli** [comment]
workaround is here

`
    const chatUrl = 'https://chat.openai.com/chat'
    const url = this._page.url().replace(/\/$/, '')

    console.log(url)
    console.log()

    if (url !== chatUrl) {
      await this._page.goto(chatUrl, {
        waitUntil: 'networkidle2'
      })
    }
`

removing the url !== chaturl check it forces the page reload and everything works

**Comment by mtaupiq** [comment]
> workaround is here
> 
> const chatUrl = 'https://chat.openai.com/chat' const url = this._page.url().replace(//$/, '')
> 
> ```
> console.log(url)
> console.log()
> 
> if (url !== chatUrl) {
>   await this._page.goto(chatUrl, {
>     waitUntil: 'networkidle2'
>   })
> }
> ```
> 
> removing the url !== chaturl check it forces the page reload and everything works

where you put that code?

**Comment by transitive-bullshit** [comment]
@mtaupiq @giugrilli please upgrade to https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v3.2.3 and let me know if it fixes your issue. I added some extra code to help with this.

If you're still seeing this issue, please reopen. Thanks!
