### ISSUE TITLE
Callback/Event handler support when cloudflare randomly ask for anti-robot check.

### ISSUE THREAD

**Issue by eebssk1** [transitive-bullshit/chatgpt-api#154]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Verify resrictions

- [X] I verify that I've double-checked all of the restrictions.

### Environment details

18.0.1 from nodesource
Debian 11
chrome from official

### Link to the code that reproduces this issue

Not relevant

### Describe the Bug

Currently, there's no way to know/handle random anti-robot check from cloudflare.

### To Reproduce

sendMessage fails because cloudflare requires anti-robot check again if it thinks us suspicious. 

### Expected Behavior

callback/'on' like event handle support when cloudflare requires check again so we can get notified quickly.

**Comment by transitive-bullshit** [comment]
I'm experimenting with maximizing the window when this happens, and then minimizing the window once cloudflare is out of the way.

Thoughts?

**Comment by eebssk1** [comment]
> I'm experimenting with maximizing the window when this happens, and then minimizing the window once cloudflare is out of the way.
> 
> Thoughts?

Nah. I'm using Xvnc on my server, the chrome window is always centered, not any movement are done after it starts up.

**Comment by transitive-bullshit** [comment]
The latest release added support for CAPTCHA automation which may solve your problem, though it is using a paid service. See https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v3.0.0 for details.

**Comment by transitive-bullshit** [comment]
I think v3 should solve this by automatically bypassing captchas. Please let me know if it's still an issue for you.
