### ISSUE TITLE
fix for ChatGPT is at capacity.

### ISSUE THREAD

**Issue by anishniroula1** [transitive-bullshit/chatgpt-api#157]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Verify resrictions

- [X] I verify that I've double-checked all of the restrictions.

### Environment details

N/A

### Link to the code that reproduces this issue

n/A

### Describe the Bug

When ChatGPT is at its capacity, instead of throwing an error, have you considered refreshing the page until you get the login page? It is somewhat annoying when it shows the capacity message and the application stop working. 

### To Reproduce

Run any demo file.

### Expected Behavior

``` 
async function checkForChatGPTAtCapacity(page: Page) {
  // console.log('checkForChatGPTAtCapacity', page.url())
  // let res: any[]
  //
  // try {
  //   res = await page.$x("//div[contains(., 'ChatGPT is at capacity')]")
  // console.log('capacity1', els)
  // if (els?.length) {
  //   res = await Promise.all(
   //     els.map((a) => a.evaluate((el) => el.textContent))
  //   )
   //   console.log('capacity2', res)
   // }
  // } catch (err) {
  // ignore errors likely due to navigation
  // }
  //
  // if (res?.length) {
  //   const error = new types.ChatGPTError('ChatGPT is at capacity')
  //   error.statusCode = 503
  //   throw error
  // }
  await delay(3000)
  let extractedText = await page.$eval('*', (el: any) => el.innerText)
  console.log(extractedText.includes('ChatGPT is at capacity right now'))

  while (extractedText.includes('ChatGPT is at capacity right now')) {
    await page.goto('https://chat.openai.com/auth/login')
    await delay(3000)
    extractedText = await page.$eval('*', (el: any) => el.innerText)
    if (!extractedText.includes('ChatGPT is at capacity right now')) {
      break
    }
  }
}

**Comment by transitive-bullshit** [comment]
Thanks @anishniroula1; I just added support for similar retry logic in https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v3.1.0

Let me know how that works for you.
