### ISSUE TITLE
Nopecha not working

### ISSUE THREAD

**Issue by DaftMonk** [transitive-bullshit/chatgpt-api#161]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Verify resrictions

- [X] I verify that I've double-checked all of the restrictions.

### Environment details

Node v18.12.0
Chrome: Version 108.0.5359.124 (Official Build) (arm64)
Mac 12.1

### Link to the code that reproduces this issue

N/A

### Describe the Bug

Set the NOPECHA_KEY in the env.

When initializing the ChatGPTApi in browser mode, i get this error:

```
/Users/tyhenkel/dev/chat-api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:237
                    ? new Error(`${response.errorText} at ${url}`)
                      ^

Error: net::ERR_BLOCKED_BY_CLIENT at chrome-extension://npgnhlnhpphdlkfdnggbdpbhoopefaai/popup.html
    at navigate (/Users/tyhenkel/dev/chat-api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:237:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Frame.goto (/Users/tyhenkel/dev/chat-api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:206:21)
    at async CDPPage.goto (/Users/tyhenkel/dev/chat-api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:440:16)
    at async getBrowser (file:///Users/tyhenkel/dev/chat-api/node_modules/chatgpt/build/index.js:945:5)
    at async ChatGPTAPIBrowser.initSession (file:///Users/tyhenkel/dev/chat-api/node_modules/chatgpt/build/index.js:1151:23)
    at async file:///Users/tyhenkel/dev/chat-api/dist/src/index.js:81:1
```

### To Reproduce

Set NOPECHA_KEY

### Expected Behavior

Expected NOPECACHA to work

**Comment by danielehrhardt** [comment]
Same error.

**Comment by transitive-bullshit** [comment]
Hmmm, are you sure that puppeteer is using Chrome and not Chromium? Just trying to think of what might be causing this.

**Comment by danielehrhardt** [comment]
> 

yes chrome is used. 
Windows 11
Node 19.2.0

**Comment by danielehrhardt** [comment]
Maybe you have installed the extension in your chrome browser.

**Comment by transitive-bullshit** [comment]
Hmmm I haven't tested on windows. Let me know if you figure it out.

**Comment by DaftMonk** [comment]
I'm having the issue on Mac.

Here's a screenshot of my chrome://version from my automated browser. Maybe worth comparing with yours?
<img width="352" alt="image" src="https://user-images.githubusercontent.com/2505273/208265507-904ede1d-8890-49fe-b9dd-d0e7dd2830fc.png">

**Comment by danielehrhardt** [comment]
yes, the reason is that the extension id changes

**Comment by danielehrhardt** [comment]
It works when you comment out this code:
![image](https://user-images.githubusercontent.com/19570043/208265718-025148a8-dec1-43de-a48e-7323846c66df.png)

**Comment by transitive-bullshit** [comment]
@DaftMonk @danielehrhardt can you try https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v3.0.1?

The extension ID is now dynamic.

@danielehrhardt I still can't get the extension to properly recognize the API key without this extra code. Without it, it just uses the default free quota of 99 tokens which goes by really fast since each recaptcha uses like 5-10 tokens.

**Comment by danielehrhardt** [comment]
> @DaftMonk @danielehrhardt can you try https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v3.0.1?
> 
> The extension ID is now dynamic.
> 
> @danielehrhardt I still can't get the extension to properly recognize the API key without this extra code. Without it, it just uses the default free quota of 99 tokens which goes by really fast since each recaptcha uses like 5-10 tokens.

works

**Comment by danielehrhardt** [comment]
> @DaftMonk @danielehrhardt can you try https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v3.0.1?
> 
> The extension ID is now dynamic.
> 
> @danielehrhardt I still can't get the extension to properly recognize the API key without this extra code. Without it, it just uses the default free quota of 99 tokens which goes by really fast since each recaptcha uses like 5-10 tokens.

For me, the code is already used and with your change, it will enter the code a second time.

**Comment by transitive-bullshit** [comment]
interesting; honestly the nopecha extension is pretty buggy, so I wouldn't be surprised if it works on some systems and not on others. At least with this code, it will set the key either way.

Closing as fixed for now. Thanks, everyone 🙏

**Comment by danielehrhardt** [comment]
> interesting; honestly the nopecha extension is pretty buggy, so I wouldn't be surprised if it works on some systems and not on others. At least with this code, it will set the key either way.
> 
> Closing as fixed for now. Thanks, everyone 🙏

Not 100%, the field will be filled with the code twice so it will not save correctly. I think it would be good to clear the field before then it should work both ways.

**Comment by transitive-bullshit** [comment]
Are you 100% sure?

The code is using:

```
        await settingsInput.type(nopechaKey)
        await settingsInput.evaluate((el, value) => {
          el.value = value
        }, nopechaKey)
```

so it's setting the value of that text input directly which should override any previous values.. Can you double check that it isn't working by actually pausing the extension *after* it does it's thing and including a screenshot of the value in the extension popup window?

Thanks.

**Comment by DaftMonk** [comment]
Confirmed this is working for me with the new version! Thank you for the great work on this project!
