### ISSUE TITLE
Google login not working if 2FA is on

### ISSUE THREAD

**Issue by MuTsunTsai** [transitive-bullshit/chatgpt-api#169]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node.js 18.12.1
Chrome 108.0.5359.125
Windows 11 22H2

### Describe the Bug

Google login is not working if 2FA is on. While still waiting for 2FA, it closes the browser and returns with error message.

**Comment by gd1m3y** [comment]
Hey @transitive-bullshit  i have disabled MFA for google but it still asks me for a  code while using the google login any idea how can i disable that

**Comment by NZX-DeSiGN** [comment]
You can bypass this by inviting a new member to your open ai organization (in your profil settings).
You can use the gmail alias to have a new email youremailaddress+ai@gmail.com for example (you will receive the email at youremailaddress@gmail.com) then finalize your member account.
You can then use this account to login and use Chat GPT.

**Comment by GavinOvsak** [comment]
Same issue here. I see a flash where it tries to send a message to my phone asking for me to hit "Approve" but it gives up within a second. Is there a flag to just let me complete the login? Making another member account doesn't change my Google Login requiring approval.

**Comment by GavinOvsak** [comment]
Update: I got it to work by adding the highlighted code here in index.js (line 839):
<img width="630" alt="image" src="https://user-images.githubusercontent.com/1077502/209489452-d4d22c62-c8c8-4876-b87a-1d87ad1bdf30.png">

**Comment by transitive-bullshit** [comment]
Yep; I use username+1@gmail.com, username+2@gmail.com, ...

Also, sorry I haven't reviewed this yet; it does look like a great PR and will merge; just spending time with family for Christmas at the moment. 🎄 💕

**Comment by gefeiyanga** [comment]
> Same issue

+1

**Comment by transitive-bullshit** [comment]
I think the solution to this is a slight fix to the puppeteer code in `src/openai-auth.ts`. PRs are welcome 🙏

**Comment by mabry1985** [comment]
> You can bypass this by inviting a new member to your open ai organization (in your profil settings). You can use the gmail alias trick to have a new email address : use [youremailaddress+ai@gmail.com](mailto:youremailaddress+ai@gmail.com) for example (you will receive the email at [youremailaddress@gmail.com](mailto:youremailaddress@gmail.com)) then finalize your member account. You can then use this account to login and use Chat GPT.

How do you go about spoofing a phone number for the authentication? I tried google voice but it got pinged. Never needed to do this before, so pardon me if it's an easy solution.

**Comment by lys623** [comment]
Same issue

**Comment by N3oTraX** [comment]
> Update: I got it to work by adding the highlighted code here in index.js (line 839): <img alt="image" width="630" src="https://user-images.githubusercontent.com/1077502/209489452-d4d22c62-c8c8-4876-b87a-1d87ad1bdf30.png">

Hi, I'm not able to get the same code like you got : 


`
     if (isGoogleLogin) {
        await page.waitForSelector('button[data-provider="google"]', {
          timeout: timeoutMs
        });
        await page.click('button[data-provider="google"]');
        await page.waitForSelector('input[type="email"]');
        await page.type('input[type="email"]', email);
        await Promise.all([
          page.waitForNavigation(),
          await page.keyboard.press("Enter")
        ]);
        await page.waitForSelector('input[type="password"]', { visible: true });
        await page.type('input[type="password"]', password);
        await delay(50);
        submitP = () => page.keyboard.press("Enter");
      } else if (isMicrosoftLogin) {
`

Any idea what I could modify to fit your approach ?

I tryed to make the alias trick but it failed to connect and I get the same error like others with 2FA on ;

`yarn run v1.22.19
mtx-chatgpt  | $ node dist/index.js
mtx-chatgpt  | /usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:64
mtx-chatgpt  |                 this.terminate(new Errors_js_1.TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`));`

**Comment by transitive-bullshit** [comment]
Try upgrading to the latest version; we're now using the official API, which no longer uses puppeteer so problems like this should go away completely: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.0.0
