### ISSUE TITLE
Add proxy auth 

### ISSUE THREAD

**Issue by timmsGithub** [transitive-bullshit/chatgpt-api#171]
### Describe the feature

Hello!

It would be very easy to add proxy auth!
Proxy format user:pass@ip:port

`if (proxyServer) {
    const ipPort = proxyServer.split("@")[1]
    puppeteerArgs.push(`--proxy-server=${ipPort}`);
  }`

and

`this._page = (await this._browser.pages())[0] || await this._browser.newPage();
      if(this._proxyServer){
        const username = this._proxyServer.split("@")[0].split(":")[0]
        const password = this._proxyServer.split("@")[0].split(":")[1]
        await this._page.authenticate({ username, password });
      }
      this._page.evaluateOnNewDocument(() => {
        window.localStorage.setItem("oai/apps/hasSeenOnboarding/chat", "true");
        window.localStorage.setItem(
          "oai/apps/hasSeenReleaseAnnouncement/2022-12-15",
          "true"
        );
      });`

Would be pretty nice if you can add this!

**Comment by transitive-bullshit** [comment]
@timmsGithub definitely; would you mind opening a PR?
