### ISSUE TITLE
ERROR:ozone_platform_x11.cc(238)] Missing X server or $DISPLAY

### ISSUE THREAD

**Issue by mtaupiq** [transitive-bullshit/chatgpt-api#172]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Here my Dockerfile:
```
FROM zenika/alpine-chrome:with-node

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD 1
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium-browser

WORKDIR /usr/src/app

COPY --chown=chrome package*.json ./

RUN npm install

COPY --chown=chrome . ./

EXPOSE 3000

CMD [ "node", "index.js" ]
```

### Describe the Bug

```
Dec 19 09:16:59 PM  /usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299
Dec 19 09:16:59 PM              reject(new Error([
Dec 19 09:16:59 PM                     ^
Dec 19 09:16:59 PM  
Dec 19 09:16:59 PM  Error: Failed to launch the browser process!
Dec 19 09:16:59 PM  [18:18:1219/141659.083685:ERROR:ozone_platform_x11.cc(238)] Missing X server or $DISPLAY
Dec 19 09:16:59 PM  [18:18:1219/141659.085321:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
Dec 19 09:16:59 PM  
Dec 19 09:16:59 PM  
Dec 19 09:16:59 PM  TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
Dec 19 09:16:59 PM  
Dec 19 09:16:59 PM      at onClose (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
Dec 19 09:16:59 PM      at ChildProcess.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:290:24)
Dec 19 09:16:59 PM      at ChildProcess.emit (node:events:525:35)
Dec 19 09:16:59 PM      at ChildProcess._handle.onexit (node:internal/child_process:291:12)
Dec 19 09:16:59 PM  
Dec 19 09:16:59 PM  Node.js v18.12.1
```

**Comment by amosayomide05** [comment]
Remove the executable path

**Comment by transitive-bullshit** [comment]
Most likely you need to setup `xvfb` for the headful portion of chrome. That's what this message is saying: `Missing X server or $DISPLAY`

**Comment by amosayomide05** [comment]
> Most likely you need to setup `xvfb` for the headful portion of chrome. That's what this message is saying: `Missing X server or $DISPLAY`

I was having this error earlier
All i did was remove the chrome executable path and it worked

**Comment by amosayomide05** [comment]
Now i am facing another error
Please how do i fix

ChatGPTAPI error 422

**Comment by mtaupiq** [comment]
> > Most likely you need to setup `xvfb` for the headful portion of chrome. That's what this message is saying: `Missing X server or $DISPLAY`
> 
> I was having this error earlier All i did was remove the chrome executable path and it worked

can i see your dockerfile?

**Comment by EmmanuelPenkra** [comment]
I was facing the same issue but figured out a fix.

Add this to your Dockerfile:
`RUN apt-get update -y \
  && apt-get -y install xvfb \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/*`

In your package.json, begin your start script with 'xvfb-run --auto-servernum' eg:
`xvfb-run --auto-servernum node app.js`

That's it!

**Comment by EmmanuelPenkra** [comment]
@amosayomide05

**Comment by amosayomide05** [comment]
> @amosayomide05 

I don't use docker

I have zero clue on how to use it!

Can i input it on terminal?

**Comment by amosayomide05** [comment]
And i am using windows not linux

**Comment by EmmanuelPenkra** [comment]
@amosayomide05  

If you're using Ubuntu Windows subsystem for Linux or you have apt-get installed, you can run:
`sudo apt-get install xvfb`

If not, you may checkout https://stackoverflow.com/questions/41099218/xvfb-on-windows

**Comment by amosayomide05** [comment]
Ok thanks for the link

**Comment by mtaupiq** [comment]
> I was facing the same issue but figured out a fix.
> 
> Add this to your Dockerfile: `RUN apt-get update -y \ && apt-get -y install xvfb \ && rm -rf /var/lib/apt/lists/* /var/cache/apt/*`
> 
> In your package.json, begin your start script with 'xvfb-run --auto-servernum' eg: `xvfb-run --auto-servernum node app.js`
> 
> That's it!

i am trying your solution but it show error: xvfb-run: error: xauth command not found

**Comment by tobq** [comment]
> > I was facing the same issue but figured out a fix.
> > Add this to your Dockerfile: `RUN apt-get update -y \ && apt-get -y install xvfb \ && rm -rf /var/lib/apt/lists/* /var/cache/apt/*`
> > In your package.json, begin your start script with 'xvfb-run --auto-servernum' eg: `xvfb-run --auto-servernum node app.js`
> > That's it!
> 
> i am trying your solution but it show error: xvfb-run: error: xauth command not found (solved)

How'd you fix the xauth issue?
