### ISSUE TITLE
chatgptapi error 429

### ISSUE THREAD

**Issue by zjwang21** [transitive-bullshit/chatgpt-api#174]
### Describe the feature

Is there any solutions for the error code 429?After the api is continuously called for 20 minutes, the error happens. 
I will appreciate it if you let me know if i missed something for solving this too much requests error.
Pretty good repo, thanks for the work.

![image](https://user-images.githubusercontent.com/115514981/208615440-a8fb1a10-a454-4ef0-9937-2925451d007f.png)

**Comment by transitive-bullshit** [comment]
This can happen if you are calling the API too frequently.

The only workaround that I'm aware of is to use multiple accounts and switch off between them like I'm doing for my twitter bot: https://github.com/transitive-bullshit/chatgpt-twitter-bot/blob/main/src/chatgpt-api-pool.ts

The same 429s will happen in the browser if you hit the endpoint too many times, so there's really nothing we can do on our end to avoid them.

**Comment by yayaQAQ** [comment]
> This can happen if you are calling the API too frequently.
> 
> The only workaround that I'm aware of is to use multiple accounts and switch off between them like I'm doing for my twitter bot: https://github.com/transitive-bullshit/chatgpt-twitter-bot/blob/main/src/chatgpt-api-pool.ts
> 
> The same 429s will happen in the browser if you hit the endpoint too many times, so there's really nothing we can do on our end to avoid them.

Multiple accounts will get the ip blocked faster.

**Comment by transitive-bullshit** [comment]
I've been running 10+ accounts on a residential IP for ~2.5 weeks now without any IP problems.

If your IP is getting blocked, it means you're abusing the API endpoints in some way.

**Comment by BENSAFOUAN-Abdelhalim** [comment]
I think this error occurs when you ask the API before getting the answer to the first question.

**Comment by securigy** [comment]
I suddenly started getting 429 error. However, I am not exceeding any rate limits (20/min).
I get it on the 1st call when posting this prompt:

Generate 5 Titles on the topic: Travelling Alaska
with Keywords: Fishing, hunting, Iditarod, Denali
and Start Outlines with: Exploring, Introducing, Discovering, Discover, Explore
 and Use Tone of voice: Professional
and use Point of view: First Person
with Language: English

Td:lr

Then, I tried a smaller prompt of "Generate 5 Titles on the topic: Travelling Alaska" but still get 429...
Not sure what to do now, I make a single call every few minutes, just trying...

**Comment by securigy** [comment]
I also created another account, but that did not resolve the problem. I also tried VPN to hide my IP but it did not work... Did OpenAI changed their APIs or rules yesterday, Jan 8, 2023?

**Comment by Abdelwahed-Aridj** [comment]
yeah same, barely used it then it gave me error 429
