### ISSUE TITLE
Can't find package puppeteer-extra-plugin-stealth@^2.11.1

### ISSUE THREAD

**Issue by slalx** [transitive-bullshit/chatgpt-api#175]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node@v16.14.2

### Describe the Bug

Can't find package puppeteer-extra-plugin-stealth@^2.11.1

![image](https://user-images.githubusercontent.com/137816/208670362-046bd4f3-6025-469a-9eac-c5ec435484b1.png)

**Comment by ShiranAbir** [comment]
You're using Node.js version 16.
From v2.3.0 Node.js version 18 is required (it's also stated in the Readme):
https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v2.3.0

Upgrade to Node.js v18 and try again.

**Comment by transitive-bullshit** [comment]
Did you resolve this by upgrading `node`? Also, not sure what `tnpm` is, but I've only tested this package with `npm`/`yarn`/`pnpm`.
