### ISSUE TITLE
Add an automated way to fetch and refresh session tokens

### ISSUE THREAD

**Issue by transitive-bullshit** [transitive-bullshit/chatgpt-api#18]
This is currently the biggest hindrance with this package (and any other approach which uses the unofficial REST API).

At some point, session tokens expire. This is currently recognized and handled by throwing an error with the message `ChatGPT failed to refresh auth token. Error: session token has expired`, but most long-running integrations will need a better solution for this going forwards.

**Comment by Lesiuk** [comment]
Using playwright is probably the easiest way.

**Comment by transitive-bullshit** [comment]
@Lesiuk it'd be pretty difficult to automate logging in with various types of credentials via any sort of headless browser approach.

https://github.com/rawandahmad698/PyChatGPT is a python hack that looks interesting, although I'm not sure about it's robustness.

**Comment by transitive-bullshit** [comment]
See also https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/revChatGPT.py#L133

**Comment by chitalian** [comment]
> @Lesiuk it'd be pretty difficult to automate logging in with various types of credentials via any sort of headless browser approach.
> 
> https://github.com/rawandahmad698/PyChatGPT is a python hack that looks interesting, although I'm not sure about it's robustness.

It is pretty robust

> See also https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/revChatGPT.py#L133

I am using this for aistorychat.com and it is pretty good

**Comment by transitive-bullshit** [comment]
@chitalian are you using the python version, or have you converted it to JS / TS?

**Comment by chitalian** [comment]
> @chitalian are you using the python version, or have you converted it to JS / TS?

I am using the python version. I basically made a server implementation here
https://github.com/dataaug/chatGPT-server

**Comment by wsxiaoys** [comment]
Actual code generating session token from username / password locates here:

https://github.com/acheong08/OpenAIAuth/blob/main/src/OpenAIAuth/OpenAIAuth.py

**Comment by diciaup** [comment]
Yesterday I have done a CLI that use electron to automatically login the user and get the session token:
https://github.com/diciaup/assistant-cli

**Comment by transitive-bullshit** [comment]
@diciaup feel free to open a PR to add this to the readme under the example projects section

**Comment by transitive-bullshit** [comment]
Here's how I'm handling this for my Twitter bot: https://github.com/transitive-bullshit/chatgpt-twitter-bot/blob/main/src/openai-auth.ts, which uses the [python revChatGPT module](https://github.com/acheong08/ChatGPT) under the hood.

Obviously, I'd prefer to encourage people to use a Node.js-based solution, but for now I think this is the best option available.

See also #83

**Comment by shubham8550** [comment]
use this to renew token (i have exam in week otherwise i would have made pull :]
https://github.com/puppeteer/puppeteer

 :)

**Comment by transitive-bullshit** [comment]
The latest release includes a puppeteer-based solution to automate login. Still TODO is automating potential CAPTCHAS.

https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v2.3.0
