### ISSUE TITLE
Does the package still work?

### ISSUE THREAD

**Issue by lukasvdberk** [transitive-bullshit/chatgpt-api#181]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Operating system: Ubuntu 21.10
Node: v18.11.0

chatgpt package version:   "chatgpt": "^3.3.1",

### Describe the Bug

First of all love that you put together a package so fast without documentation!

I tried running it today but got stuck verifying the google Captcha (see screenshot below). I assume that this is something that can not be bypassed without a human completing the captcha right? (if I complete the capatcha myself it does continue to fill in the password and ask the question)

![image](https://user-images.githubusercontent.com/38686669/208936483-75d146b5-c7a7-4db8-8089-05e4fdcf5471.png)

Thanks!

**Comment by timmsGithub** [comment]
Working very well, try to include the captcha api key in your loginCredentials

**Comment by transitive-bullshit** [comment]
If you want to automatically bypass captchas, make sure you're setting either `NOPECHA_KEY` or `CAPTCHA_TOKEN`.

See the readme section on CAPTCHAs for more details: https://github.com/transitive-bullshit/chatgpt-api#captchas

**Comment by lukasvdberk** [comment]
Thank you! I will have a look at that!
