### ISSUE TITLE
Char text issue? 

### ISSUE THREAD

**Issue by JarJarBeatyourattitude** [transitive-bullshit/chatgpt-api#184]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node.js v18.12.1, chrome on newest Windows 11 

### Describe the Bug

Tried to run the program with password and email set as variables, no captcha stuff set up yet, got:

PS C:\Users\jshan\OneDrive\Desktop\ChatGptConversation> node test.mjs
C:\Users\jshan\OneDrive\Desktop\ChatGptConversation\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Input.js:205
        for (const char of text) {
                           ^

TypeError: text is not iterable

Sorry if I'm missing something obvious, I'm not very experienced. Any tips would help. Thanks

**Comment by transitive-bullshit** [comment]
Add some logging to your `test.mjs` to make sure that `email` and `password` are set correctly.

This looks like something that will happen if the text you're passing in isn't a valid string.
