### ISSUE TITLE
Repeatedly input Key, resulting in nopecha verification error

### ISSUE THREAD

**Issue by mtrucc** [transitive-bullshit/chatgpt-api#185]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

NodeJS 19
Chrome 103
MacOS 13.0

### Describe the Bug

https://github.com/transitive-bullshit/chatgpt-api/blob/091914a03c3f60f6fd584c4669f864733abb3083/src/openai-auth.ts#L434

Repeatedly input Key, resulting in nopecha verification error

For example, the correct key is 123456
It will enter 123456123456

**Comment by transitive-bullshit** [comment]
I have seen this as well, and so far my attempts to mitigate it have been unsuccessful.

**Comment by danielehrhardt** [comment]
This Plugin behaves really strange :D the normal stuff did not worked. 
The change in the PR looks like that it works most reliable. 
https://github.com/transitive-bullshit/chatgpt-api/issues/185
