### ISSUE TITLE
how to clear conversation?

### ISSUE THREAD

**Issue by zjwang21** [transitive-bullshit/chatgpt-api#186]
### Describe the feature

i used three accounts to use this api and the chatgpt timeout error occurs sometimes. I wonder if this error was caused by too many conversations(threads). Can this be solved in some way or how to clear the conversations?

**Comment by Glowin** [comment]
What do you mean "clear conversation"? If you need send request without conversationId and parentId, you can just run `await api.sendMessage('Hello World!')`, if you need reset browser, use [initSession](https://github.com/transitive-bullshit/chatgpt-api/blob/main/docs/classes/ChatGPTAPIBrowser.md#initsession).

If you get timeout error casually, it maybe openAI server is on the heavy balance.

If you use this api in huge request, you should low your request to 50 in 1 hour.

**Comment by transitive-bullshit** [comment]
I don't think that too many conversation threads is an issue from my pretty thorough testing.

As @Glowin mentioned, if you want to create a new thread, just don't pass `conversationId` and `parentMessageId`.
