### ISSUE TITLE
Who has encountered this problem

### ISSUE THREAD

**Issue by burialz** [transitive-bullshit/chatgpt-api#188]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

ChatGPTError: Failed to authenticate session

### Describe the Bug
![image](https://user-images.githubusercontent.com/49971836/209103447-191df7e2-5537-4c41-8710-32f6780659e1.png)

**Comment by danielehrhardt** [comment]
Sometimes i have the same Problem i am not sure why.

**Comment by transitive-bullshit** [comment]
Add some more debug logging and let us know what you find.

Also, add `debug: true` to the `ChatGPTAPIBrowser` constructor which may help diagnose.

**Comment by reidsneo** [comment]
+1
```

/node_modules/chatgpt/build/index.js:1384
      throw new ChatGPTError("Failed to authenticate session");

ChatGPTError: Failed to authenticate session
    at ChatGPTAPIBrowser.initSession (file:///home/runner/project/node_modules/chatgpt/build/index.js:1384:13)
```

**Comment by BENSAFOUAN-Abdelhalim** [comment]
![image](https://user-images.githubusercontent.com/74852971/209314352-6060a7a5-3bbf-4dc1-8812-7517bd50f0d7.png)

i have the same error :

**Comment by firslov** [comment]
![图片](https://user-images.githubusercontent.com/9650948/209425606-91a828b2-d886-4fea-ae6a-6b8482bd6b62.png)

i have the same error

**Comment by reidsneo** [comment]
I want to recollect about this issue, did your guys using google authentication (OAuth) instead of using username and password?

**Comment by BENSAFOUAN-Abdelhalim** [comment]
yes by using isGoogleLogin: true

**Comment by BENSAFOUAN-Abdelhalim** [comment]
at first it works well, until 20/12/2022

**Comment by reidsneo** [comment]
In my case also same, while using isGoogleLogin: true
for some reason after pupetter automatically process the Oauth login, there was additional "verification step" like entering OTP to mobile to verify google authorization process, this step seem skipped and lead to the error above
it work on my local pc, but not work on newly logged google login my remote server
