### ISSUE TITLE
can't run the demo samples

### ISSUE THREAD

**Issue by waverider404** [transitive-bullshit/chatgpt-api#193]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node version(19.3.0), OS(windows), browser (Chrome)

### Describe the Bug

When i try to run the demos, I am getting this error

`
(node:18396) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Failed to launch the browser process! spawn C:\Program Files\Google\Chrome\Application\chrome.exe ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (c:\Users\adene\chatgpt\chatgpt-api\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:299:20)
    at ChildProcess.<anonymous> (c:\Users\adene\chatgpt\chatgpt-api\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:293:24)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
`

**Comment by Tpgainz** [comment]
Hi firend !
Wrong path, be sure your windows path correspond to C:\Program Files\Google\Chrome\Application\chrome.exe.
Maybe you just need to edit openai-auth line 472 ???
For example
From

`C:\Program Files\Google\Chrome\Application\chrome.exe`
To
`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`

According to your system

The path is a string so it need to correspond with your system path.

**Comment by waverider404** [comment]
Awesome, thanks it's working now :)

**Comment by liuliangsir** [comment]
@Tpgainz You can also try [setting the executablePath with Environment-Variable](https://stackoverflow.com/a/74887546/4441984). Add the following to your own bash configuration file like `~/.bashrc` if you are running some commands from git bash.
```
export PUPPETEER_EXECUTABLE_PATH="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
```
