### ISSUE TITLE
can not find a button "#__next .btn-primary"

### ISSUE THREAD

**Issue by yayaQAQ** [transitive-bullshit/chatgpt-api#196]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

v18.12.1 node
Google Chrome 108.0.5359.124
ubuntu 20.04

### Describe the Bug

<img width="882" alt="image" src="https://user-images.githubusercontent.com/20497531/209420090-da4abe43-1ee3-4744-8f73-7030c269b02c.png">

**Comment by Glowin** [comment]
I also encounter this problem frequently. Every time after recognizing the captcha, it will occasionally not go to click the next button. It keeps getting stuck in this step, resulting in a 120,000ms delay error. The overall probability is around 60%.

I think the reason for this is that the next click is triggered according to the delay, and if the CAPTCHA recognition takes too long, the next click will be missed.

**Comment by aviavinas** [comment]
What was in your Docker file?

**Comment by yayaQAQ** [comment]
![page](https://user-images.githubusercontent.com/20497531/209424385-5567c6b0-e7cd-4033-8faa-6da94b6ed47e.png)
I took a screenshot of where I was stuck and found that it was cf verified, so it seems that using xvfb is not enough to pass the cf verification. (I used to be able to run it with xvfb)

**Comment by transitive-bullshit** [comment]
@yayaQAQ does this only repro when using `xvfb`?

**Comment by yayaQAQ** [comment]
yes, I tried window, mac(with desktop), ubuntu18.04, ubuntu20.04(without desktop)
only the machine without desktop encountered this problem with xvfb-run.
what can i do next?
@transitive-bullshit

**Comment by yayaQAQ** [comment]
Strangely enough, the same code can be accessed consistently on a mac using a proxy; however, using windows (on google cloud platform) will get 429.

**Comment by Glowin** [comment]
@transitive-bullshit I repro at Macbook, not server.

**Comment by transitive-bullshit** [comment]
I'm not able to repro this using the latest version.

I've made a lot of changes to the `nopecha` and puppeteer initialization code to make things more robust. It's definitely not perfect, but I think this should be resolved now.

Feel free to re-open if you're still running into this issue after upgrading to the latest version – and include as much detail as possible – and I'll take another look.

Thanks!
