### ISSUE TITLE
openai website auto-login stops at the last step

### ISSUE THREAD

**Issue by firslov** [transitive-bullshit/chatgpt-api#197]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

nodejs v18.10.0
chrome Version 108.0.5359.124 (Official Build) (arm64)
macOS Version 12.3 M1

### Describe the Bug

![图片](https://user-images.githubusercontent.com/9650948/209421166-c5ec6361-fd0d-4304-bf4a-7cbc28a8e94e.png)

When I run the demo, nopecha works fine, but the automatic login of the openai website stops at this step in the picture, and I need to click the "continue" button manually to continue.

Is it normal？

**Comment by yayaQAQ** [comment]
Should be the reason for the network, but sometimes even the google server clicked no effect

**Comment by firslov** [comment]
I switched to a gmail account and added "isGoogleLogin: true", now the problem is gone.

**Comment by firslov** [comment]
https://github.com/transitive-bullshit/chatgpt-api/blob/main/src/openai-auth.ts#L614-L626

Here is the problem, Network delays can cause **page.$('textarea#g-recaptcha-response')** to get the wrong value. I added a delay in front and the problem was solved.
