### ISSUE TITLE
TimeoutError: Waiting for selector `#password` failed

### ISSUE THREAD

**Issue by Glowin** [transitive-bullshit/chatgpt-api#199]
### Verify latest release

- [x] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node: v18.12.1
OS: Mac OS 11.7
browser: chrome 108.0.5359.124

### Describe the Bug

Every time after recognizing the captcha, it will occasionally not go to click the next button. It keeps getting stuck in this step, resulting in a 120,000ms delay error. The overall probability is around 60%.

```
initialized nopecha extension with key I-H3A5U9V63FMT
/Users/glowin/Documents/projects/chatGPT/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:64
                this.terminate(new Errors_js_1.TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`));
                               ^

TimeoutError: Waiting for selector `#password` failed: Waiting failed: 120000ms exceeded
    at Timeout.<anonymous> (/Users/glowin/Documents/projects/chatGPT/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:64:32)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

Node.js v18.12.1
```
error occur at ~00:13
https://user-images.githubusercontent.com/1147941/209441270-949e6c5f-c4f8-4ad6-8e68-63b4761a0e30.mp4

**Comment by transitive-bullshit** [comment]
Confirming that I'm also seeing this some percentage of the time.

Will follow up once I figure out what's going on.

**Comment by transitive-bullshit** [comment]
Just released an update which should fix this: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v3.3.8

I haven't run into this since the fix, so closing for now. Please re-open if you run into this after upgrading.

Thanks!
