### ISSUE TITLE
Switching to direct API requests

### ISSUE THREAD

**Issue by ElijahPepe** [transitive-bullshit/chatgpt-api#2]
Headless Chrome seems a bit overkill for a Node.js API wrapper, and may not work on all machines (see line 36 in chatgpt-api.ts). The ChatGPT API allows direct requests given a CSRF token (which doesn't seem to change in my testing) and a session token, which can be obtained through the `/api/auth/session` endpoint.

**Comment by ElijahPepe** [comment]
Documentation on the various API endpoints:

`GET /api/auth/session` — Gets the current user and access token.
`GET /backend-api/models` — Gets the models (currently, only `text-davinci-002-render` is listed).
`POST /backend-api/moderations` — Given an input and model, assesses whether or not the string is flagged or blocked, and assigns the decision a moderation ID.
`POST /backend-api/conversation` — Creates or edits a prompt.
`POST /backend-api/conversation/message_feedback` — Votes on a prompt.

**Comment by transitive-bullshit** [comment]
Agreed that this is definitely worth investigating. I created the headless chrome version yesterday inspired by Daniel Gross's Whatsapp demo, but would greatly prefer to avoid the browser.

Very open to PRs and/or I'll look into this later today.

**Comment by spaceworkplatform** [comment]
@ElijahPepe I started to try implement the requests , I did the get session request successfully and then create moderation request and got back the moderation_id.

Can you make clear what to do from here to get the reply for this moderation ? like the next request if for conversation, but how I should know the message_id, conversation_id, parent_message_id params values ? from where exactly ?

Will help if you make clear the rest of the requests pipeline after moderation created, It will help me on my project and also I can help implement that here.

**Comment by ElijahPepe** [comment]
@spaceworkplatform The `/backend-api/conversation` endpoint only needs a `parent_message_id` and an `id`. Take a look at #3 for typings. Both of those IDs are randomly generated UUIDs. To add to a conversation, you can use `conversation_id` in your request with the conversation ID.

Getting a response from `/backend-api/conversation` is tricky, I haven't figured it out yet, but I'm sure it's possible.

**Comment by spaceworkplatform** [comment]
actually I did some tests and I started to understand that.
`/backend-api/conversation` response headers show us the content type is: `text/event-stream; charset=utf-8`, that means is server sent events - kind of streams each part of the conversation answer , so if you doing a http request and get the request plain body you going to get all the server sent events divided by lines (\n) and prefixed with data: 
More info regards server sent events stream can found here:
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

So basically the ChatGPT ui maybe use something like EventSource (as described on the link above) to dynamiclly "write" the model reply as it streams by this endpoint as events.

Take a look as such a response I managed to received:
`data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"content_type": "text", "parts": ["Hello! Is there something you would like to talk about? I'm here to"]}, "end_turn": null, "weight": 1.0, "metadata": {}, "recipient": "all"}, "conversation_id": "2c49337e-ace0-40e5-a723-b7eedb4207f9", "error": null} ◀

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"content_type": "text", "parts": ["Hello! Is there something you would like to talk about? I'm here to help"]}, "end_turn": null, "weight": 1.0, "metadata": {}, "recipient": "all"}, "conversation_id": "2c49337e-ace0-40e5-a723-b7eedb4207f9", "error": null} ◀

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"content_type": "text", "parts": ["Hello! Is there something you would like to talk about? I'm here to help with any questions you may"]}, "end_turn": null, "weight": 1.0, "metadata": {}, "recipient": "all"}, "conversation_id": "2c49337e-ace0-40e5-a723-b7eedb4207f9", "error": null} ◀

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"conte ▶

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"content_type": "text", "parts": ["Hello! Is there something you would like to talk about? I'm here to help with any questions you may have."]}, "end_turn": null, "weight": 1.0, "metadata": {}, "recipient": "all"}, "conversation_id": "2c49337e-ace0-40e5-a723-b7eedb4207f9", "error": null} ◀

data: {"message": {"id": "7f45fba1-a141-4bba-ba26-82212de404a4", "role": "assistant", "user": null, "create_time": null, "update_time": null, "content": {"content_type": "text", "parts": ["Hello! Is there something you would like to talk about? I'm here to help with any questions you may have."]}, "end_turn": null, "weight": 1.0, "metadata": {}, "recipient": "all"}, "conversation_id": "2c49337e-ace0-40e5-a723-b7eedb4207f9", "error": null} ◀

data: [DONE]
`

**Comment by ElijahPepe** [comment]
@spaceworkplatform Good observation! Looks like the tool I was using wasn't reading the stream. I used cURL and it is a stream.

[undici](https://github.com/nodejs/undici) is my tool of choice for requests and it seems like the fastest option.

**Comment by spaceworkplatform** [comment]
> @spaceworkplatform Good observation! Looks like the tool I was using wasn't reading the stream. I used cURL and it is a stream.
> 
> [undici](https://github.com/nodejs/undici) is my tool of choice for requests and it seems like the fastest option, if you're looking for a library to use.

Thanks :-) thats was tricky one, because it not typical response type and we not expect that, so on the chrome inspector also its hard to see the actual response.

We'll keep going this way, parsing the events, investigating all the right flow and I keep you posted soon

**Comment by transitive-bullshit** [comment]
https://github.com/wong2/chat-gpt-google-extension/blob/main/background/index.mjs has a good example of how to do this.

What remains to be seen is how effectively this can be done without an existing auth token, and whether or not generating a new / fresh auth token can be done via the unofficial API-only.

**Comment by ElijahPepe** [comment]
Generating an auth token might be possible using an existing API, might also require some tinkering with the site, but if OpenAI has an auth solution then we can theoretically use that.

**Comment by RomanHotsiy** [comment]
Here is a working client: https://github.com/RomanHotsiy/commitgpt/blob/main/client.ts

**Comment by transitive-bullshit** [comment]
@RomanHotsiy Awesome; looking into this now...

**Comment by transitive-bullshit** [comment]
Released https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v1.0.0  🚀 

Thanks to everyone who helped out in this thread 🙏 

Please open a new issue if you notice anything wrong while upgrading to the new major version.
