### ISSUE TITLE
Persistent sessions?

### ISSUE THREAD

**Issue by aaronteamAAR** [transitive-bullshit/chatgpt-api#206]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

NODE 18
CHROME 108
WINDOWS 10

### Describe the Bug

I want to save my login session so i don't have to login each time

**Comment by transitive-bullshit** [comment]
The intended usage is to have a persistent node.js process that is responding to external events and using one or more persistent browser(s) to respond, instead of creating a new browser + session for each request.

See my twitter bot for a real-world example, where it opens N browsers for N accounts and then polls for incoming tweets, cycling through the different accounts to respond in turn: https://github.com/transitive-bullshit/chatgpt-twitter-bot

**Comment by transitive-bullshit** [comment]
In a previous version, we were using a persistent puppeteer context, and you could tweak the code to allow that, but I would recommend against it since the Cloudflare protections make this approach much less viable.

**Comment by aaronteamAAR** [comment]
> The intended usage is to have a persistent node.js process that is responding to external events and using one or more persistent browser(s) to respond, instead of creating a new browser + session for each request.
> 
> 
> 
> See my twitter bot for a real-world example, where it opens N browsers for N accounts and then polls for incoming tweets, cycling through the different accounts to respond in turn: https://github.com/transitive-bullshit/chatgpt-twitter-bot

So in a short form, how did you achieve this?

**Comment by aaronteamAAR** [comment]
> In a previous version, we were using a persistent puppeteer context, and you could tweak the code to allow that, but I would recommend against it since the Cloudflare protections make this approach much less viable.

I wouldn't even want to do that as I have no issues with it for now, I just need to have something like a real time communication with the bot

**Comment by transitive-bullshit** [comment]
Create a HTTP server / node.js process that runs one or more OpenAI accounts in the background as browsers. When an HTTP event comes in that you want the bot to respond to, use `sendMessage`. Just make sure that you don't have multiple `sendMessage` requests open to a single browser instance at a time, as that will cause 429 errors.

For more help, check the Projects section of the readme; there are dozens of examples of other folks who are using similar approaches 😄

**Comment by aaronteamAAR** [comment]
> Create a HTTP server / node.js process that runs one or more OpenAI accounts in the background as browsers. When an HTTP event comes in that you want the bot to respond to, use `sendMessage`. Just make sure that you don't have multiple `sendMessage` requests open to a single browser instance at a time, as that will cause 429 errors.
> 
> 
> 
> For more help, check the Projects section of the readme; there are dozens of examples of other folks who are using similar approaches 😄

Just seeing this now, thanks so much.

**Comment by am-monkey** [comment]
> Create a HTTP server / node.js process that runs one or more OpenAI accounts in the background as browsers. When an HTTP event comes in that you want the bot to respond to, use `sendMessage`. Just make sure that you don't have multiple `sendMessage` requests open to a single browser instance at a time, as that will cause 429 errors.
> 
> For more help, check the Projects section of the readme; there are dozens of examples of other folks who are using similar approaches 😄

Can you please share some examples how to interact with running node.js process? How I can run browser once and interact with it?
