### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by realcoloride** [transitive-bullshit/chatgpt-api#207]
### Verify latest release

- [x] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node.js version: v18.12.1
Browser version: Chrome 108
OS: Windows
OS version: 11 21H2

### Describe the Bug

Hello, I keep having this error:

```
import { ChatGPTAPIBrowser } from 'chatgpt'
^^^^^^

SyntaxError: Cannot use import statement outside a module
```
I tried:
* Installing and reinstalling node
* Installing and reinstalling the module
* Adding `type:"module"` to the module in the package.json
* Asking a way to resolve this problem to ChatGPT

I'm confused

**Comment by loirotv** [comment]
@realcoloride how did you manage to fix it? I am facing the same issue.

**Comment by realcoloride** [comment]
Use commonJS importing instead
Import from is for typescript if I remember correctly
