### ISSUE TITLE
Clear conversations

### ISSUE THREAD

**Issue by petitbonney** [transitive-bullshit/chatgpt-api#209]
### Describe the feature

Hello, I saw that we can clear conversations on ChatGPT interface. I did not dive down in the repo code, maybe you will be able to add it. I extracted the curl request. It seems to be a PATCH on /conversations:

curl 'https://chat.openai.com/backend-api/conversations' \
  -X 'PATCH' \
  -H 'authority: chat.openai.com' \
  -H 'accept: */*' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8,fr;q=0.7,es;q=0.6' \
  -H 'authorization: Bearer ...' \
  -H 'content-type: application/json' \
  -H 'cookie: ...' \
  -H 'origin: https://chat.openai.com' \
  -H 'referer: https://chat.openai.com/chat' \
  -H 'sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' \
  --data-raw '{"is_visible":false}' \
  --compressed

**Comment by transitive-bullshit** [comment]
Thanks for the code snippet, @petitbonney 

As I understand it, there's really no need to clear conversations. Just don't pass in a `conversationId` and `parentMessageId` to `sendMessage` and it will by default create a new conversation.
