### ISSUE TITLE
multi threading 

### ISSUE THREAD

**Issue by mishav78** [transitive-bullshit/chatgpt-api#213]
### Describe the feature

is it multi threaded already?

**Comment by transitive-bullshit** [comment]
Node.js does not use multithreading. You can have multiple browser processes to process requests across N OpenAI accounts concurrently, but this is beyond the scope of this repo.

**Comment by mishav78** [comment]
is there any other project that handles captcha and the fact the request is from inside a browser like you do, perhaps in another language?
