### ISSUE TITLE
If the network speed is too slow, the login button will fail to click.

### ISSUE THREAD

**Issue by CSerht** [transitive-bullshit/chatgpt-api#216]
### Describe the feature

I'm in China, using a VPN to access OpenAI. So my Internet is slow.

The login button is clicked before the ChatGPT login page is loaded. As a result, the click fails. I have to click on it myself.

The following code seems to be relevant, but I don't know the language.
```
// click login button and wait for navigation to finish
await Promise.all([
  page.waitForNavigation({
    waitUntil: 'networkidle2',
    timeout: timeoutMs
  }),

  page.click('#__next .btn-primary')
])
```

Can you add some logic to make the login button click successfully when the Internet speed is slow?

Thank you!

**Comment by transitive-bullshit** [comment]
Ahh good call; we can definitely add a `waitForSelector` here to help mitigate this issue.

**Comment by CSerht** [comment]
Thank you very much. That's great news！

**Comment by transitive-bullshit** [comment]
Hopefully the changes by @fuergaosi233 will resolve this. Please upgrade to https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v3.3.9 and let us know.
