### ISSUE TITLE
How is this legal?

### ISSUE THREAD

**Issue by UCWV6N8pcAL6bjiWMZtZrKrQwT** [transitive-bullshit/chatgpt-api#217]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Add a note in README, explaining how this is legal\moral to abuse chatGPT service.

### Describe the Bug

Not even taking into account the morality of the fact that this repo advertises usage of CAPTCHA solver services and proxies to circumvent _several layers_ of bot protection systems put in place by chatGPT authors. 

I'd like to see a **clear explanation** from both the @transitive-bullshit  and @github why this (and other modules like it) are not being taken down for violating [OpenAI ToS](https://openai.com/terms/)?
![image](https://user-images.githubusercontent.com/80627726/210104916-284a34fe-1f8a-4a77-a012-ba1bf23525a9.png)

**Comment by transitive-bullshit** [comment]
I asked in OpenAI's discord explicitly about this module and our use case and it only received positive replies.

We are not "abusing" anything; this package just provides an easier way to access the standard web functionality, and as explicitly stated in the readme, the package's implementation will be replaced with the official API once it's released.

OpenAI employees have starred this repo and are definitely aware of what we're doing, and I've yet to receive a single complaint as all of my contact info is very publicly available.

**Comment by transitive-bullshit** [comment]
If you'd like more info, feel free to reach out to me personally from a non-anonymous account, and I'd be happy to discuss.
