### ISSUE TITLE
Does this work in browser js? 

### ISSUE THREAD

**Issue by dskill** [transitive-bullshit/chatgpt-api#22]
Forgive the noob question, but can I run this in browser js?  I tried putting it into a static webpage, but I got some errors.  Now I think I'm realizing this is only intended to run in node.js.

**Comment by dskill** [comment]
(obviously i'm just experimenting.  I wouldn't actually publish a static site that uses my own credentials.  OK I convinced myself this is a really dumb question. thx for the cool example!)

**Comment by transitive-bullshit** [comment]
Not yet, but it wouldn't take much effort to make this package work in both Node.js + browser.

This could be really important, for instance, for running on Edge runtimes like CF workers, Vercel edge functions, etc.

**Comment by transitive-bullshit** [comment]
See https://github.com/transitive-bullshit/chatgpt-api/issues/24

**Comment by dskill** [comment]
thx!
