### ISSUE TITLE
In React App throw - Uncaught TypeError: Assignment to constant variable. in puppeter-extra-plugin

### ISSUE THREAD

**Issue by gidimetis** [transitive-bullshit/chatgpt-api#221]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

React 18.2
Vite: 2.9.14

### Describe the Bug

![bug-report](https://user-images.githubusercontent.com/101128327/210166384-a4fa5f11-2c77-4e93-b78d-188e1bdefbed.png)

**Comment by rafazold** [comment]
I'm getting the same issue with Svelte, did you make something to solve this?

**Comment by Splinteer** [comment]
> I'm getting the same issue with Svelte, did you make something to solve this?

Same for me
