### ISSUE TITLE
Should we add cookie save when login success.

### ISSUE THREAD

**Issue by fuergaosi233** [transitive-bullshit/chatgpt-api#224]
### Describe the feature

At present, SDK behavior requires re-login every time it is started. Can we provide a Cookie interface to automatically back up and dump cookies every time?

**Comment by transitive-bullshit** [comment]
I agree that re-authenticating is a pain, but it's pretty difficult to get persistent sessions to work with the Cloudflare protections.

See my previous comments in this thread: https://github.com/transitive-bullshit/chatgpt-api/issues/206
