### ISSUE TITLE
Having to enter the recaptcha manually

### ISSUE THREAD

**Issue by jwgatt** [transitive-bullshit/chatgpt-api#227]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Running Linux Ubuntu 20
Google Chrome

### Describe the Bug

Puppeteer isn't solving the recapture but seems like it is 'missing', the recapture box which briefly shows a red outline. After being solved manually a second captcha appears with traffic lights etc. Seems like Puppeteer and its plugins arn't working as intended, is there anyway to get around this?

**Comment by transitive-bullshit** [comment]
Which captcha provider are you using? Can you verify that you've set up the captcha env variables correctly by pasting the full `stdout` from running the demo locally?

Double-check this section of the readme https://github.com/transitive-bullshit/chatgpt-api#captchas
