### ISSUE TITLE
can we use this script in our WordPress website and create website like chatgpt?

### ISSUE THREAD

**Issue by nk076** [transitive-bullshit/chatgpt-api#228]
### Describe the feature

can we use this script in our WordPress website and create website like chatgpt?
if yes do you have any video guide how to use this?

**Comment by christophebe** [comment]
I don't think there is already a wordpress extension for that. You need to check in the Wordpress plugin website or on github

**Comment by transitive-bullshit** [comment]
WordPress integration is outside the scope of this repo. It's definitely possible to build another project on top of this one that would do what you're asking, but I don't think one exists yet.
