### ISSUE TITLE
Session closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by evolution-ant** [transitive-bullshit/chatgpt-api#231]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

mac m1 
chrome:108.0.5359.124
chatgpt:3.3.10

### Describe the Bug

At first it is normal, after a while it will appear:
closeSession error Error: Protocol error (Network.deleteCookies): Session closed. Most likely the page has been closed.
Is puppeteer and chrome link timeout, is there a way to make him not timeout

**Comment by transitive-bullshit** [comment]
This can happen sometimes when we recognize that the request is going to error and we forcibly try and reset the browser session by closing the browser and re-authenticating.

It's not perfect, but it tends to work well enough for a lot of use cases.

Are you seeing the browser recover after this error or not?

**Comment by evolution-ant** [comment]
> This can happen sometimes when we recognize that the request is going to error and we forcibly try and reset the browser session by closing the browser and re-authenticating.
> 
> It's not perfect, but it tends to work well enough for a lot of use cases.
> 
> Are you seeing the browser recover after this error or not?

Already working properly
