### ISSUE TITLE
Access Denied: 1020 on Replit

### ISSUE THREAD

**Issue by cheesebellies** [transitive-bullshit/chatgpt-api#233]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node version: `Node.js 18.12.1`
Browser Version: `Chromium 108.0.5359.94`
OS Info: 
```shell
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
Additional info: run on (Replit)[https://replit.com] using the following code:
```javascript
import { ChatGPTAPIBrowser } from 'chatgpt'

const api = new ChatGPTAPIBrowser({
  email: process.env.OPENAI_EMAIL,
  password: process.env.OPENAI_PASSWORD
})
await api.initSession()

const result = await api.sendMessage('Hello World!')
console.log(result.response)
```

### Describe the Bug

Upon running `node index.js`, everything works fine until the browser opened.<br>
![Screenshot 2023-01-05 9 37 34 PM](https://user-images.githubusercontent.com/84882131/210918620-e801a3ac-dd43-4832-8f23-c44dde03f143.png)
<br>
![Screenshot 2023-01-05 9 38 34 PM](https://user-images.githubusercontent.com/84882131/210918685-df3171c1-8a1a-4c52-9dab-fe889fecd311.png)

<strong>Steps to reproduce:</strong><br><br>
Create an account with Replit, then navigate to the `create` button. Choose node.js as a template.
Create the index.js file using the code described in the `Environment Details` section of this report, then add `"type": "module"` to package.json.
Click the three dots in the file explorer to the left, and click `show hidden files`.
Navigate to `replit.nix`, and in `deps` add the following:
```
pkgs.chromedriver
pkgs.chromium
```
then run the following shell commands:
```shell
npm install puppeteer chatgpt
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
unset npm_config_prefix
nvm install v18.12.1
npm audit fix
export OPENAI_EMAIL="your_email_here"
export OPENAI_PASSWORD="your_password_here"
export PUPPETEER_EXECUTABLE_PATH=$(whereis chromium | awk '{print $2}')
node index.js
```

**Comment by cheesebellies** [comment]
Most likely it is different, but it could be close to me (in Massachusetts, US) since it says "atl07" as the server. "Atlantic 07"

**Comment by acheong08** [comment]
Some IP addresses are banned.

**Comment by acheong08** [comment]
> or wait until the official API is released.

On that note, OpenAI made an announcement today that they will begin monetizing ChatGPT soon. Could be a sign of an official API
