### ISSUE TITLE
Fails with long passwords

### ISSUE THREAD

**Issue by acheong08** [transitive-bullshit/chatgpt-api#234]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Not relevant

### Describe the Bug

When the password is too long, the login button is pressed before it has been fully entered

**Comment by acheong08** [comment]
Solution: Wait a few more milliseconds based on password length

**Comment by transitive-bullshit** [comment]
Thanks @acheong08 😄

This should resolve the issue I think https://github.com/transitive-bullshit/chatgpt-api/commit/b6649b948494d305b79dcbee5b54cb2eaa6b46c5 

Just released 🚀
