### ISSUE TITLE
Getting 403 on sendMessage

### ISSUE THREAD

**Issue by maksimlya** [transitive-bullshit/chatgpt-api#238]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

NodeJS 18.12.11
Window 11

### Describe the Bug

Hi I was trying out this project and it works really well using the browser auth api. However each time I restart server I had to do the recapcha stuff so I tried instead using the REST api (doing browser auth 1 time, then storing tokens locally etc). However the REST api does not seems to work. It refreshes the session fine but I get 403 forbidden exception on send message.

```
ChatGPTError: ChatGPTAPI error 403
    at fetchSSE (file:///E:/Discord%20Bot/node_modules/chatgpt/build/index.js:51:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 403,
  statusText: 'Forbidden',
```

Reading the existing issues I saw it might not work right now, is that the case?

**Comment by hendriklammers** [comment]
Same issue here.. However for me it also happens after successful authentication using `getOpenAIAuth` with Google login.

**Comment by transitive-bullshit** [comment]
We strongly recommend using the browser API. The REST-based version unfortunately suffers from issues due to Cloudflare's TLS fingerprinting.

The suggested usage is to login once, keep the browser around, and respond to requests while the auth is valid – instead of re-authenticating for every request.

**Comment by Dagmawi-Beyene** [comment]
> Same issue here.. However for me it also happens after successful authentication using `getOpenAIAuth` with Google login.

I had the same issue, but it worked after I changed chatGPTAPI to ChatGPTAPIBrowser
