### ISSUE TITLE
Add support for browser-like edge runtimes

### ISSUE THREAD

**Issue by transitive-bullshit** [transitive-bullshit/chatgpt-api#24]
It shouldn't take much effort to make this package work in both Node.js + browser environments.

This could be really important, for instance, for running on Edge runtimes like CF workers, Vercel edge functions, trusted code in Chrome extensions, etc.

> **Note**
> This package is not meant to be run client-side in a browser because it contains a reference to your private session token.

**Comment by bytemain** [comment]
https://github.com/syonfox/GPT-3-Encoder

consider to use this fork, it support browser environment

**Comment by transitive-bullshit** [comment]
@bytemain this looks awesome. will def look into it. thanks! 🙏

**Comment by transitive-bullshit** [comment]
@bytemain would you mind creating a PR?

**Comment by bytemain** [comment]
after some research, [syonfox/GPT-3-Encoder](https://github.com/syonfox/GPT-3-Encoder) is still cannot used in Edge Runtime, it also need some modification.
So I gave up.
