### ISSUE TITLE
Fs issue with Puppeteer

### ISSUE THREAD

**Issue by ifeoluwaayo** [transitive-bullshit/chatgpt-api#241]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node 16 Nextjs13 

### Describe the Bug

A fs not found error

**Comment by ifeoluwaayo** [comment]
I'm using nextjs 13 Turbo Pack

**Comment by ErikDombi** [comment]
readme states:
`You must use node >= 18 at the moment. I'm using v19.2.0 in my testing.`
Try updating to a newer version of node.

**Comment by transitive-bullshit** [comment]
@ifeoluwaayo you'll need to give more info on the specific error you're running into. Does the demo in this repo work for you?

If it does, then it's a problem with our project's config. Note that if your project's unable to find the correct chrome path, you can set the `PUPPETEER_EXECUTABLE_PATH` env var to override it.

Also, as @ErikDombi mentioned, we recommend using `node >= 18`.
