### ISSUE TITLE
Change Browser Location

### ISSUE THREAD

**Issue by Fedack** [transitive-bullshit/chatgpt-api#243]
### Describe the feature

Greetings,
Currently it seems like it can only use Chrome Browser. Considering ChatGPT is at capacity, I'd like to use another browser (Brave) and point to that for puppeteer.

Is it possible and if so how?

**Comment by transitive-bullshit** [comment]
If ChatGPT is at capacity, the browser you're using won't affect things.

Currently, we only support puppeteer which supports Chromium. You can set the `PUPPETEER_EXECUTABLE_PATH` env var to override the default chromium path.
