### ISSUE TITLE
422 on any message sending. API Change?

### ISSUE THREAD

**Issue by alramalho** [transitive-bullshit/chatgpt-api#244]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node: v18.10.0
Browser Version: Google Chrome Version 108.0.5359.98 (Official Build) (x86_64)
OS: MacOS
OS Version: macOS Big Sur Version 11.6.6

### Describe the Bug

Starting from today, all message requests are returning a `422` as status code.
I have not investigated deeply, but I believe this was an API architectural change on OpenAI side, that the tool has failed to accompany. Here follows a print showing the different request signatures from manually interacting with the ChatGPT UI and triggering a request from the `chatgpt-api` library.

<img width="415" alt="Untitled" src="https://user-images.githubusercontent.com/47791391/211312384-1d687567-38c7-4a75-8f1f-173a7fb03cca.png">

Error message:
```
ChatGPTError: ChatGPTAPI error 422
    at ChatGPTAPIBrowser.sendMessage (file:///Users/alramalho/workspace/hippo-prototype/chatgpt-api/node_modules/chatgpt/build/index.js:1524:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/alramalho/workspace/hippo-prototype/chatgpt-api/index.js:25:24 {
  statusCode: 422,
  statusText: ''
}
```

Code that triggered error:

```javascript
await api.sendMessage("say hi")
```

**Comment by transitive-bullshit** [comment]
Hey @alramalho, this may be due to a bug that we just fixed, though I haven't seen this 422 error before. Let me know if it still repros after updating to latest.

Are you able to run the included `demos/demo.ts`? If you can, then it may be something within your node.js project.
