### ISSUE TITLE
Cannot bypass authentication from containerized server

### ISSUE THREAD

**Issue by karam-khanna** [transitive-bullshit/chatgpt-api#245]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node:19, dockerized container, gcp

### Describe the Bug

I am running a dockerized server deployed to GCP. When the container is run locally, authentication works fine, but when it’s deployed to gcp, it always runs into the authentication failed error. I suspect there’s an additional page it’s being sent to due to the IP address coming from a data center.

**Comment by transitive-bullshit** [comment]
> I suspect there’s an additional page it’s being sent to due to the IP address coming from a data center.

Yes. Unfortunately, Cloudflare's protections rely on a dynamic "riskiness score" which is greatly affected by data center IPs.

The suggested workaround is to use a residential IP proxy.

**Comment by karam-khanna** [comment]
Got it, thanks. If anyone finds a scalable solution to the proxy issue please comment
