### ISSUE TITLE
[Error] ChatGPTError: SyntaxError: Unexpected non-whitespace character after JSON at position 4

### ISSUE THREAD

**Issue by czzonet** [transitive-bullshit/chatgpt-api#247]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

3.3.1

### Describe the Bug

ChatGPTError: SyntaxError: Unexpected non-whitespace character after JSON at position 4
    at ChatGPTAPIBrowser.sendMessage

## Edited:

 unexpected some date response.

![Snipaste_2023-01-10_15-27-36](https://user-images.githubusercontent.com/16220009/211488297-fe2002c2-0ba0-4389-9003-55fbe74a6eb8.png)

## Resolved:

add code to `node_modules\chatgpt\build\index.js` line 185 or wait for merge.

```ts
try {
  const checkJson = JSON.parse(data);
} catch (error) {
  console.log("warning: parse error.");

  return;
}
```

**Comment by lokwkin** [comment]
Same here. And i found that if the message is as simple as "hello" or "what is your name", it works perfectly. It starts to throw this error when the question is longer.

**Comment by fungyeung** [comment]
Same here. Chatgpt web UI has no problem displaying the response.

**Comment by fuergaosi233** [comment]
Same here 🤦.

**Comment by LesterDong** [comment]
I have the same problem, so I wonder if it is caused by the response time out?

**Comment by transitive-bullshit** [comment]
This is definitely something new; looking into it...

**Comment by youht88** [comment]
same here when the response is complex

**Comment by jordancoult** [comment]
Yep, I'm having this issue too.

**Comment by rajeshjill** [comment]
Same here and sometimes the response is **502**

**Comment by subhadippal66** [comment]
Same here. Anyone solved it yet ?

**Comment by subhadippal66** [comment]
![image](https://user-images.githubusercontent.com/62802794/211467910-e56501bf-77c5-4b6c-bc5a-c6fe062353f8.png)

**Comment by soGary** [comment]
Same here all the time

**Comment by anotherso1a** [comment]
Same error. And I found that in Chrome, questions are already be answered, but dosen't return in chatgpt-api

**Comment by czzonet** [comment]
I have been trying to run the demo to locate the problem...

**Comment by MrlolDev** [comment]
Same problem here any solution ?

**Comment by michaelybecker** [comment]
same and +1 to it being new (as in, wasn't a problem this morning)

**Comment by vtxyer** [comment]
+1

**Comment by transitive-bullshit** [comment]
Just released https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v3.3.12 with a potential fix from @czzonet 🔥

**Comment by SkyleLai** [comment]
I face same problem at v3.3.11, and get fixed at v3.3.12. thanks a lot

**Comment by MichaelVandi** [comment]
Thank you for the fix!!!

**Comment by MrlolDev** [comment]
It doesn't work for me

**Comment by michaelbecker-d** [comment]
@transitive-bullshit , haven't even checked yet (will edit comment when I do) - just wanted to say thank you for all your effort on this fantastic little project. You're so quick with fixes!

**Comment by transitive-bullshit** [comment]
> It doesn't work for me

I know you mentioned it on discord as well; can you provide more detail here? And does the built-in demo on latest `main` work for you locally?

**Comment by seckingyo** [comment]
same error today
