### ISSUE TITLE
I can't run the demos on visual studio code

### ISSUE THREAD

**Issue by pesoszpesosz** [transitive-bullshit/chatgpt-api#248]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

I am using Node.js v19.3.0, latest version of chrome, and windows 10 (Version 22H2 OS Build 19045.2364)

### Describe the Bug

<a href="https://ibb.co/4fMzHBs"><img src="https://i.ibb.co/YW8mxvD/error.png" alt="error" border="0"></a><br />

Hey, guys i keep getting this code when i try to put the command: npx tsx demos/demo.ts

I've installed "npm install chatgpt puppeteer"

I am using visual studio code.

I tried creating .env file in the main directory, but nothing happened, maybe i am not doing something right. I need to login with google authentication, so i can't just type my credentials in a file. The browser needs to open first somehow, before i can login. Please help me

**Comment by czzonet** [comment]
The demo use .env file to normal login instead of google. You can change the demo.ts.

**Comment by transitive-bullshit** [comment]
Make sure the environment variables used by the demo are declared. If you're using Google auth, you'll need to edit things slightly.

**Comment by pesoszpesosz** [comment]
Can you please show me how the code would look like with a google auth, I am kinda new to programming and I tried a lot of stuff to get it working already

**Comment by transitive-bullshit** [comment]
@PairZhu try adding `isGoogleLogin: true` to the params passed to the `ChatGPTAPIBrowser` constructor:

```tsx
const api = new ChatGPTAPIBrowser({
    email,
    password,
    isGoogleLogin: true,
    debug: false,
    minimize: true
  })
```

If that doesn't work for the built-in demo, let me know and provide as much info on what happens (and what's logged) as possible.
