### ISSUE TITLE
How to increase the time it takes for "isAtCapacity" to be determined?

### ISSUE THREAD

**Issue by InspectorPepinillo** [transitive-bullshit/chatgpt-api#250]
### Describe the feature

Hello, is there any (noob-friendly) way to increase the time the browser waits to confirm if Chat GPT is at capacity? I tried increasing the values in the attached image (inside openai-auth.ts), but I don't think that works. Maybe I'm missing something. I ask because Chat GPT is usually at capacity, but it works after reloading a few times... so maybe waiting 10 minutes or so instead of 2 would solve this issue (and thus avoiding the 503 error).
![capacity (1)](https://user-images.githubusercontent.com/122381097/211593811-a08a8eec-8b89-449e-ad4e-34b0e2357913.png)

**Comment by transitive-bullshit** [comment]
Definitely a good request.

Likely the default timeout from up above is overriding this default timeout value. Maybe they should be separate..

I generally handle this by having app-level logic which adds retries, but I agree it'd be nice to have that in this package itself.

**Comment by InspectorPepinillo** [comment]
Thank you!
