### ISSUE TITLE
login 

### ISSUE THREAD

**Issue by gpuer** [transitive-bullshit/chatgpt-api#252]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

chrome

### Describe the Bug

There is a click action but the verification window cannot be opened。
![WX20230111-113601](https://user-images.githubusercontent.com/36808568/211712824-4aa048c3-2ea3-48ce-83a9-5dd340c676bf.png)

**Comment by transitive-bullshit** [comment]
Can you give the full output of your console when running the demo, including how you're invoking the demo?

Also, are you sure you have a non-empty email and password defined?

What version of node.js?

**Comment by liu904-61** [comment]
This happened to me just now, I used the correct email and password, node.js version is v19.2.0
After the automatic click robot verification failed, I clicked manually and the process was normal

**Comment by liu904-61** [comment]
This happened to me just now, I used the correct email and password, node.js version is v19.2.0
After the automatic click robot verification failed, I clicked manually, and the follow-up process was normal

**Comment by transitive-bullshit** [comment]
@liu904-61 which captcha provider?

In general, beyond simple scenarios, I definitely recommend wrapping your ChatGPT usage in retry logic since there are any number of points where it can fail due to small reasons. We'll never be able to make it 100% robust without an official API.

**Comment by InspectorPepinillo** [comment]
This may be related with a problem I am experiencing right now: "ChatGPTError: Failed to authenticate session"
Everything works fine (including Captchas) until "Continue" button is clicked. It seems to be working but then once I get logged in, the scripts stops and I get this error. This happens when using a gmail account and also when signing in with nopecha captcha provider. Yesterday I wasn't experiencing this issue.

![session](https://user-images.githubusercontent.com/122381097/211780701-802cb8f9-e658-40e6-95cb-56733e5aed80.png)

**Comment by guation** [comment]
I have the same problem. After opening the login interface, it automatically enters my email address but displays this red box. I manually click the red box to complete human-machine verification before continuing to log in. However, after successful login, the browser exits and the console displays "Failed to authenticate session".

**Comment by gpuer** [comment]
node version is 18.12.1
![image](https://user-images.githubusercontent.com/36808568/212827824-568a4781-c7a7-4071-812e-d727bdd07a6a.png)
The above is a screenshot without pop-up verification, and the picture below is an error report after I click login after manual verification
![image](https://user-images.githubusercontent.com/36808568/212828496-0e964a52-17df-4530-a11e-69185e7d3690.png)

**Comment by samuelfaj** [comment]
Same here!

**Comment by maxiannunziata** [comment]
same

**Comment by or2008** [comment]
same

**Comment by transitive-bullshit** [comment]
Try upgrading to the latest version; we're now using the official API, which no longer uses puppeteer so problems like this should go away completely: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.0.0
