### ISSUE TITLE
429 error very frequently.

### ISSUE THREAD

**Issue by Abhineetnehra** [transitive-bullshit/chatgpt-api#253]
### Describe the feature

No error, just looking for ideas. The delay between each API call is 10 seconds, and I'm not sure why I get 429 error sometimes after 5 successful calls,  sometime after 17 calls, and sometime after 50 calls. There could be a reason why, when the server is most busy, it throws the 429 error early. Could someone please suggest a better approach to avoiding (error 429: too many requests) in a much better way so as to increase the number of successful API responses.

**Comment by InspectorPepinillo** [comment]
For me, I have found that using prompts that result in shorter text helps preventing 429 errors (i.e. "write a short paragrapht about..." instead of "write an essay about..."). So I prefer using many "shorter prompts" instead of just a big one. Of course this trick may not be useful for your usecase, buy anyway tha's my two cents.

**Comment by transitive-bullshit** [comment]
I see this as well and the best advice I have for now is to add a reasonable amount of retry logic around your usage of `chatgpt`. This obviously isn't ideal, but it may be the best we can do with the current restrictions OpenAI & Cloudflare have in place.

If anyone has any deeper insight as to why the 429s happen seemingly at random, please share your learnings. Hopefully we can make this package more robust as a community.

**Comment by xKliment** [comment]
> I see this as well and the best advice I have for now is to add a reasonable amount of retry logic around your usage of `chatgpt`. This obviously isn't ideal, but it may be the best we can do with the current restrictions OpenAI & Cloudflare have in place.
> 
> If anyone has any deeper insight as to why the 429s happen seemingly at random, please share your learnings. Hopefully we can make this package more robust as a community.

I am currently trieng to develop a WhatsApp Bot and i have noticed that if 2-3 users write at the same time i get the error. maybe a load balancer or a queue for the questions so this way you can avoid it?

**Comment by emipc** [comment]
I'm getting this error as well. Would setting a proxy server help for the different accounts help?

**Comment by samuelfaj** [comment]
I'll test now with 10 users and a load balancer.

Each user going to make 3 requests.
