### ISSUE TITLE
Logging nopechaKey even when NOT in debug mode

### ISSUE THREAD

**Issue by aldilaff** [transitive-bullshit/chatgpt-api#254]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node v18.13.0

### Describe the Bug

The framework is always logging/printing the nopecha key even when it when the ChatGPTAPIBrowser is created with debug mode set to false.

Here's how I am initializing ChatGPTAPIBrowser:

```
const api = new ChatGPTAPIBrowser({
  email,
  password,
  debug: false,
  minimize: true,
});
```

When I look at the output of my code I always see this: `initializing nopecha extension with key ********`. Is there a reason we are always printing the secret key out?

See [here](https://github.com/transitive-bullshit/chatgpt-api/blob/d4067ca455b0495da6c8a5d967b822bf5d1cdb62/src/openai-auth.ts#L414) for the line that is doing this.

**Comment by transitive-bullshit** [comment]
Fixed this recently. Thanks :)
