### ISSUE TITLE
getting 401 with `new ChatGPTAPIBrowser({ ...openAIAuth })`

### ISSUE THREAD

**Issue by KeyToLove** [transitive-bullshit/chatgpt-api#258]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

![image](https://user-images.githubusercontent.com/54970106/212459418-8136612b-779b-4a7d-af7a-0bcfb61d6a22.png)

### Describe the Bug

```js
// index.js
import { ChatGPTAPIBrowser, getOpenAIAuth } from 'chatgpt'
import * as dotenv from 'dotenv'
dotenv.config()

const demo = async () => {
  const openAIAuth = await getOpenAIAuth({
    email: process.env.OPENAI_EMAIL,
    password: process.env.OPENAI_PASSWORD,
  })

  const api = new ChatGPTAPIBrowser({ ...openAIAuth })
  await api.initSession()
}
demo()
```
i just run this demo by Node
```cmd
node index.js
```
after then, I've actually logged in to the automatically open chrome
![image](https://user-images.githubusercontent.com/54970106/212459318-f137a53f-f532-4022-98ab-390733a3e978.png)

but the terminal threw the following error
![image](https://user-images.githubusercontent.com/54970106/212460035-0ecc3e9c-da9e-449e-8d5a-a13488c252bd.png)
Did I use something wrong?

**Comment by transitive-bullshit** [comment]
It looks like `process.env.OPENAI_EMAIL` is not defined or empty. Make sure you're setting the correct environment variables. Maybe try console.log'ing the email and password before creating the `ChatGPTAPIBrowser`. This package will then log in automatically for you. You don't need to do the log in yourself.

**Comment by KeyToLove** [comment]
>  try console.log'ing the email and password before creating the `ChatGPTAPIBrowser`

hey, I just tried it, I'm sure these information is correct. In fact, this package open my chrome input my email automatically and  stuck here.

![image](https://user-images.githubusercontent.com/54970106/212522400-8c3044ad-c555-4d9b-8ed3-dfafed99b482.png)

After i pass Man-machine verification by myself, the package did the rest for me. Finally, the `chatgpt` page show me logged in successfully and the browser  is closed. This is the complete procedure for reporting the 401 error 😫.

**Comment by cyber0life** [comment]
Any solutions?

**Comment by transitive-bullshit** [comment]
Try upgrading to the latest version; we're now using the official API (no puppeteer!) so this should no longer be an issue: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.0.0
