### ISSUE TITLE
How do I solve recatchpa? 

### ISSUE THREAD

**Issue by aaronteamAAR** [transitive-bullshit/chatgpt-api#260]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node version = 18
Chrome = 108
Os = windows
osversion = 10

### Describe the Bug

I’d love to know how to solve the recatchpa that comes when your asked to put an email, I tried with the token but it didn’t seem to work, maybe I used it wrongly.

**Comment by transitive-bullshit** [comment]
Make sure to double-check this section of the readme: https://github.com/transitive-bullshit/chatgpt-api#captchas

Which captcha provider are you trying to use? What happens exactly when you use it, and what get logged to the console?

**Comment by aaronteamAAR** [comment]
> Make sure to double-check this section of the readme: https://github.com/transitive-bullshit/chatgpt-api#captchas
> 
> 
> 
> Which captcha provider are you trying to use? What happens exactly when you use it, and what get logged to the console?

I used 2captcha

I used ChatGPTAPIBrowser and I set the token for the captcha, it gets to the part where your asked to put your email but it doesn't solve the recaptcha

**Comment by transitive-bullshit** [comment]
Try using nopecha instead; it's definitely a lot more reliable in my experience – and faster as well.
