### ISSUE TITLE
Multiple messages 

### ISSUE THREAD

**Issue by suhail-ak-2** [transitive-bullshit/chatgpt-api#261]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node js 19
Chrome latest
Macos latest

### Describe the Bug

When trying to do multiple messages at the same time it is getting broken with error 422.

Is there any way to do multiple messages at the same time?

**Comment by transitive-bullshit** [comment]
You can only have a single `sendMessage` request per account and browser instance at a time. If you try to have concurrent requests, you will quickly run into errors.

The workaround is to use a pool of accounts and cycle between them, but that is beyond the scope of this repo.

**Comment by suhail-ak-2** [comment]
If maintain a queue system. Is it possible to maintain the context for each users

**Comment by transitive-bullshit** [comment]
Try upgrading to the latest version; we're now using the official API (no puppeteer!) so this should no longer be an issue: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.0.0
