### ISSUE TITLE
Myabe save the chrome data for avoid multiple login?

### ISSUE THREAD

**Issue by Himly1** [transitive-bullshit/chatgpt-api#262]
### Describe the feature

When restart  my app the browser will require login again. We can use the "userDataDir" property on the `puppeteer.launch` to avoid this.
Which mean once you loged in will not require login anymore until the login expired.

Here is the option for the puppeteer browser to do that:
```bs = await puppeteer.launch({ ignoreHTTPSErrors: true, headless: headless, executablePath: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe", userDataDir: './userData', args, })```

You need to set the `userDataDir` on the puppeteer.launch function.

**Comment by Himly1** [comment]
Also, We can catch the post question and then set the responseType to "stream" and get the response one word by one word.
Because In some case waiting the response to completed is too long,  in some case we can pass an called to the sendMessage() function, when a sentence responsed you can pass the sentence to the callback.

**Comment by Himly1** [comment]
When you set the option "userDir" to the puppeteer.launch and then test this effect, be sure when you login succssed do not kill your app but first close the browser and then kill the app. Because when you kill the app the cookie will not save the to 'userDir' which mean the browser is not closed well, its crashed which mean its unable to save the chrome data.

**Comment by Himly1** [comment]
I forked this repo but when I try to make a change to the code well its a mess to test the changes, because its all of oop stuff and the OOP things just like a mightmare to me.

**Comment by guation** [comment]
I think we can also add Google Quick Login.

**Comment by transitive-bullshit** [comment]
> Also, We can catch the post request and then set the responseType to "stream" and get the response one word by one word. Because In some case waiting the response to completed is too long, in some case we can pass a callback to the sendMessage() function, when a sentence responsed you can pass the sentence to the callback.

This is already supported by the `onProgress` optional param of `sendMessage`.

**Comment by transitive-bullshit** [comment]
`userDir` was supported in a previous version of this package, but it was removed due to the difficulties around Cloudflare.

The recommend usage is to not re-login every time, but rather keep a persistent server open.

That being said, it wouldn't be hard to re-add support for a persistent `userDir`, with it defaulting to a [random tmp dir](https://classic.yarnpkg.com/en/package/tempy) that uses the account email as a seed (so different accounts are guaranteed to have different tmp dirs).

**Comment by transitive-bullshit** [comment]
This is now supported thanks to https://github.com/transitive-bullshit/chatgpt-api/pull/271 by @kodjunkie
