### ISSUE TITLE
get 403 when using ChatGPTAPI 

### ISSUE THREAD

**Issue by LesterDong** [transitive-bullshit/chatgpt-api#263]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node v18.13.0 
chrome v109.0.5414
Mac OS 12.3

### Describe the Bug

this is my test code:
<img width="751" alt="image" src="https://user-images.githubusercontent.com/25879996/212544817-4d7b1df1-31c7-40a7-ae6f-3817e1d58f99.png">

----------------------------------------------
I'm sure the sessionToken and clearanceToken is valid, but got 403 
<img width="816" alt="image" src="https://user-images.githubusercontent.com/25879996/212544775-f0f61f56-d323-4fa5-b9c2-393e9095c4a0.png">

**Comment by nailuoGG** [comment]
`ChatGPTAPIBrowser`  work fine

**Comment by LesterDong** [comment]
> `ChatGPTAPIBrowser` work fine

I know, but i want run in a lightweight way after loging in by ChatGPTAPIBrowser

**Comment by transitive-bullshit** [comment]
Try upgrading to the latest version; we're now using the official API (no puppeteer!) so this should no longer be an issue: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.0.0
