### ISSUE TITLE
How to change conversation title

### ISSUE THREAD

**Issue by liuliangsir** [transitive-bullshit/chatgpt-api#264]
### Describe the feature

As the title above says, I have no idea about how to change conversation title after creating a conversation with using [chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api). I find that chatgpt official website use a end point to change conversation title in the case. If you do not change conversation titles after creating a massive conversations, you will find a lot of conversations named New chat on left side of chatgpt official website. In addition, It tends to a uncomfortable user experience.

**Comment by transitive-bullshit** [comment]
This project is aimed at programmatic usage of the core ChatGPT functionality only.

All of the UX-related features of the webapp are out of scope for this package, as they will very likely not be part of the official API once it's released.
