### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by Bogdan-O** [transitive-bullshit/chatgpt-api#265]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node v18.13.0
chrome v108.0.5359.124-1 
Debian 10

### Describe the Bug

this is my test code:
```
const api = new ChatGPTAPIBrowser({
    email: process.env.OPENAI_EMAIL,
    password: process.env.OPENAI_PASSWORD,
    isGoogleLogin: true
  })
await api.initSession()
  
const result = await api.sendMessage('Hi, I have a question HR related')
console.log('api result: ',result.response) 
```
 
After a few minutes I get the timeout following timeout error:
![image](https://user-images.githubusercontent.com/57963945/212692556-8539b81c-fe7e-4d2f-b2dd-087d0ad51bce.png)

**Comment by transitive-bullshit** [comment]
Try upgrading to the latest version; we're now using the official API (no puppeteer!) so this should no longer be an issue: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.0.0
