### ISSUE TITLE
calling refreshSession slow

### ISSUE THREAD

**Issue by LesterDong** [transitive-bullshit/chatgpt-api#266]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node v18
mac v12.3

### Describe the Bug

Anyone know why calling refreshSession so slow?  Seems to be caused by "await this._page.waitForResponse " , but i want to know what it did...

**Comment by transitive-bullshit** [comment]
Try upgrading to the latest version; we're now using the official API (no puppeteer!) so this should no longer be an issue: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.0.0
