### ISSUE TITLE
You requested a model that is not compatible with this engine

### ISSUE THREAD

**Issue by UCAudio** [transitive-bullshit/chatgpt-api#269]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node.js 18.13, Newest Chrome

### Describe the Bug

When making a call with api.sendMessage, the following is returned:

  message: 'You requested a model that is not compatible with this engine. Please contact us through our help center at help.openai.com for further questions.',
  type: 'invalid_request_error',
  param: 'model',

Is it possible there was just a recent change to the model name?

**Comment by transitive-bullshit** [comment]
Interesting; Are you able to repro this running the included demo?

I'm seeing the API still working consistently on my end so far.

**Comment by UCAudio** [comment]
It's working for me again as well. I saw some other people hit the same issue as me, but I think it was an intermittent issue related to high server demand and unrelated to this package. Very strange error message though.

**Comment by mabry1985** [comment]
I just hit this as well

**Comment by transitive-bullshit** [comment]
@mabry1985 if you can, would love to see more info around reproducing this and/or debug logs. thanks

**Comment by mabry1985** [comment]
@transitive-bullshit I'll keep an eye out for it again tonight and see if I can get any more info. I tried to refresh it once before going to bed and it happened again.

It's a 400 error if I remember correctly, I would have shared that info, but I thought they shared the code above. Other than that I had the same debug log. It's just a message and error code
