### ISSUE TITLE
add support for API token without using email & password login.

### ISSUE THREAD

**Issue by laminesadiki** [transitive-bullshit/chatgpt-api#270]
### Describe the feature

I think that OpenAI provides a pyhton API for their chatGPT.

I think that building an API with python and provide a Node.js REST api listenning in python services is enough to get answers directly using API.

if there is a limit or issue with this method, tell me.

Thanks.

**Comment by Alexandre-Georges** [comment]
Open AI does not provide an API for Chat GPT, I am pretty sure that's why this repository exists.
You are probably thinking of GPT 3 (which is used by Chat GPT), there is an API for some models based on it.
https://beta.openai.com/playground/p/default-chat

FAQ for Chat GPT:
```
How can I implement this? Is there any implementation guide for this?

ChatGPT is being made available as a research preview so we can learn about its strengths and weaknesses. It is not available in the API.
```

**Comment by dmatora** [comment]
There is https://github.com/acheong08/ChatGPT which supports authentication using session_token (you can get one from https://chat.openai.com/api/auth/session)
it's necessary to use with accounts that don't have passwords (if you signed up with google, you can only use google to authenticate)

**Comment by transitive-bullshit** [comment]
As others have said, there is no official ChatGPT API, so OpenAI API tokens don't work with ChatGPT for the time being.

This project will be updated to use the official API as soon as it's available.

**Comment by dmatora** [comment]
I wasn't talking about OpenAI API token, I was talking about chatGPT session token
Anyway, after having closer look to readme, I figured both google authentication and session tokens are really supported, it's just not mentioned in all relevant doc sections
