### ISSUE TITLE
Return error code (e.g. "message_length_exceeds_limit") from sendMessage

### ISSUE THREAD

**Issue by emipc** [transitive-bullshit/chatgpt-api#272]
### Describe the feature

I'd like to get the error code that ChatGPT responds with when the message you submitted is too long. Unfortunately, this in only logged in the console but it's not as part of the error being thrown from `sendMessage`, so we can't use it.

I think that'd be very useful in order to have a proper error handling in our end.

This is the error that is being logged in the console:

```
ChatGPT "myaccount@gmail.com" error 413; {
  message: 'The message you submitted was too long, please reload the conversation and submit something shorter.',
  code: 'message_length_exceeds_limit'
}
```

**Comment by transitive-bullshit** [comment]
Hey @emipc, thanks for opening an issue 😄

Looks like we just need to include this extra detail info in the error being thrown, right?

Also, I would recommend capping the input length on your end before even calling `sendMessage` to prevent abuse.

**Comment by adminha** [comment]
I think message length limit is 4097.
--------------------------
https://chatgpttalk.com/

**Comment by MichaelVandi** [comment]
@adminha is that characters or bytes?

**Comment by emipc** [comment]
> Hey @emipc, thanks for opening an issue 😄
> 
> Looks like we just need to include this extra detail info in the error being thrown, right?
> 
> Also, I would recommend capping the input length on your end before even calling `sendMessage` to prevent abuse.

Hey! I guess that's all we need to do, yep.

I'm already handling it before sending the request, but I think it depends on the language you are using and checking the length from a message might not work as expected because of the tokens: https://beta.openai.com/tokenizer

If I understood it correctly, it'd be better to encode the string and count the tokens,

Anyway, I found it a bit confusing to have the error code on the console but not being able to use it, so I think if we are able to work with them, it'd allow us to better handle different error cases.

**Comment by MichaelVandi** [comment]
@emipc @transitive-bullshit @adminha is the 4097 limit based on tokens, characters or bytes?

**Comment by transitive-bullshit** [comment]
This should no longer be relevant to the v4 `ChatGPTAPI` or `ChatGPTUnofficialProxyAPI`.

There will always be context limits (4096 tokens), which we try to enforce. If you're running into these limits, add `debug: true` to your constructor to try and debug what's going on under the hood.
