### ISSUE TITLE
Handle premium chatgpt accounts

### ISSUE THREAD

**Issue by transitive-bullshit** [transitive-bullshit/chatgpt-api#275]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

any premium chatgpt account

### Describe the Bug

Looks like we'll need to use the `text-davinci-002-render-paid` model as noted by @waylaidwanderer 

Maybe this is just an overridable option in the constructor?

**Comment by transitive-bullshit** [comment]
Fixed in https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v3.5.1

**Comment by z0lo13** [comment]
@transitive-bullshit could it still be used in a new version?
