### ISSUE TITLE
TimeoutError: Waiting for selector `#__next .btn-primary` failed: Waiting failed: 180000ms exceeded

### ISSUE THREAD

**Issue by logistic-people-deutschland** [transitive-bullshit/chatgpt-api#277]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

v18.13.0 node
Debian GNU/Linux 10 (buster)

### Describe the Bug

npx tsx demo-google-auth.ts
 
TimeoutError: Waiting for selector `#__next .btn-primary` failed: Waiting failed: 180000ms exceeded
    at Timeout.<anonymous> (/var/www/hr.logistic-people.de/htdocs/APIs/chatgpt-api-js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:64:32)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

**Comment by ChopChoP534** [comment]
Im having this same issue. It works locally but doesnt when running on docker. 
I don't know if this can be a issue but I set headless to true

**Comment by logistic-people-deutschland** [comment]
I also set headless to true but it doesn't work

**Comment by transitive-bullshit** [comment]
Try upgrading to the latest version; we're now using the official API, which no longer uses puppeteer so problems like this should go away completely: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.0.0
