### ISSUE TITLE
select an account error

### ISSUE THREAD

**Issue by BENSAFOUAN-Abdelhalim** [transitive-bullshit/chatgpt-api#278]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node.js v19.3.0
OS : Windows
Browser version : 109.0.5414.119

### Describe the Bug

Recently, when i use API with google auth, i get this after adding Email and password : 

![issue-55](https://user-images.githubusercontent.com/74852971/215115086-30614248-c1dd-46ea-aba0-723860455c34.PNG)

the api is not working properly even with the latest version, I only get responses for a few requests, after 4 or 5 requests it crashes.
what is the main reason for this, should i change the authentication method ?

**Comment by transitive-bullshit** [comment]
Try upgrading to the latest version; we're now using the official API, which no longer uses puppeteer so problems like this should go away completely: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.0.0
