### ISSUE TITLE
Is there a way to configure the model and corresponding parameters?

### ISSUE THREAD

**Issue by Tarhyru** [transitive-bullshit/chatgpt-api#28]
i found official example there are some models and parameter choices，this look like fixed. Are you interested in configuring it?

**Comment by transitive-bullshit** [comment]
I'm not so sure that ChatGPT allows for different models at the moment. All of the official examples are using OpenAI's API, which is meant to be configurable.

Do you have a link to an example where someone is customizing the model + parameters that is using ChatGPT?
