### ISSUE TITLE
Error: No element found for selector: button[type="submit"]

### ISSUE THREAD

**Issue by LiamRM** [transitive-bullshit/chatgpt-api#280]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node.js v18.12.1
Windows 11
Chrome v109.0.5414.120

### Describe the Bug

Error when logging in using email and password (not Google or Microsoft auth). 

There used to be a CAPTCHA box I'd check manually right after the email is entered, but as of today I'm not seeing a CAPTCHA box, and am running into this weird login error:

![image](https://user-images.githubusercontent.com/57396578/215309676-ff9d3cbb-87b9-42e3-8e2e-1896e781789e.png)

**Comment by transitive-bullshit** [comment]
Try upgrading to the latest version; we're now using the official API, which no longer uses puppeteer so problems like this should go away completely: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.0.0
