### ISSUE TITLE
Connecting to ChatGPT without Chrome/Pupeteer

### ISSUE THREAD

**Issue by timkmecl** [transitive-bullshit/chatgpt-api#282]
Hi, someone [discovered](https://twitter.com/GodlyIgnorance/status/1620270384150093825) that it was possible to connect to ChatGPT using the official OpenAI API just by passing the correct model name. You only need the official OpenAI API key, and there is no need to either have a Chrome open or obtain session/clearance tokens from the browser. I implemented this in a simple **[npm module](https://github.com/timkmecl/chatgpt-api-wrapper)** that you can check out. 

This may be an improvement over the current method, it is however more low-level (it doesn't support conversations/follow up questions out of the box, however it is simple to implement this as can be seen in the linked repo). The only downside is that the conversations/conversation ids are not synced with the web version or over multiple sessions - you always have to pass the entire conversation history.

**Comment by transitive-bullshit** [comment]
Just seeing this now.

Check out the latest version: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.0.0 😄

Yeah; we need to track messages on our side now, but I've added an example of how to do this using `keyv` with redis. Should be really easy to add support for any databse.

Definitely looking for help w/ this new version btw; let me know if you're interested in joining forces :)

**Comment by timkmecl** [comment]
Excelent timing 😂

I'm glad you implemented this,  I managed to get my VSCode extension working again with the latest version. I just hope that OpenAI doesn't remove/fix this soon...

 If there is something I can do to assist, I'd be happy to help, however I do not have that much experience with this kind of stuff

**Comment by transitive-bullshit** [comment]
>  I just hope that OpenAI doesn't remove/fix this soon...

I have heard from a credible source that this model is a "stealth release" from OpenAI for testing with partners, so I think it's unlikely that we'll have to revert.

Feel free to join our [discord](https://discord.gg/v9gERj825w) if you're interested in contributing or hacking on stuff here.
