### ISSUE TITLE
I started to get 429 errors. Looks like they have fingerprinted my IP etc

### ISSUE THREAD

**Issue by allthingssecurity** [transitive-bullshit/chatgpt-api#283]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node version 18.13
Browser chrome
Windows 10

### Describe the Bug

Since yesterday, I have experienced 429 errors and i am unable to use this awesome tool. Can you help

**Comment by thomasunify** [comment]
Same for me, but don't think is IP related as I have tried from different locations and IPs.

**Comment by allthingssecurity** [comment]
They have fingerprinted a number of things I think like email to login along with some other aspects

**Comment by transitive-bullshit** [comment]
Try upgrading to the latest version; we're now using the official API, and you should no longer have any issues related to IP addresses or rate limiting: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.0.0

**Comment by allthingssecurity** [comment]
you are super
