### ISSUE TITLE
I get : ChatGPTError: ChatGPT invalid session token ( I am using a valid key from OpenAI with a free trial 18$ )

### ISSUE THREAD

**Issue by BENSAFOUAN-Abdelhalim** [transitive-bullshit/chatgpt-api#285]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node.js v19.3.0
OS : Windows 
Latest version of the package

### Describe the Bug
I get this error after using the latest version of the package : 

![image](https://user-images.githubusercontent.com/74852971/216087534-eb771806-e8df-425b-ac10-79243db2a2b2.png)

**Comment by transitive-bullshit** [comment]
@BENSAFOUAN-Abdelhalim this error doesn't exist in the latest version of the package. It only existed in v3 of the package.

Double check to make sure you're using v4.

**Comment by BENSAFOUAN-Abdelhalim** [comment]
thanks for your answer, but before i get this error, i already updated the package, i tested the latest version 4.04 but unfortunately i get the same 401 error.

![image](https://user-images.githubusercontent.com/74852971/216268388-df4331d3-d91e-467c-93ba-3d1cf3b6a377.png)

**Comment by transitive-bullshit** [comment]
@BENSAFOUAN-Abdelhalim this error will only happen if the `apiKey` parameter you're passing to the constructor is empty.

Try logging it before `new ChatGPTAPI` just to make sure it's not an empty value.

**Comment by BENSAFOUAN-Abdelhalim** [comment]
Thanks @transitive-bullshit , it worked now.
