### ISSUE TITLE
about remove ChatGPTAPIBrowser

### ISSUE THREAD

**Issue by bincooo** [transitive-bullshit/chatgpt-api#286]
### Describe the feature

It is not recommended to remove ChatGPTAPIBrowser, as it allows unlimited tokens

**Comment by transitive-bullshit** [comment]
`ChatGPTAPIBrowser` did not support unlimited tokens. It may have supported more input tokens, but definitely not unlimited.

Can you share more about your use case?

**Comment by transitive-bullshit** [comment]
Note that you can still use `ChatGPTAPIBrowser`. Just stay on **v3**.
