### ISSUE TITLE
res.conversationId is undefined after first conversation

### ISSUE THREAD

**Issue by Glowin** [transitive-bullshit/chatgpt-api#287]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

$ node --version
v18.12.1

### Describe the Bug

I run the demo about tract conversation:

``` javascript
const api = new ChatGPTAPI({ apiKey: process.env.OPENAI_API_KEY })

// send a message and wait for the response
let res = await api.sendMessage('What is OpenAI?')
console.log(res.text)

// send a follow-up
res = await api.sendMessage('Can you expand on that?', {
  conversationId: res.conversationId,
  parentMessageId: res.id
})
console.log(res.text)

// send another follow-up
// send a follow-up
res = await api.sendMessage('What were we talking about?', {
  conversationId: res.conversationId,
  parentMessageId: res.id
})
console.log(res.text)
```

I got res like below, res.conversationId is undefined, but this value will pass to second conversationId. I think there is problem about `id`, `conversationId` and `parentMessageId`.

``` json
{
    role: "assistant",
    id: "cmpl-6fA4ItiyX1SzmDFOBKWTfHdpTfWoS",
    parentMessageId: "cdbca365-b97c-4592-ae25-ac278454a94f",
    conversationId: undefined,
    text: "OpenAI is an artificial intelligence research laboratory consisting of the for-profit technological company, OpenAI LP, and its parent company, the non-profit OpenAI Inc.",
}
```

**Comment by Dorian25** [comment]
Same here ✋ 

![image](https://user-images.githubusercontent.com/32178615/216107807-e7fe5862-87f1-4a21-8283-b5d6194e0363.png)

**Comment by transitive-bullshit** [comment]
`conversationId` is currently unused, so it should be fine.

This is a bug, though, since we want to mimic the expected official API as closely as possible.

**Comment by Glowin** [comment]
> `conversationId` is currently unused, so it should be fine.
> 
> This is a bug, though, since we want to mimic the expected official API as closely as possible.

How can I pass conversationId and parentMessageId to next conversation? like:

```
res = await api.sendMessage('Can you expand on that?', {
  conversationId: res.conversationId,
  parentMessageId: res.id
})
```
or 
```
res = await api.sendMessage('Can you expand on that?', {
  conversationId: res.id,
  parentMessageId: res. parentMessageId
})
```

**Comment by transitive-bullshit** [comment]
This should now be fixed in https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.0.2

**Comment by transitive-bullshit** [comment]
@Glowin w/ the fix, just follow the examples & `demos/demo-conversation.ts`. Honestly, you can pass anything as `conversationid` since it's really not used for anything.

**Comment by halower** [comment]
does this mean that when parentMessageId is null, it is a new conversation @transitive-bullshit

**Comment by transitive-bullshit** [comment]
@halower yes; for `ChatGPTAPI`, if a message doesn't have a `parentMessageId`, then it is the start of a new conversation.
