### ISSUE TITLE
v4 proxy support?

### ISSUE THREAD

**Issue by davidpellerin** [transitive-bullshit/chatgpt-api#288]
Just wondering with the release of V4 if proxy support still exists?

I believe under the hood calls to openai are made using fetch?

**Comment by transitive-bullshit** [comment]
Great question; right now, I removed it, but it shouldn't be too hard to re-add.

Maybe we allow the option to specify a custom `fetch` method, which would allow you to use a custom `agent` that uses a proxy? Here's an example of that in the wild https://www.scrapingbee.com/blog/proxy-node-fetch/

**Comment by transitive-bullshit** [comment]
Note that in general, the need for proxies should decrease a lot with v4 since you can now deploy it to any cloud infrastructure without worrying about cloud IP bans, but I'm sure it'll still be really useful for local testing in banned countries.

**Comment by alexandregiordanelli** [comment]
I think it's important to return the proxy. I can't ask more than 20 questions in 1 minute using the same apiKey, and maybe with the proxy with the residential IP rotating it will work.

**Comment by transitive-bullshit** [comment]
OpenAI has rate limits, and you can not use proxies to get around them: https://platform.openai.com/docs/guides/rate-limits/overview

You can add money to your account and wait 48 hours to increase the default rate limits by quite a bit.

Also @davidpellerin I added support for custom `fetch` awhile ago, so this should be possible now.
