### ISSUE TITLE
Returned language is always English

### ISSUE THREAD

**Issue by xiaoyongzhu** [transitive-bullshit/chatgpt-api#289]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

I'm running the code in main branch (with the latest leaked APIs) with node v18.12.1

### Describe the Bug

This is really nice work! Thanks for writing this API!

I'm running the code in main branch (with the latest leaked APIs) with this prompt like below. Since the prompt is in Chinese, the result returned from ChatGPT (from website) is also Chinse, which works great. However the result returned by the repo/leaked API is still English. Guess maybe there's a config somewhere that can be set?

```
import dotenv from 'dotenv-safe'
import { oraPromise } from 'ora'

import { ChatGPTAPI } from '../src'

dotenv.config()

/**
 * Demo CLI for testing basic functionality.
 *
 * ```
 * npx tsx demos/demo.ts
 * ```
 */
async function main() {
  const api = new ChatGPTAPI({ apiKey: process.env.OPENAI_API_KEY })

  const prompt =
    '写一篇500字的文章推荐SKII神仙水'

  const res = await oraPromise(api.sendMessage(prompt), {
    text: prompt
  })
  console.log(res)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})

```

<img width="561" alt="image" src="https://user-images.githubusercontent.com/1185090/216235664-48757559-1e79-4555-89b5-c9fbe6856ccd.png">

**Comment by transitive-bullshit** [comment]
@xiaoyongzhu did you find a solution to this? I just want to make sure that other folks are also aware how to solve it.

**Comment by xiaoyongzhu** [comment]
@transitive-bullshit thanks for the follow up! Actually I think it might be some OpenAI issues, because in the website I actually use different phrase like below:

`写一篇200字的文章推荐SKII神仙水+大红瓶面霜组合，并且加入很多的emoji`

And the output is Chinese (for the website and for this repo).

However if I change it to something like this:

`写一篇500字的文章推荐SKII神仙水`

Then the output is English, for both the website and the repo.

(sorry I didn't verify this before filing the issue - the prompt I gave to the website and this API is actually different.)


So the take away there is to explicitly specify the return language in the prompt, for example like this:

`写一篇500字的文章推荐SKII神仙水, return the result in Chinese`

**Comment by transitive-bullshit** [comment]
Thanks @xiaoyongzhu 🙏

**Comment by ws02589111** [comment]
> @transitive-bullshit thanks for the follow up! Actually I think it might be some OpenAI issues, because in the website I actually use different phrase like below:
> 
> `写一篇200字的文章推荐SKII神仙水+大红瓶面霜组合，并且加入很多的emoji`
> 
> And the output is Chinese (for the website and for this repo).
> 
> However if I change it to something like this:
> 
> `写一篇500字的文章推荐SKII神仙水`
> 
> Then the output is English, for both the website and the repo.
> 
> (sorry I didn't verify this before filing the issue - the prompt I gave to the website and this API is actually different.)
> 
> So the take away there is to explicitly specify the return language in the prompt, for example like this:
> 
> `写一篇500字的文章推荐SKII神仙水, return the result in Chinese`

https://github.com/transitive-bullshit/chatgpt-api/blob/835959f6b76382fbd6a545f1addd609b8bf06a33/src/chatgpt-api.ts#L305

I don't know if my understanding is correct， you can try update the `promptPrefix` to set your AI character setting， maybe you can add text like “you must response me chinese”
