### ISSUE TITLE
Add better support for conversations

### ISSUE THREAD

**Issue by transitive-bullshit** [transitive-bullshit/chatgpt-api#29]
- Expose message IDs to the user
- Store the latest message ID as the default `conversationId`
- Automatically update the default conversation ID if no `conversationId` is passed

See #26 which I need to review

**Comment by solserer-labs** [comment]
From what I've been seeing the network logs is that if you want to have a "conversation" you also have to send all the previous inputs/corresponding outputs in the "thread"? The entire thread is sent to `https://chat.openai.com/backend-api/moderations` from what I can see in the network tab.

This would entail storing the entire chatlog per conversationId?

Correct me if I'm wrong.

**Comment by transitive-bullshit** [comment]
> This would entail storing the entire chatlog per conversationId?

I don't think so. From what I understand, I think you only need the most recent message ID in the conversation for ChatGPT to pick up from there.

**Comment by simon300000** [comment]
My implementation in #26 would create new Conversation Object for each 'conversation', which should allows multiple concurrent Conversation with a single API. And also expose the metadata to user by exposing the event stream listener.

But there is no other way to manage conversations such as iterate all created conversation or create conversation manually, and I am not sure if that should be implemented and how, so 😝

**Comment by DerKorb** [comment]
I think it would be a good idea to be able to recreate a conversation using a previously used id. I think I'd rather manage a list myself.

**Comment by simon300000** [comment]
> I think it would be a good idea to be able to recreate a conversation using a previously used id. I think I'd rather manage a list myself.

I added some optional parameter in the `getConversation` function, seems somewhat better

**Comment by transitive-bullshit** [comment]
Just merged #26 by @simon300000 which is 🔥 Will update this thread once it's released to npm.

**Comment by transitive-bullshit** [comment]
Conversations are now supported as of https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v2.0.0

Huge shoutout to @simon300000 for the great PR 💪
