### ISSUE TITLE
Starting to get 404 when I send a message

### ISSUE THREAD

**Issue by frederikenghave** [transitive-bullshit/chatgpt-api#290]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node.js v18.13.0
Windows 10
Chrome Version 109.0.5414.120 (Official Build) (64-bit)

### Describe the Bug

I've been using the module with great success, but from today I started running into issues: When I send a message to ChatGPT I get an error code 404:

ChatGPTError: ChatGPTAPI error 404
    at ChatGPTAPIBrowser.sendMessage (...node_modules/chatgpt/build/index.js:1604:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ...chatgpt.js:49:21 {
  statusCode: 404,
  statusText: ''

Logging in still works for me.
It looks like an update from ChatGPT that needs to be incorporated into the module.

**Comment by anotherso1a** [comment]
same issue. today.

**Comment by anotherso1a** [comment]
upgrade to @4+ then fixed

**Comment by ws02589111** [comment]
same issue, my lib version is 4.0.4

**Comment by panlina** [comment]
Same. 4.0.4.

**Comment by LesterDong** [comment]
> Same. 4.0.4. For the first 2 runs it worked normally, and then it started to report `That model does not exist`.

+1, Seems openai found the bug and fixed it just now!

**Comment by panlina** [comment]
> > Same. 4.0.4. For the first 2 runs it worked normally, and then it started to report `That model does not exist`.
> 
> +1, Seems openai found the bug and fixed it just now!

I tried just now. Seems as you said it does not repro for now.

**Comment by panlina** [comment]
> > Same. 4.0.4. For the first 2 runs it worked normally, and then it started to report `That model does not exist`.
> 
> +1, Seems openai found the bug and fixed it just now!

But again, the same error.

**Comment by cy948** [comment]
find var `CHATGPT_MODEL` in file `node_modules/chatgpt/build/index.js`, then change it to the available model could fix it temporary.

```diff
- var CHATGPT_MODEL = "text-chat-davinci-002-20230126";
+ var CHATGPT_MODEL = "text-davinci-003";
```

**Comment by ws02589111** [comment]
> 

this is official public model, you can use official sdk to access it

**Comment by cy948** [comment]
我已经收到您的邮件，将在工作时间内2小时回复您。 I have received your email and will reply to you within 2 hours of working time.

**Comment by ikechan8370** [comment]
> 我已经收到您的邮件，将在工作时间内2小时回复您。 I have received your email and will reply to you within 2 hours of working time. 

What's this?

**Comment by cy948** [comment]
> 

That's a automatic reply from mailbox. 🤷‍♂️

**Comment by qbosen** [comment]
A temporary solution is to modify the model directly

```
const api = new ChatGPTAPI({apiKey: process.env.OPENAI_API_KEY})
api._completionParams.model = 'text-davinci-003';
```

**Comment by iota-unum** [comment]
> A temporary solution is to set the model
> 
> ```
> const api = new ChatGPTAPI({completionParams: {model: 'text-davinci-003'}});
> ```

So this works like a charm, but I want to point out that openai charges for this

**Comment by transitive-bullshit** [comment]
Update: the `text-chat-davinci-002-20230126` model has been disabled by OpenAI, which is what this library's currently using under the hood.

OpenAI released this model in stealth to YC and select partners last week. It was fine-tuned for chat and used to some extent by ChatGPT itself. After @waylaidwanderer discovered it, we updated this lib to use it.

This is a temporary setback as we look for a workaround. It is very likely that OpenAI partners still have access to a similar model. If you have any info on workarounds, please share them with one of the admins or in #general.

As @qbosen mentioned for a temporary workaround, you can override the `model` to use `text-davinci-003` to keep your applications running. This model isn't fine-tuned for chat like ChatGPT, but it will still produce reasonable results.

```ts
  const api = new ChatGPTAPI({
    apiKey: process.env.OPENAI_API_KEY,
    completionParams: {
      model: 'text-davinci-003'
    }
  })
```

**NOTE: this method is not free** and your OpenAI account will be charged for usage. Double check their pricing to make sure this is okay for your use case.

**Comment by transitive-bullshit** [comment]
This package's been updated to use the chatgpt model from 2022: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.1.1

Please upgrade to `v4.1.1` to try out the latest.
