### ISSUE TITLE
RIP. It was fun while it lasted

### ISSUE THREAD

**Issue by dex3r** [transitive-bullshit/chatgpt-api#292]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Version 4.0.4
Worked just a minute ago.

It was fun while it lasted

### Describe the Bug

`Error: ChatGPT error 404: {
    "error": {
        "message": "That model does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}`

**Comment by Armas0n** [comment]
Same 404. RIP confirmed?

**Comment by ws02589111** [comment]
RIP, maybe we just only use browser based solution, before the offical api coming ,

**Comment by B1LDER** [comment]
I was getting the same 404 error just a moment ago and now it's working just fine again. LOL. I don't know what to make of this.

**Comment by dex3r** [comment]
@B1LDER thanks for the update! It indeed works again for some reason. I wonder for how long :(

**Comment by deemkeen** [comment]
maybe they've restarted some services because of the heavy load, so the model was not available for a while

**Comment by dex3r** [comment]
It does not exist again :/

**Comment by vtxyer** [comment]
Thanks for updating ~~~ at least once had :)

**Comment by MichaelVandi** [comment]
It's going down intermittently. If you're running any sort of service with this. Just let your users know that ChatGPT is unstable right now. The constant anxiety is unhealthy.

**Comment by InnovativeCoder** [comment]
True, sometimes it is working, and sometimes showing the model not found.

**Comment by Korayem** [comment]
Time to revert back to the old puppeteer method? or at least have both options available in this npm package so we can build fallback mechanism

**Comment by ikechan8370** [comment]
https://github.com/waylaidwanderer/node-chatgpt-api/issues/19#issuecomment-1413982707
Try to change the default model.

**Comment by MichaelVandi** [comment]
Change to which one?

**Comment by ikechan8370** [comment]
> > [waylaidwanderer/node-chatgpt-api#19 (comment)](https://github.com/waylaidwanderer/node-chatgpt-api/issues/19#issuecomment-1413982707) Try to change the default model.
> 
> 
> 
> not available for me

You are right. I guess OpenAI is also deploying and replacing the model, so sometimes it works and sometimes it doesn't. (It seems to be always 404 now) Maybe we have to wait for it and find the name of the new model just like what the author did before.

**Comment by enricotal70** [comment]
Where? can you specify pretty please ...

**Comment by ikechan8370** [comment]
> > > [waylaidwanderer/node-chatgpt-api#19 (comment)](https://github.com/waylaidwanderer/node-chatgpt-api/issues/19#issuecomment-1413982707) Try to change the default model.
> > 
> > 
> > 
> > not available for me
> 
> You are right. I guess OpenAI is also deploying and replacing the model, so sometimes it works and sometimes it doesn't. (It seems to be always 404 now) Maybe we have to wait for it and find the name of the new model just like what the author did before.

I seem to be too optimistic. According to the discussion of the developers on Twitter, it seems that this method has really reached the end of life. Unless you turn to other models, it not only charges but also doesn't work well.

**Comment by dex3r** [comment]
Damn, thats a shame.
In the future I used to play with davinci 002. It was nothing like ChatGPT. Major prompt engineering techiques made it a bit better, but not even close.

Im wondering how are things with davinci 003? Is it closer to ChatGPT (with right prompting) or is it only slightly improved over davinci 002.

**Comment by waylaidwanderer** [comment]
FYI there is a new model version available, and that's why this one was removed. The person that knows the new model name is refusing to share it but has provided an API layer for his implementation.

IMO this is against the spirit of open-source, so if anyone has any leads, I implore you to share. From what I learned from them, if you have access to the Azure OpenAI services you may be able to find the model name there.

**Comment by mazique** [comment]
Mine still works 🤷‍♂️ I have this API connected to about 4 or 5 different services and they are all still working.

**Comment by transitive-bullshit** [comment]
Update: the `text-chat-davinci-002-20230126` model has been disabled by OpenAI, which is what this library's currently using under the hood.

OpenAI released this model in stealth to YC and select partners last week. It was fine-tuned for chat and used to some extent by ChatGPT itself. After @waylaidwanderer discovered it, we updated this lib to use it.

This is a temporary setback as we look for a workaround. It is very likely that OpenAI partners still have access to a similar model. If you have any info on workarounds, please share them with one of the admins or in #general.

As @qbosen mentioned for a temporary workaround, you can override the `model` to use `text-davinci-003` to keep your applications running. This model isn't fine-tuned for chat like ChatGPT, but it will still produce reasonable results.

```ts
  const api = new ChatGPTAPI({
    apiKey: process.env.OPENAI_API_KEY,
    completionParams: {
      model: 'text-davinci-003'
    }
  })
```

**NOTE: this method is not free** and your OpenAI account will be charged for usage. Double check their pricing to make sure this is okay for your use case.

**Comment by transitive-bullshit** [comment]
@mazique can you provide more details like the specific version of this package you're using? Also, is your OpenAI account associated with any OpenAI partners like YC that may still have access to the leaked model?

**Comment by mazique** [comment]
I am using the version that is included in the current version of this vs code extension:
https://github.com/gencay/vscode-chatgpt

This CLI Assistant 
https://github.com/diciaup/assistant-cli

And this vscode extension
https://github.com/barnesoir/chatgpt-vscode-plugin

**Comment by waylaidwanderer** [comment]
@mazique those just use the old browser-based solution.

**Comment by mazique** [comment]
Oh 🥴

**Comment by mazique** [comment]
Sorry about that. Well, let's get a new unofficial api going. There are so many great apps around here.

**Comment by luigi-bar** [comment]
Is the old browser-based approach still valid / maintained?
Thanks for the great work

Il Gio 2 Feb 2023, 21:21 Joel ***@***.***> ha scritto:

**Comment by AbuBakar-here** [comment]
In my case, it is giving me 429 "too many requests" instead of 404.

**Comment by ws02589111** [comment]
> Sorry about that. Well, let's find a new vulnerability for the unofficial api. There are so many great apps around here.

Is there any new information about official api?

**Comment by waylaidwanderer** [comment]
> In my case, it is giving me 429 "too many requests" instead of 404.

@AbuBakar-here you probably don't have any credits to use `text-davinci-003`. The API will return a 429 if you run out.

**Comment by waylaidwanderer** [comment]
Updated https://github.com/waylaidwanderer/node-chatgpt-api/releases/tag/v1.6.1 with a newly (possibly old) working ChatGPT model, just FYI

**Comment by tonyanhq** [comment]
I was just dev the code, and soon find out too many requests, and boom 404!

**Comment by ws02589111** [comment]
#https://github.com/waylaidwanderer/node-chatgpt-api/issues/19

The model `text-chat-davinci-002-20221122` is available for me

**Comment by farouqaldori** [comment]
Is it only me or `text-chat-davinci-002-20221122` is really slow?

**Comment by waylaidwanderer** [comment]
Seems to be responding quite quickly for me.

**Comment by ws02589111** [comment]
> Is it only me or `text-chat-davinci-002-20221122` is really slow?

quickly too

**Comment by transitive-bullshit** [comment]
This package's been updated to use the chatgpt model from 2022: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.1.1

Please upgrade to `v4.1.1` to try out the latest.

**Comment by shishir-wm** [comment]
> Is it only me or `text-chat-davinci-002-20221122` is really slow?

yup quite slow

**Comment by transitive-bullshit** [comment]
A lot faster than the browser version :)
