### ISSUE TITLE
Persist conversation state

### ISSUE THREAD

**Issue by bertybuttface** [transitive-bullshit/chatgpt-api#296]
### Describe the feature

We used to persist conversation state across reboots. Now we are using the new API based way of accessing ChatGPT the package we are using also needs to persist it's own state so that it can simulate the old `conversationId` and `parentMessageId` behaviour of the old interface.

**Comment by adrenallen** [comment]
I think this is the same issue I'm having, conversation context does not seem to be working when passing conversation and parent messaged id :(

**Comment by bertybuttface** [comment]
Apologies I raised this issue on the wrong library

**Comment by transitive-bullshit** [comment]
This is fully supported. See the `demos/demo-persistence.ts` for an example.

Any https://github.com/jaredwray/keyv is easy to use – or you can use `getMessageById` and `upsertMessage` to have full control over message persistence.
