### ISSUE TITLE
Passing the model as a constructor parameter

### ISSUE THREAD

**Issue by jcfigueiredo** [transitive-bullshit/chatgpt-api#302]
### Describe the feature

I might be wrong, and help me understand if I am, but if we don't hardcode the model by passing it as a parameter, this API could be used in many other scenarios with text-davinci-003, codex, and others.

**Comment by transitive-bullshit** [comment]
@jcfigueiredo Yep; just pass `completionParams: { model: 'text-davinci-003' }` to the constructor. You can pass any of the official OpenAI completion params to override this package's defaults.

**Comment by jcfigueiredo** [comment]
Awesome! Thank you. 🙏 Great project!
