### ISSUE TITLE
Occasionally meet exceptions that unable to catch

### ISSUE THREAD

**Issue by otakustay** [transitive-bullshit/chatgpt-api#308]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

```
  System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 13.99 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/Library/Caches/fnm_multishells/32653_1675674566329/bin/node
    Yarn: 3.2.1 - ~/Library/Caches/fnm_multishells/32653_1675674566329/bin/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/32653_1675674566329/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.3
```

### Describe the Bug

We're using `onMessage` to display message by chunk, we use a very simple code snippet like:

```ts
try {
    const response = await api.sendMessage(
        body.content,
        {
            conversationId: body.conversationId,
            parentMessageId: body.parentMessageId,
            onProgress: response => {
                this.logger.verbose(`[${id}] Partial reply ${JSON.stringify(response.text)}`);
                socket.send(JSON.stringify({event: 'progress', payload: response}));
            },
        }
    );
    this.logger.debug(`[${id}] Reply ${JSON.stringify(response.text)}`);
    socket.send(JSON.stringify({event: 'finish', payload: response}));
}
catch (ex) {
    const payload = ex instanceof ChatGPTError
        ? {statusCode: ex.statusCode, message: ex.message}
        : {statusCode: 500, message: ex instanceof Error ? ex.message : `${ex}`};
    this.logger.warn(`[${id}] Caught HTTP ${payload.statusCode}: ${JSON.stringify(payload.message)}`);
    socket.send(JSON.stringify({event: 'error', payload}));
}
```

Ocasionally we see errors in our log saying fetch is terminated, this error is not caught by `catch` clause so our server may crash on unhandled rejections.

![image](https://user-images.githubusercontent.com/639549/217162523-6ef524d3-6a58-4fde-a5fb-f04aea4f1cdf.png)

We expect all errors be caught, but wondering if SSE fetch or the abort signal stuff can create uncatcheable rejected promises reading response stream

**Comment by transitive-bullshit** [comment]
Interesting.

I think I know what might be going on. Just pushed a fix; can you upgrade to https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.1.3 and see if that resolve the issue for you?

The other possibility is that the socket is being forcibly closed after the initial HTTP request responds and during the message exchange. There's definitely room to add additional error handling logic here that may not be caught by the wrapping `Promise`.

**Comment by otakustay** [comment]
Have run the new version for 2 hours, didn't see any crash any more 👍
