### ISSUE TITLE
Nestjs integration

### ISSUE THREAD

**Issue by oleguslee** [transitive-bullshit/chatgpt-api#309]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node 18.12.1
nestjs ^8.0.0

### Describe the Bug

Hello! I'm trying to integrate into my project on nest js, but it does not support esm, how can I fix this?

**Comment by otakustay** [comment]
NestJS doesn't require a library to be ESM, I'm running it on NestJS 9.x, what errors did you get?

**Comment by elfillo** [comment]
I have the same problem with nestJs integration. 
`Error [ERR_REQUIRE_ESM]: require() of ES Module [node_modules/chatgpt/build/index.js] from [file path] not supported.
`

`"@nestjs/core": "^8.0.0`
`"chatgpt": "^4.1.3"`
`NodeJs v18.14.0`

**Comment by otakustay** [comment]
This is my `tsconfig.json`

```json
{
    "compilerOptions": {
        "module": "NodeNext",
        "target": "ES2022",
        "moduleResolution": "NodeNext",
        "declaration": true,
        "removeComments": true,
        "esModuleInterop": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "strict": true,
        "strictPropertyInitialization": false,
        "keyofStringsOnly": true,
        "sourceMap": false,
        "outDir": "./dist",
        "incremental": true,
        "skipLibCheck": true,
        "allowJs": false
    },
    "include": ["src"]
}
```

Also I have `"type": "module"` in `package.json`, maybe this is the fix, I'm working in a pure ESM environment

**Comment by elfillo** [comment]
Unfortunately that configuration break whole project;

**Comment by fourcolors** [comment]
I have this problem with Remix right now

**Comment by shishenbaiye** [comment]
Try to use this solution:

`export const importDynamic = new Function(
  'modulePath',
  'return import(modulePath)',
);`

and using it into your function:

```
const { ChatGPTAPI } = await importDynamic("chatgpt"); 
   this.gptApi = new ChatGPTAPI({ 
      apiKey: process.env.OPENAI_API_KEY as string,
});
```

**Comment by msborrow** [comment]
compilerOption.moduleResolution: Node16 add this to your tsconfig.json compilerOptions and enjoy

**Comment by transitive-bullshit** [comment]
There are also previous issues on here of Nestjs users posting their workarounds.

Sorry, but commonjs is deprecated and it's a huge pain for maintainers like myself to try and support both ESM and commonjs.

**Comment by ChuckJonas** [comment]
it's pretty funny that this claims to be the "official" open AI package, but isn't compatible out of the box with 99% of all existing codebases.  

ESM only modules are a PITA.
