### ISSUE TITLE
chatgpt@4.2.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "14.20.0"

### ISSUE THREAD

**Issue by gefeiyanga** [transitive-bullshit/chatgpt-api#312]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node 14.20.0

### Describe the Bug

I have added unfetch, but when I install chatgpt got this result.

**Comment by transitive-bullshit** [comment]
I would recommend upgrading your node.js version.

If you're restricted to using node.js 14, you can safely ignore this warning as long as `fetch` is defined.

**Comment by gefeiyanga** [comment]
> I would recommend upgrading your node.js version.
>  
> If you're restricted to using node.js 14, you can safely ignore this warning as long as `fetch` is defined.

but i got the error, how to ignore this error and continue to install chatgpt

**Comment by gefeiyanga** [comment]
> I would recommend upgrading your node.js version.
> 
> If you're restricted to using node.js 14, you can safely ignore this warning as long as `fetch` is defined.

Just like this:
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/30728843/217423170-d69908e3-37c0-484a-8bff-6d67638c451f.png">

**Comment by gefeiyanga** [comment]
ok, upgrade v18.10.0, everything is great
