### ISSUE TITLE
chatgpt-api today dosen't work, has no response!!!

### ISSUE THREAD

**Issue by FEjohnny** [transitive-bullshit/chatgpt-api#315]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Yesterday is worked!!

### Describe the Bug

Yesterday is worked!!

**Comment by christophebe** [comment]
it works for me with the version 4.2.0

**Comment by hafidzaini** [comment]
> it works for me with the version 4.2.0

yes, working fine after update to 4.2.0
this issue should be closed 😉

**Comment by hafidzaini** [comment]
but it wont be free 🤣
![](https://i.imgur.com/EWPwP6z.png)

**Comment by transitive-bullshit** [comment]
Please upgrade to v4.2.0. Unfortunately, OpenAI disabled the previous model and so it will now cost money to use with their official API.
