### ISSUE TITLE
I have passed the parentMessageid and conversationid，but it can't track the conversation.

### ISSUE THREAD

**Issue by gefeiyanga** [transitive-bullshit/chatgpt-api#316]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node 18.10.0

### Describe the Bug

I use the API just like this: 
```
      const res = await api.sendMessage(question, {
        conversationId,
        parentMessageId,
        timeoutMs: 3 * 60 * 1000,
      });
```
but the response has no cennection with the reference.
for example, I want it explain some code above, it can't know what i mean.

bad English, sorry.

**Comment by gefeiyanga** [comment]
Is that because we change the model to text-davinci-003?

**Comment by BoryaGames** [comment]
Yes, that's because of changing model.

**Comment by SimonBaars** [comment]
The problem is when you recycle the API, for example, this will not retain history:
```
let api = new ChatGPTAPI({
  apiKey: process.env.OPENAI
})
let res = await api.sendMessage('Write two paragraphs about cotton candy.')
console.log(res.text)
api = new ChatGPTAPI({
  apiKey: process.env.OPENAI
})
res = await api.sendMessage('What were we talking about?', {conversationId: res.conversationId, parentMessageId: res.id})
console.log(res.text)
```

But this will:
```
let api = new ChatGPTAPI({
  apiKey: process.env.OPENAI
})
let res = await api.sendMessage('Write two paragraphs about cotton candy.')
console.log(res.text)
res = await api.sendMessage('What were we talking about?', {conversationId: res.conversationId, parentMessageId: res.id})
console.log(res.text)
```

**Comment by transitive-bullshit** [comment]
Check out the persistence demo.

You can use any `keyv` adaptor to store messages to they're recorded between sessions.

**Comment by gefeiyanga** [comment]
> The problem is when you get a new API instance, for example, this will not retain history:
> 
> ```
> let api = new ChatGPTAPI({
>   apiKey: process.env.OPENAI
> })
> let res = await api.sendMessage('Write two paragraphs about cotton candy.')
> console.log(res.text)
> api = new ChatGPTAPI({
>   apiKey: process.env.OPENAI
> })
> res = await api.sendMessage('What were we talking about?', {conversationId: res.conversationId, parentMessageId: res.id})
> console.log(res.text)
> ```
> 
> But this will:
> 
> ```
> let api = new ChatGPTAPI({
>   apiKey: process.env.OPENAI
> })
> let res = await api.sendMessage('Write two paragraphs about cotton candy.')
> console.log(res.text)
> res = await api.sendMessage('What were we talking about?', {conversationId: res.conversationId, parentMessageId: res.id})
> console.log(res.text)
> ```

thanks，you are right.

**Comment by suzumiyahifumi** [comment]
I want to know that could I retain history in different  API instance? I wish the conversation is continue when server has restarted.

**Comment by suzumiyahifumi** [comment]
I want to know that could I retain history in different API instance? I wish the conversation is continue when server has restarted.

**Comment by transitive-bullshit** [comment]
@suzumiyahifumi https://github.com/transitive-bullshit/chatgpt-api/issues/316#issuecomment-1423194385

**Comment by suzumiyahifumi** [comment]
@transitive-bullshit 
You mean that I can save the status of server sessions with keyv, and when I restart server the  conversation will continue  with same parentMessageid and conversationid when old sessions has loaded into new instance by keyv?

**Comment by transitive-bullshit** [comment]
> @transitive-bullshit You mean that I can save the status of server sessions with keyv, and when I restart server the conversation will continue with same parentMessageid and conversationid when old sessions has loaded into new instance by keyv?

Yes :) you need to store these messages to a persistent data store. `keyv` supports many different types of databases.

**Comment by suzumiyahifumi** [comment]
> > @transitive-bullshit You mean that I can save the status of server sessions with keyv, and when I restart server the conversation will continue with same parentMessageid and conversationid when old sessions has loaded into new instance by keyv?
> 
> Yes :) you need to store these messages to a persistent data store. `keyv` supports many different types of databases.

Okay, I will try it.
Since I has used redis to keep parentMessageid and conversationid pair for all conversations, but when server restart conversation can't retain. 
Now, I try your methed. Bless me, I hope it can retain in new server instance.
Thank you, if it is work, I will reply in here :)

**Comment by suzumiyahifumi** [comment]
@transitive-bullshit 
I have seen the update of keyv functional right now, this late for me, Thank you again :)

**Comment by DevXiaolan** [comment]
> @transitive-bullshit I have seen the update of keyv functional right now, this late for me, Thank you again :)

man ,how is going ?
Is it work? 
Any demo codes for retain a conversation when server restart ? ( that means totally a new instance.)

**Comment by suzumiyahifumi** [comment]
> > @transitive-bullshit I have seen the update of keyv functional right now, this late for me, Thank you again :)
> 
> man ,how is going ? Is it work? Any demo codes for retain a conversation when server restart ? ( that means totally a new instance.)

Yes, it must be work. It is working on my bot service. All functionality is good :)

**Comment by vvmspace** [comment]
> The problem is when you get a new API instance, for example, this will not retain history:
> 
> ```
> let api = new ChatGPTAPI({
>   apiKey: process.env.OPENAI
> })
> let res = await api.sendMessage('Write two paragraphs about cotton candy.')
> console.log(res.text)
> api = new ChatGPTAPI({
>   apiKey: process.env.OPENAI
> })
> res = await api.sendMessage('What were we talking about?', {conversationId: res.conversationId, parentMessageId: res.id})
> console.log(res.text)
> ```
> 
> But this will:
> 
> ```
> let api = new ChatGPTAPI({
>   apiKey: process.env.OPENAI
> })
> let res = await api.sendMessage('Write two paragraphs about cotton candy.')
> console.log(res.text)
> res = await api.sendMessage('What were we talking about?', {conversationId: res.conversationId, parentMessageId: res.id})
> console.log(res.text)
> ```

Any way to solve this problem?
I am using lambda and I can not to have single instance for user's chat
