### ISSUE TITLE
today chat-gpt doesn't work

### ISSUE THREAD

**Issue by SixDjango** [transitive-bullshit/chatgpt-api#317]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

v4.2.0

### Describe the Bug

today chat-gpt doesn't work , there is no any response

**Comment by hafidzaini** [comment]
v4.2.0 should be working, but cost money.
but i get this error too while using v4.2.0 with davinci003

Error: ChatGPT error 429: {
  "error": {
    "message": "The server had an error while processing your request. Sorry about that!",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

**Comment by allthingssecurity** [comment]
Will we plan to move to browser based solution or we have challenges, there also? Not sure just asking

**Comment by karam-khanna** [comment]
same issue.

**Comment by hafidzaini** [comment]
browser based solution could use puppeteer and should bypass cloud flare.
im waiting for this browser version too

**Comment by transitive-bullshit** [comment]
Please see my previous answer regarding the switch away from the browser version: https://github.com/transitive-bullshit/chatgpt-api/issues/314#issuecomment-1422395492
