### ISSUE TITLE
ChatGPT becoming less reliable

### ISSUE THREAD

**Issue by KevinKaiwenZheng** [transitive-bullshit/chatgpt-api#324]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node: 18
OS: Cent OS Stream 9

### Describe the Bug

I think somehow the GPT is becoming stupid. I have not changed the prompt, but the response it generates is significantly shorter and less reliable than a few days earlier. I'm not sure if it is because the model had been changed or something else, but it did happen.

**Comment by actuallydan** [comment]
I've noticed this anecdotally as well, but I haven't used this library since they added the Cloudflare protection. Is it possible that the ChatGPT webapp is running some sort of additional layer on top of this model to transform the shorter output into more conversational and helpful output?

(also big thanks to @transitive-bullshit for building this!)

**Comment by arashn** [comment]
@KevinKaiwenZheng which version of the model are you using? 

The current default model in this project is `text-davinci-003`, which is not the same model that ChatGPT is using and its responses are not as detailed. Earlier, the default model used in this project was the one used by ChatGPT, but OpenAPI has now limited access to it, hence the switch to `text-davinci-003`.

Take a look at [this line](https://github.com/transitive-bullshit/chatgpt-api/blob/835959f6b76382fbd6a545f1addd609b8bf06a33/src/chatgpt-api.ts#L14) to see the model names and the current default one. Also, see [here](https://github.com/waylaidwanderer/node-chatgpt-api#updates) about recent changes to the ChatGPT API.

**Comment by KevinKaiwenZheng** [comment]
@arashn Thanks & noted. Thanks again for @transitive-bullshit for the amazing API. Waiting for the official API or a better version for this API to come XD
