### ISSUE TITLE
api方式 text-davinci-003 请求的聊天结果和浏览器中使用的完全不一样

### ISSUE THREAD

**Issue by leadscloud** [transitive-bullshit/chatgpt-api#326]
### Describe the feature

api方式 text-davinci-003 请求的聊天结果和浏览器中使用的完全不一样

能否增加额外使用chrome浏览器的方式，api方式返回的内容不太好。

**Comment by transitive-bullshit** [comment]
See my answer here: https://github.com/transitive-bullshit/chatgpt-api/issues/314#issuecomment-1422395492

Closing as a duplicate of #319
