### ISSUE TITLE
Allow custom fetch function

### ISSUE THREAD

**Issue by otakustay** [transitive-bullshit/chatgpt-api#333]
### Describe the feature

We're using this client but requires http proxy agent setup, by using `undici` library we can pass `dispatcher` to `fetch` function, however directly call of `fetch` allows less options than `undici`.

I'd propose `new ChatGPTAPI` accepts a `fetch` function option to use instead of the native global `fetch` function, then we can customize proxies, keep alives, timeouts and more.

**Comment by transitive-bullshit** [comment]
Excellent idea @otakustay; completed in https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.4.0
