### ISSUE TITLE
vite2 + vue3 ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by classfang** [transitive-bullshit/chatgpt-api#334]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

vite2 + vue3 node=18.0

### Describe the Bug

vite2 + vue3 ReferenceError: __dirname is not defined

**Comment by transitive-bullshit** [comment]
I don't think this error is likely to do with the `chatgpt` module. Note: `chatgpt` should only be used from Node.js server-side.

Without more info, we won't be able to help you.

**Comment by JerryCheng1** [comment]
> I don't think this error is likely to do with the `chatgpt` module. Note: `chatgpt` should only be used from Node.js server-side.
> 
> Without more info, we won't be able to help you.

the same error was encountered in other vue3 project
console output:
```
Uncaught (in promise) ReferenceError: __dirname is not defined
    at node_modules/gpt-3-encoder/Encoder.js (Encoder.js:5:54)
    at __require2 (chunk-IKJM6GHQ.js?v=321da443:18:50)
    at node_modules/gpt-3-encoder/index.js (index.js:1:28)
    at __require2 (chunk-IKJM6GHQ.js?v=321da443:18:50)
    at chatgpt-api.ts:1:37
```

**Comment by transitive-bullshit** [comment]
It looks like this code is trying to be used from a non-Node.js environment according to what Vite expects. That's the only reason why `__dirname` wouldn't be defined.

With that being said, https://github.com/latitudegames/GPT-3-Encoder has some problems, and I'm definitely looking to replace it. It has compatibility issues like this one, only support node.js, and it's not up-to-date.

If anyone has a good alternative tokenizer (like a JS version of https://github.com/openai/tiktoken), please let me know.

**Comment by JerryCheng1** [comment]
您的邮件已收到。祝您生活愉快！

**Comment by JerryCheng1** [comment]
[This issue solves the error ](https://github.com/latitudegames/GPT-3-Encoder/issues/32)

1. Edit `PATH_OF_PROJECT/node_modules/gpt-3-encoder/Encoder.js`
```js
//const encoder = JSON.parse(fs.readFileSync(path.join(__dirname, './encoder.json')));
//const bpe_file = fs.readFileSync(path.join(__dirname, './vocab.bpe'), 'utf-8');

const encoder = require('./encoder.json')
const bpe_file = require('./vocab_bpe.json')
```
2. Add [vocab_bpe.json](https://github.com/latitudegames/GPT-3-Encoder/files/10713133/gpt-3-encoder-react.zip) into `PATH_OF_PROJECT/node_modules/gpt-3-encoder`
3. Delete node_modules/.vite

Enjoy

**Comment by JamieMcDonnell** [comment]
Hi, thanks for the suggestions, but where can I find 'vocab_bpoe.json'? It's not in the repo. Do I need to convert vocab.bpe to JSON or can I find it somewhere else? Thanks a lot.

**Comment by transitive-bullshit** [comment]
@JamieMcDonnell @JerryCheng1 @classfang try the new version https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.6.0

It replaces the troublesome gpt-3-encoder with a better dependency.
