### ISSUE TITLE
vue 3 fs.readFileSync (Encoder.js)

### ISSUE THREAD

**Issue by heavywar** [transitive-bullshit/chatgpt-api#336]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

vue 3 
webpack 5

### Describe the Bug

i get error if import chatgpt

` import { ChatGPTAPI } from 'chatgpt'
`
```
app.js:494 Uncaught TypeError: fs.readFileSync is not a function
    at eval (Encoder.js?0bd4:5:1)
    at ./node_modules/gpt-3-encoder/Encoder.js (chunk-vendors.js:762:1)
    at __webpack_require__ (app.js:491:33)
    at fn (app.js:776:21)
    at eval (index.js?86a2:1:1)
    at ./node_modules/gpt-3-encoder/index.js (chunk-vendors.js:772:1)
    at __webpack_require__ (app.js:491:33)
    at fn (app.js:776:21)
    at eval (index.js:28:72)
    at ./node_modules/chatgpt/build/index.js (chunk-vendors.js:7049:1)
```

my vue.js
```

module.exports = {
  transpileDependencies: true,
  configureWebpack: {
    plugins: [
      new NodePolyfillPlugin()
    ],
    
  
}
```

first i got error 
```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
```
after i added node-polyfill-webpack-plugin, i get new error:

> ERROR in ./node_modules/gpt-3-encoder/Encoder.js 52:9-22
> Module not found: Error: Can't resolve 'fs' in 

And i aded:
```
 resolve: {

      fallback: {
        fs:  false
      }
    }

```
And after it i got error about fs.readFileSync is not a function

**Comment by transitive-bullshit** [comment]
@JamieMcDonnell @JerryCheng1 @classfang try the new version https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.6.0

It replaces the troublesome gpt-3-encoder with a better dependency.

**Note**: make sure you're only using this package from backend node.js code.
