### ISSUE TITLE
How to bypass the latest cloudflare hunman verify?

### ISSUE THREAD

**Issue by LesterDong** [transitive-bullshit/chatgpt-api#337]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

win10
node v18.13

### Describe the Bug

![image](https://user-images.githubusercontent.com/25879996/218708381-f275599b-a7eb-42e3-817c-38fa1fe3ba94.png)

I still based on your v3 branch, which is Browser-based solution，i just want to know how to by pass the human verify, nopecha seems not working... In addition，capacity check seems not working too

**Comment by LesterDong** [comment]
Nopecha has a corresponding solution but I don't know how to integrate it into the code. It's really embarrassing. https://developers.nopecha.com/token/turnstile/

**Comment by transitive-bullshit** [comment]
See also my answer in #341

I do not plan on continuing to support v3, but the new `ChatGPTUnofficialProxyAPI` should fulfill most needs since it's free and uses the real ChatGPT – and is much lighter-weight than the previous full browser solution.
