### ISSUE TITLE
How to integrate Dall-e?

### ISSUE THREAD

**Issue by JeoriTr** [transitive-bullshit/chatgpt-api#338]
### Describe the feature

How to integrate Dall-e 2 into ChatGPT node, please guide me. Thank you.

**Comment by cmbitton** [comment]
Dalle2 is included in OpenAI's API. Its very easy to integrate, the documentation is available here: https://platform.openai.com/docs/guides/images/usage

**Comment by transitive-bullshit** [comment]
This is outside the scope of this project since DALL-E and ChatGPT are two separate AIs.

**Comment by transitive-bullshit** [comment]
@JeoriTr here's a great example of how to integrate this package with DALL-E https://github.com/askrella/whatsapp-chatgpt
