### ISSUE TITLE
Does someone still use v3 successfully?

### ISSUE THREAD

**Issue by MaLcai** [transitive-bullshit/chatgpt-api#341]
### Describe the feature

Is V3 still effective?

**Comment by itskdhere** [comment]
> Is V3 still effective?


Yup

**Comment by LesterDong** [comment]
How did you solve "Verify you are human" defense?

**Comment by itskdhere** [comment]
> How did you solve "Verify you are human" defense?

Manually 🙂

**Comment by LesterDong** [comment]
> > How did you solve "Verify you are human" defense?
> 
> Manually 🙂

I mean it has to be solved automatically, otherwise the solution is meaningless

**Comment by tom-leamon** [comment]
I'm using V3 successfully, but it doesn't work with ChatGPT Plus accounts, unfortunately.

**Comment by transitive-bullshit** [comment]
Note that I'm not currently planning on supporting v3 going forwards. I recommend that you use the new `ChatGPTUnofficialProxyAPI` instead (introduced in v4.5.0).

<img width="853" alt="CleanShot 2023-02-19 at 04 07 06@2x" src="https://user-images.githubusercontent.com/552829/219941518-16dd9fbd-2aa4-41b2-b267-f1d0a03c59aa.png">

**Comment by transitive-bullshit** [comment]
If you want to discuss v3 with other users, feel free to ask in our [Discord](https://discord.gg/v9gERj825w).
