### ISSUE TITLE
Reverse Proxy server is not Working

### ISSUE THREAD

**Issue by suhail-ak-2** [transitive-bullshit/chatgpt-api#344]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node js - 19
Brower - Chrome 109.0
Os- Mac Os Ventura 13.2

### Describe the Bug

When i runnong the reverse proxy it is throwing service unavailable.

Reverse proxy url [-]('https://chatgpt.pawan.krd/api/completions')

`ChatGPTError: ChatGPT error 503: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
<script src="/cdn-cgi/apps/head/dYMkwc06fJ_hgAqAMinzib-CLyo.js"></script></head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<hr>
<address>Apache/2.4.52 (Ubuntu) Server at chatgpt.pawan.krd Port 80</address>
<script>(function(){var js = "window['__CF$cv$params']={r:'799ca3e52afd9be0',m:'SZU_qk553OVTPmjrnSXxPlC2VW3bvt9a7dftdRrZuQw-1676449393-0-AQb6VUR5+N9RVtUdn3bITlSwTwenrg7XXRuYc8d6JN+C6MlzmNDpYkDR+6uA1jAqDq08QOFv9ZII7+IEWeLQn6U9GWnou5gkpe77tkxwW1wz5leyUPMmIUYzfOTdl4jtzw==',s:[0x2c15d9282f,0x65de5dae90],u:'/cdn-cgi/challenge-platform/h/b'};var now=Date.now()/1000,offset=14400,ts=''+(Math.floor(now)-Math.floor(now%offset)),_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/h/b/scripts/alpha/invisible.js?ts='+ts,document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.nonce = '';_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script></body></html>`

**Comment by transitive-bullshit** [comment]
Specific reverse proxy servers like the one hosted by @PawanOsman are outside the scope of this repo.
