### ISSUE TITLE
Is there a plan to create browser client version?

### ISSUE THREAD

**Issue by hbq969** [transitive-bullshit/chatgpt-api#345]
### Describe the feature

The current version needs to rely on many nodejs server features, Whether to consider developing a browser client version？

**Comment by transitive-bullshit** [comment]
`v3` is the browser version. You can still use `v3.5.1` if you want.

I've moved on from maintaining it because it was a pain to maintain, tended to be flaky, and the official API is coming soon.

**Comment by hbq969** [comment]
> `v3` is the browser version. You can still use `v3.5.1` if you want.
> 
> I've moved on from maintaining it because it was a pain to maintain, tended to be flaky, and the official API is coming soon.

ok, thank you!

**Comment by jakobsa** [comment]
Maintaining the puppeteer based version is a pain, I understand that. I want to add one argument for doing so however.
With ChatGPT Plus it seems that the playground is faster and most of all requests from there are not billed. When using the API via Rest/APIKey, it is billed to the issuing account.

**Comment by transitive-bullshit** [comment]
@jakobsa @hbq969 You can now use `ChatGPTUnofficialProxyAPI ` which uses the a proxied version of the real ChatGPT API. Upgrade to https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.5.0

I think this should solve your concerns regarding the previous browser-based version.

**Comment by jakobsa** [comment]
Thank you very much! Just tried it out. Worked on first trial. Also now having the conversation thread back in the playground. Which is great for debugging.

**Comment by hbq969** [comment]
> @jakobsa @hbq969 You can now use `ChatGPTUnofficialProxyAPI ` which uses the a proxied version of the real ChatGPT API. Upgrade to https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.5.0
> 
> I think this should solve your concerns regarding the previous browser-based version.

Great, good job!
