### ISSUE TITLE
chatgpt wrong answer about date, year, time

### ISSUE THREAD

**Issue by JeoriTr** [transitive-bullshit/chatgpt-api#347]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node.js

### Describe the Bug

I'm in the GMT+7 time zone. when the questions about date, time bot all answered wrong.
Is there a way to set GMT+7 time zone for chatgpt?

**Comment by williamlee1982** [comment]
yes, just tell it your time zone at first and ask it to answer your question about date and time in your time zone

**Comment by transitive-bullshit** [comment]
You can set a custom `promptPrefix` to tell GPT your desired time. Use the optional `promptPrefix` parameter of `sendMessage` https://github.com/transitive-bullshit/chatgpt-api/blob/main/docs/modules.md#sendmessageoptions
