### ISSUE TITLE
I get this "fetch failed" error sometimes.

### ISSUE THREAD

**Issue by gefeiyanga** [transitive-bullshit/chatgpt-api#350]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Please see image below.

### Describe the Bug

<img width="697" alt="image" src="https://user-images.githubusercontent.com/30728843/219342552-7287dc7f-bea0-4bf2-ac75-0685f1c20e85.png">

**Comment by eebssk1** [comment]
The "vulnerable" that the project currently using is now patched by openai.Good time gone now.

**Comment by gefeiyanga** [comment]
> The "vulnerable" that the project currently using is now patched by openai.Good time gone now.

据我所知，除了之前那个泄漏模型，作者用的都是openai开源的东西。

**Comment by transitive-bullshit** [comment]
@gefeiyanga network errors can happen sometimes. I recommend wrapping your logic in https://github.com/sindresorhus/p-retry and using `timeoutMs` to cancel requests that take too long to resolve.

> The "vulnerable" that the project currently using is now patched by openai.Good time gone now.

@eebssk1 this is false. there are several models which have been disabled by OpenAI, but this package still works and provides multiple viable options for accessing ChatGPT. The default `ChatGPTAPI` uses the official OpenAI completions API which will never be shut down or patched – it's the official API, although on our end it's just mimicking ChatGPT. On the other hand, I just added `ChatGPTUnofficialProxyAPI` which uses a proxied version of the official ChatGPT webapp's API, and that's currently working.
