### ISSUE TITLE
Logo for the project

### ISSUE THREAD

**Issue by gucr** [transitive-bullshit/chatgpt-api#353]
### Describe the feature

Here is a logo idea for the project.

The main idea was to reflect the ChatGPT global shape and add some electronic-ish circuits to suggest the idea of "connecting into" ChatGPT.

If you like it I can PR a hand crafted SVG

![cgptapi](https://user-images.githubusercontent.com/6040008/219533044-3208dce0-432c-4988-bb40-0c4d9ff1eace.png)

**Comment by transitive-bullshit** [comment]
I really love this @gucr 💕 

Would be happy to accept a PR – I may want to tweak the text a bit in Figma after merging the initial PR if that's okay, but I love the logo. Really appreciate it!

Feel free to add yourself to the credits section in your PR as well for making the logo 😄 Thanks!!

**Comment by gucr** [comment]
Hey @transitive-bullshit, glad you like it :)

Here is the [Figma file](https://github.com/transitive-bullshit/chatgpt-api/files/10809631/ChatGPT-logo.fig.zip). It contains the logo and the color codes so you can play with it. The font used is the [Inter Family](https://github.com/rsms/inter)

By the way the icon is hand-coded an less thann a KB. If you re-export it with Figma it will be way bigger even if you optimize it with SVGO. So if you want me to re-optimize the file after your modifications, feel free to ping me!

**Comment by transitive-bullshit** [comment]
Sorry I never got around to adding this, Guillaume. This project is undergoing a major revamp, and I'm closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
