### ISSUE TITLE
Can I use a fine-tuned model?

### ISSUE THREAD

**Issue by samo-c** [transitive-bullshit/chatgpt-api#355]
### Describe the feature

Can I use a fine-tuned model? What should I do?

`
const api = new ChatGPTAPI({
    apiKey: "",
      CompletionParams:{
         model:"FINE_TUNED_MODEL"
       }
})
`
This option does not appear to be in effect. What should I do?

**Comment by transitive-bullshit** [comment]
This should be:

```
new ChatGPTAPI({ apiKey: "", completionParams:{ model:"FINE_TUNED_MODEL" } })
```

Note the lower-case `completionParams`.

You can set `debug: true` to print out the body we're sending to OpenAI.
