### ISSUE TITLE
how to set max tokens and temperature 

### ISSUE THREAD

**Issue by unnimona** [transitive-bullshit/chatgpt-api#356]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

how to set max tokens and temperature 

### Describe the Bug

how to set max tokens and temperature

**Comment by transitive-bullshit** [comment]
```ts
const api = new ChatGPTAPI({ completionParams: { temperature: 0.5 }, maxResponseTokens: 50 })
```

Note: you can set any OpenAI params in `completionParams`.

Note: we're overriding `max_tokens` right now depending on how large your context window and prompt are, so `maxResponseTokens` will override that.
