### ISSUE TITLE
Support acheong08's v1 browserless API to use the real ChatGPT model

### ISSUE THREAD

**Issue by RainEggplant** [transitive-bullshit/chatgpt-api#357]
### Describe the feature

The reverse proxy method by `@waylaidwanderer` has recently been patched by OpenAI, which makes using the real ChatGPT model with a browserless API impossible. However, `@acheong08` has implemented a proxy server that allows users to bypass Cloudflare protection and use ChatGPT [through his v1 API](https://github.com/acheong08/ChatGPT#v1-standard-chatgpt). While the API is different from the official API, it is still functional. Can you consider supporting `@acheong08`'s v1 API in this project?

**Comment by transitive-bullshit** [comment]
Definitely @RainEggplant

You can now use `ChatGPTUnofficialProxyAPI ` which uses the a proxied version of the real ChatGPT API. Upgrade to https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.5.0

The default uses @acheong08's reverse proxy, but there are other proxies available from the community that you can override. I tried to add details to the readme to help describe the tradeoffs between these different approaches. Please let me know what you think.

Thanks!

**Comment by RainEggplant** [comment]
Thank you @transitive-bullshit ❤! The API works pretty well. And I really like the comparison table, which is very straightforward. It should help people understand the differences between these methods.

**Comment by transitive-bullshit** [comment]
Appreciate the feedback @RainEggplant 🙏  Thanks again
