### ISSUE TITLE
I'm trying to integrate this project with a frontend, 

### ISSUE THREAD

**Issue by pfeducode** [transitive-bullshit/chatgpt-api#358]
### Describe the feature

I'm trying to integrate this project with a frontend, but I'm encountering version conflicts when using Umi. I attempted to integrate it with nodejs+koa2, but that also failed. I'm hoping to run this project as a standalone service to provide an API for the frontend, which will help avoid version conflicts. If you can help me get this project up and running as a standalone service, it would be very helpful. Thank you.
![image](https://user-images.githubusercontent.com/100210045/219687213-10bc09e8-cd66-47bc-a44c-d1eb02f3137f.png)

**Comment by transitive-bullshit** [comment]
Hmmm, `gpt-3-encoder` definitely has problems.

I'm not sure the exact issue you're running into, but I'm looking to replace that dependency.

This may be helpful for you:

```ts
async function example() {
  // To use ESM in CommonJS, you can use a dynamic import
  const { ChatGPTAPI } = await import(https://github.com/transitive-bullshit/chatgpt-api)

  const api = new ChatGPTAPI({ apiKey: process.env.OPENAI_API_KEY })

  const res = await api.sendMessage('Hello World!')
  console.log(res.text)
}
```

#336 and #334 look related as they all have to do with compat issues with `gpt-3-encoder`.

**Comment by JamieMcDonnell** [comment]
Hey there,
I just tried to spin up my first Vue3/Quasar/ChatGPT project and hit this issue. Trying to include the ChatGPTAPI from your repo directly gives me a CORS error. I'm running currently on localhost:9000.

Any chance you can whitelist localhost?

Thanks!!

**Comment by transitive-bullshit** [comment]
Try the new version https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.6.0

It replaces the troublesome gpt-3-encoder with a better dependency.

> Any chance you can whitelist localhost?

Any CORS issues are happening in your webapp and have nothing to do with this project.
