### ISSUE TITLE
chatgpt在nest无法正常引入

### ISSUE THREAD

**Issue by QianShi-ffg** [transitive-bullshit/chatgpt-api#360]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

chatgpt版本4.4.1     nodejs  18.12.1

### Describe the Bug

在nestjs的service中，无法使用require(), 也无法使用import
当使用irequire()时，出现如下错误
![image](https://user-images.githubusercontent.com/56419687/219882327-8b844d92-9e6f-4ce9-9369-d7c1c46f0ec3.png)

当使用import时，出现如下错误
![image](https://user-images.githubusercontent.com/56419687/219882268-7c7db5ed-87d6-4576-81ec-af8baa8f438b.png)

在使用动态导入const { ChatGPTAPI } = await import('chatgpt'); 时，接口无法正常运行，会报下面的错误
![image](https://user-images.githubusercontent.com/56419687/219882780-3c15a537-c687-4920-952c-ff59abcd6326.png)

**Comment by CarlDuFromChina** [comment]
nodejs 默认是 CommonJS 导出导入方案，如果你导入的包没有做 CommonJS 导出而是使用了 ES Module 就会出现问题。你可以试试以下方案。

```javascript
export const importDynamic = new Function('modulePath', 'return import(modulePath)');
const { ChatGPTAPI } = await importDynamic('chatgpt');
```

**Comment by transitive-bullshit** [comment]
The readme has an example of how you can import an ESM module from commonjs.

There are also numerous other issues on this repo you can search through, including other people using nest.js who have posted their solutions.

Cheers,
