### ISSUE TITLE
Cannot read properties of undefined (reading 'packageJson') when using npx chatgpt

### ISSUE THREAD

**Issue by zeke** [transitive-bullshit/chatgpt-api#366]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

```
$ npx --version
8.19.3

$ uname -a
Darwin ezekiels-mbp.lan 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64
```

### Describe the Bug

I can run `npx chatgpt` and `npx chatgpt@latest` from some directories, but in others I get an error.

```
~/git/replicate/scribble-diffusion bypass-vercel-image-optimization
$ npx chatgpt "write a shell command to convert input.mov to output.mp4, and speed it up 2x"

ffmpeg -i input.mov -filter:v "setpts=0.5*PTS" -an output.mp4

~/git/replicate/scribble-diffusion bypass-vercel-image-optimization
$ cd ~

~
$ npx chatgpt "write a shell command to convert input.mov to output.mp4, and speed it up 2x"
TypeError: Cannot read properties of undefined (reading 'packageJson')
    at main (file:///Users/z/.npm/_npx/060caca6003d4dba/node_modules/chatgpt/bin/cli.js:11:39)

~
$ npx chatgpt@latest "write a shell command to convert input.mov to output.mp4, and speed it up 2x"
TypeError: Cannot read properties of undefined (reading 'packageJson')
    at main (file:///Users/z/.npm/_npx/0395a9b5d614bda1/node_modules/chatgpt/bin/cli.js:11:39)
```

**Comment by zeke** [comment]
@transitive-bullshit maybe this is something with my env? Not sure. Let me know if there's something I can do to help debug.

**Comment by transitive-bullshit** [comment]
Hmmm I'm using https://github.com/sindresorhus/read-pkg-up to read the package.json version. Probably overkill, but still I'm surprised.

**Comment by transitive-bullshit** [comment]
Thanks @zeke. I think this should be fixed in https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.7.1

**Comment by zeke** [comment]
Nice! It works 💛
