### ISSUE TITLE
Incomplete content display

### ISSUE THREAD

**Issue by MkMarko** [transitive-bullshit/chatgpt-api#368]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

origin: https://chat.openai.com
referer: https://chat.openai.com/chat
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36

### Describe the Bug

I asked a question on the ChatGPT official website and interface: help me write a JS game. He showed it but didn't show it completely because Max_ The reason for token? But why does this problem occur on the official website? How should my interface solve this problem? And when finish_ If reason is right, it is not displayed completely, finish_ When reason is stop, it is displayed completely. When finish_ How to get the remaining content when reason is length?
<img width="737" alt="截屏2023-02-20 11 16 22" src="https://user-images.githubusercontent.com/24669328/220002319-8885dcc9-a211-4b0f-96e9-a32d216d9709.png">
<img width="735" alt="截屏2023-02-20 11 17 11" src="https://user-images.githubusercontent.com/24669328/220002332-fc79b134-4fb1-4f14-9464-5edb9496ef6f.png">
<img width="1087" alt="截屏2023-02-20 11 21 25" src="https://user-images.githubusercontent.com/24669328/220002338-7baa8b7d-7601-400f-8abe-e33332ee05ae.png">

**Comment by transitive-bullshit** [comment]
This may be due to going over the token limit (along with your conversation history).

If this happens, the response will cutoff mid-stream.

Maybe try using the official API in the latest update: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v5.0.0
