### ISSUE TITLE
How can I integrate into my Vue application?

### ISSUE THREAD

**Issue by leducgiachoang** [transitive-bullshit/chatgpt-api#369]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

This is my code, it doesn't seem to be working.
`const api = new ChatGPTAPI({apiKey: localStorage.getItem("SECRET_KEY")});`
`const res = await api.sendMessage(text)`
`console.log(res)`

It requires the Buffer library and I have installed it but still encounter errors.
`npm install buffer`

Is this an error message? Can anyone help me?

![Screenshot from 2023-02-20 10-58-48](https://user-images.githubusercontent.com/69897727/220006694-f43174c9-8e7b-45d5-8332-a1517df98b21.png)

### Describe the Bug

Cannot use libraries within Vuejs application, I need help

**Comment by transitive-bullshit** [comment]
@leducgiachoang this package is node.js-only, so you need to put it in a backend API route that you can call from your frontend.

if you try to put node.js modules in browser / frontend code, you'll random errors like this one.

**Comment by leducgiachoang** [comment]
> @leducgiachoanggói này chỉ dành cho node.js, vì vậy bạn cần đặt gói này vào tuyến API phụ trợ mà bạn có thể gọi từ giao diện người dùng của mình.
> 
> nếu bạn cố gắng đặt các mô-đun node.js trong mã trình duyệt/giao diện người dùng, bạn sẽ gặp các lỗi ngẫu nhiên như lỗi này.

Could you please guide me on how to track chat process using nodejs?

**Comment by leducgiachoang** [comment]
> @leducgiachoanggói này chỉ dành cho node.js, vì vậy bạn cần đặt gói này vào tuyến API phụ trợ mà bạn có thể gọi từ giao diện người dùng của mình.
> 
> nếu bạn cố gắng đặt các mô-đun node.js trong mã trình duyệt/giao diện người dùng, bạn sẽ gặp các lỗi ngẫu nhiên như lỗi này.

@transitive-bullshit  I tried to follow your instructions, but it seems that the conversation is not being recorded. I don't have much experience with nodejs, so please help me. Here is my code.

> router.post('/', async function(req, res, next) {
  var {ChatGPTAPI, ChatGPTUnofficialProxyAPI} = await import("chatgpt")
  const api = new ChatGPTUnofficialProxyAPI({accessToken: "sess-code"});
  const prompt = req.body.prompt;
  const conversationId = req.body.conversationId;
  const parentMessageId = req.body.parentMessageId
  const send = await api.sendMessage(prompt, {
    conversationId: conversationId,
    parentMessageId: parentMessageId
  })
  console.log(send)
  res.json({
    title: send.text,
    parentMessageId: send.parentMessageId,
    conversationId: send.conversationId
  });
});

**Comment by leducgiachoang** [comment]
file:///home/leducgiachoang/Pictures/Screenshots/Screenshot%20from%202023-02-20%2014-08-57.png

**Comment by leducgiachoang** [comment]
> npm 安装了buffer 在main.js中引入了buffer `import * as buffer from "buffer"
> 
> if (typeof (window).global === "undefined"){ (window).global = window; } if (typeof (window).Buffer === "undefined") { (window).Buffer = buffer.Buffer }`
@wzwei1990 
It seems to have worked, but unfortunately it produced another error.

![Screenshot from 2023-02-20 15-14-23](https://user-images.githubusercontent.com/69897727/220049629-cb586bef-300e-4cf4-be42-8cb3271b5839.png)

**Comment by wzwei1990** [comment]
![1676881280434](https://user-images.githubusercontent.com/41670762/220050981-03851369-d460-4ec8-90be-7bafae0b9064.png)
npm 又安装了unfetch 修改了源码替换了fetch

**Comment by leducgiachoang** [comment]
> ![1676881280434](https://user-images.githubusercontent.com/41670762/220050981-03851369-d460-4ec8-90be-7bafae0b9064.png) npm 又安装了unfetch 修改了源码替换了fetch

@wzwei1990 How does it work? I installed it but can't use it. I'm writing with the Vue.js library.

**Comment by leducgiachoang** [comment]
@wzwei1990 
![Screenshot from 2023-02-20 15-58-50](https://user-images.githubusercontent.com/69897727/220059482-57c89306-7995-4fe2-8542-01311736b874.png)

**Comment by wzwei1990** [comment]
> > ![1676881280434](https://user-images.githubusercontent.com/41670762/220050981-03851369-d460-4ec8-90be-7bafae0b9064.png) npm 又安装了unfetch 修改了源码替换了fetch
> 
> @wzwei1990 How does it work? I installed it but can't use it. I'm writing with the Vue.js library.
我用的vue3 需要删除一下.vite文件夹 重新编译

**Comment by transitive-bullshit** [comment]
@leducgiachoang @wzwei1990 none of this code should ever be run on the browser. It is insecure and unsupporteed.

It is only intended to be used from a Node.js server.

**Comment by leducgiachoang** [comment]
> > > ![1676881280434](https://user-images.githubusercontent.com/41670762/220050981-03851369-d460-4ec8-90be-7bafae0b9064.png)npm 又安装了không tìm nạp và không tìm nạp
> > 
> > 
> > @wzwei1990Làm thế nào nó hoạt động? Tôi đã cài đặt nó nhưng không thể sử dụng nó. Tôi đang viết bằng thư viện Vue.js.
> > 我用的vue3 需要删除一下.vite文件夹 重新编译

@wzwei1990 It cannot be added

![Screenshot from 2023-02-20 16-06-24](https://user-images.githubusercontent.com/69897727/220061683-1b17f914-75ad-4f81-806b-ab7653b8cb64.png)

**Comment by leducgiachoang** [comment]
> @leducgiachoang @wzwei1990 none of this code should ever be run on the browser. It is insecure and unsupporteed.
> 
> It is only intended to be used from a Node.js server.

@transitive-bullshit Can you create a similar library for Vuejs?

**Comment by leducgiachoang** [comment]
@transitive-bullshit Please take a look at this simple tool that I have created.: 

[https://chrome.google.com/webstore/detail/chatgpt-extension/dcbcnpnaccfjoikaofjgcipcfbmfkpmj](url)

**Comment by wzwei1990** [comment]
> > @leducgiachoang @wzwei1990 none of this code should ever be run on the browser. It is insecure and unsupporteed.
> > It is only intended to be used from a Node.js server.
> 
> @transitive-bullshit Can you create a similar library for Vuejs?
https://www.npmjs.com/package/unfetch  npm i unfetch 先安装unfetch 再去找chatgpt位置，你应该是找错位置了 我是修改的源码  \node_modules\chatgpt\build\index.js 里面

**Comment by leducgiachoang** [comment]
> > > @leducgiachoang @wzwei1990không mã nào trong số này được chạy trên trình duyệt. Nó không an toàn và không được hỗ trợ. 
> > > Nó chỉ được dự định sử dụng từ máy chủ Node.js.
> > 
> > 
> > @transitive-bullshitBạn có thể tạo một thư viện tương tự cho Vuejs không? 
> > https://www.npmjs.com/package/unfetch   npm i unfetch 先安装unfetch 再去找chatgpt位置，你应该是找错位置了 我是修改的源码 \node_modules\chatgpt\build\index.js 里面

@wzwei1990 This is my code, and it's not working. Can I add you to my git project?

![Screenshot from 2023-02-20 17-25-57](https://user-images.githubusercontent.com/69897727/220079600-c4052b4e-11fe-49d3-b4eb-0584dd0decec.png)

**Comment by transitive-bullshit** [comment]
> > @leducgiachoang @wzwei1990 none of this code should ever be run on the browser. It is insecure and unsupporteed.
> > It is only intended to be used from a Node.js server.
> 
> @transitive-bullshit Can you create a similar library for Vuejs?

This project supports Node.js. You can call it from any frontend framework including Vue.js via an API. You need to host the Node.js API either using a serverless function or on a server somewhere and then call into it from your Vue.js / React / Svelte / JS app.

There is no version of this library which supports Vue.js directly (or any frontend framework) because it is fundamentally meant to only be used from the backend.
