### ISSUE TITLE
UND_ERR_HEADERS_TIMEOUT occurs frequently for long messages

### ISSUE THREAD

**Issue by zouyxdut** [transitive-bullshit/chatgpt-api#370]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node.js 19.6
OS: Ubuntu 20.04

### Describe the Bug

The error is as below:
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undi)
    at async file:///home/xxxxx{
  cause: HeadersTimeoutError: Headers Timeour
      at Timeout.onParserTimeout [as _onTime)
      at listOnTimeout (node:internal/timers)
      at process.processTimers (node:interna{
    code: 'UND_ERR_HEADERS_TIMEOUT'
  }
}

**Comment by transitive-bullshit** [comment]
what's your code for using this package?

**Comment by zouyxdut** [comment]
> what's your code for using this package?

just simply run the `demos/demo.ts`, with long text

**Comment by zouyxdut** [comment]
```ts
async function main() {
  const api = new ChatGPTAPI({ apiKey: process.env.OPENAI_API_KEY })

  const prompt =
    '我想让你充当一位电商卖货主播。我会给你提供商品相关的信息，你将运用各种直播卖货的话术向我介绍这个商品。你的目的是让我购买这个商品，尽可能详细介绍这个商品的优点，但是不能夸大宣传，需要让我感受到这个商品真的对我有用。“商品标题为：【李佳琦直播间】拜年服女童汉服儿童套装过年服喜庆周岁礼服冬装。商品属性为：品牌:西子问\n适用年龄:12个月 18个月 2岁 3岁 4岁 5岁 6岁 7岁 8岁 9岁 10岁 11岁 12岁 13岁 14岁\n面料:涤纶\n图案:其他/other\n产地:中国大陆\n省份:浙江省\n地市:杭州市\n适用性别:女\n模特实拍:实拍有模特\n颜色分类:瑾柠套装 天玥旗袍 满堂套装\n货号:TZ2212011418\n参考身高:100 110 120 130 140 150\n适用季节:冬季\n上市年份季节:2022年冬\n厚薄:厚款\n安全等级:B类\n材质成分:聚酯纤维100%\n。详细介绍：无”。请向我详细介绍这个商品，不要错过任何重要细节，并尽可能让我产生购买意图。'

  const res = await oraPromise(api.sendMessage(prompt,
    {
      timeoutMs: 5 * 60 * 1000
    }), {
    text: prompt
  })
  console.log(res)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})

```

**Comment by transitive-bullshit** [comment]
@zouyxdut I'll test it out tomorrow; ping me if you don't hear back.

In the meantime, you can set `debug: true` in the constructor to see exactly what's being send to the official OpenAI completions API. Also, your 5 minute timeout is generally way too long; I've never seen a response take more than 3 minutes to complete even under heavy load.

**Comment by erhaa233** [comment]
> @zouyxdut I'll test it out tomorrow; ping me if you don't hear back.
> 
> In the meantime, you can set `debug: true` in the constructor to see exactly what's being send to the official OpenAI completions API. Also, your 5 minute timeout is generally way too long; I've never seen a response take more than 3 minutes to complete even under heavy load.

What about the test results?

**Comment by szha381** [comment]
do you  has rate limites per hour for ChatGPTUnofficialProxyAPI ?
 i can only send 72 reqs in 30 minute

**Comment by transitive-bullshit** [comment]
> do you has rate limits per hour for ChatGPTUnofficialProxyAPI ? i can only send 72 reqs in 30 minute

I believe the rate limit for the default proxy right now is 40 / minute (based on IP address).

**Note**: I would strongly recommend only having a single request per ChatGPT account at a time. Avoid concurrent requests and it'll work much better.

**Comment by szha381** [comment]
> > do you has rate limits per hour for ChatGPTUnofficialProxyAPI ? i can only send 72 reqs in 30 minute
> 
> I believe the rate limit for the default proxy right now is 40 / minute (based on IP address).
> 
> **Note**: I would strongly recommend only having a single request per ChatGPT account at a time. Avoid concurrent requests and it'll work much better.

ok, thanks~

**Comment by zouyxdut** [comment]
> > do you has rate limits per hour for ChatGPTUnofficialProxyAPI ? i can only send 72 reqs in 30 minute
> 
> I believe the rate limit for the default proxy right now is 40 / minute (based on IP address).
> 
> **Note**: I would strongly recommend only having a single request per ChatGPT account at a time. Avoid concurrent requests and it'll work much better.

@transitive-bullshit have you test the code? how is your result?

**Comment by acheong08** [comment]
Does this occur before or after some info streams?

**Comment by transitive-bullshit** [comment]
@zouyxdut I believe this was a timeout issue fixed by @acheong08's proxy on his end.

Please let us know if you're still seeing it.
