### ISSUE TITLE
Fetch not defined!

### ISSUE THREAD

**Issue by adiiityaaa** [transitive-bullshit/chatgpt-api#374]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Nodejs 16.19.1

### Describe the Bug

file:///home/container/node_modules/chatgpt/build/index.js:139
      throw new Error("Invalid environment; fetch is not defined");
            ^
Error: Invalid environment; fetch is not defined
    at new ChatGPTAPI (file:///home/container/node_modules/chatgpt/build/index.js:139:13)

![image](https://user-images.githubusercontent.com/77008828/220177129-c0cd7720-8d9b-410e-94ef-c1fb03172134.png)

**Comment by transitive-bullshit** [comment]
@adiiityaaa see the readme section talking about how node >= 18 has `fetch` installed by default but older versions of node you need to install a `fetch` polyfill.
