### ISSUE TITLE
Use error reporting in nest:Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by liyang9331** [transitive-bullshit/chatgpt-api#375]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Use error reporting in nest:Error [ERR_REQUIRE_ESM]: Must use import to load ES Module
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/70904270/220241552-09b447a7-9095-4cc9-a6c9-672a6bae8103.png">

### Describe the Bug

Use error reporting in nest:Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

**Comment by liyang9331** [comment]
Found a solution from the closed issues

**Comment by stefanmaco** [comment]
and the closed issue is...?

**Comment by transitive-bullshit** [comment]
@stefanmaco just use issue search. there are dozens of issues that discuss this, and it's also mentioned in the project's readme if you search for commonjs.

**Comment by rzfzr** [comment]
@liyang9331 and @transitive-bullshit, next time please just reference the issue... 
#31 
Still haven't found a way to work with the unofficial api.
