### ISSUE TITLE
Invalid environment; fetch is not defined

### ISSUE THREAD

**Issue by AloneUtopia** [transitive-bullshit/chatgpt-api#376]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Windows 10
node  v16.19.1

I have installed [fetch](https://github.com/developit/unfetch#usage-as-a-polyfill)

`npm i unfetch`

```
"node_modules/unfetch": {
      "version": "5.0.0",
      "resolved": "https://registry.npmjs.org/unfetch/-/unfetch-5.0.0.tgz",
      "integrity": "sha512-3xM2c89siXg0nHvlmYsQ2zkLASvVMBisZm5lF3gFDqfF2xonNStDJyMpvaOBe0a1Edxmqrf2E0HBdmy9QyZaeg=="
    }
```

I have read the closed issue [Fetch not defined!](https://github.com/transitive-bullshit/chatgpt-api/issues/374) ,but I still don't understand...

### Describe the Bug

```shell
$ npx tsx demos/demo.ts
d:\WWW\chatgpt-api\src\chatgpt-api.ts:152
      throw new Error('Invalid environment; fetch is not defined')
            ^

Error: Invalid environment; fetch is not defined
    at ChatGPTAPI (d:\WWW\chatgpt-api\src\chatgpt-api.ts:152:13)
    at main (d:\WWW\chatgpt-api\demos\demo.ts:16:15)
    at <anonymous> (d:\WWW\chatgpt-api\demos\demo.ts:27:1)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

**Comment by liyang9331** [comment]
metoo

**Comment by AloneUtopia** [comment]
> 
My problem seems to be solved.

I installed isomorphic-fetch；
And in `fetch.ts`

```
/// <reference lib="dom" />

//const fetch = globalThis.fetch
import fetch from 'isomorphic-fetch'

export { fetch }
```

**Comment by transitive-bullshit** [comment]
The readme gives instructions for this; if you're using node < 18, you need to install a `fetch` polyfill. If you're using node >= 18, `fetch` is installed by default.

**Comment by liyang9331** [comment]
> The readme gives instructions for this; if you're using node < 18, you need to install a `fetch` polyfill. If you're using node >= 18, `fetch` is installed by default.



> The readme gives instructions for this; if you're using node < 18, you need to install a `fetch` polyfill. If you're using node >= 18, `fetch` is installed by default.

I installed and used it in the netjs project through npm. The global node-match and the netjs project node-match have been installed, but I still prompt:Error: Invalid environment; fetch is not defined

**Comment by transitive-bullshit** [comment]
@liyang9331 I'm not sure what `node-match` is but it has nothing to do with `fetch`.

**Comment by brinkqiang** [comment]
> 

Both unfetch and node-fetch didn't work for me, but your previous solution worked.

**Comment by brinkqiang** [comment]
> > 
> 
> 我的问题似乎解决了。
> 
> 我安装了isomorphic-fetch； 而在`fetch.ts`
> 
> ```
> /// <reference lib="dom" />
> 
> //const fetch = globalThis.fetch
> import fetch from 'isomorphic-fetch'
> 
> export { fetch }
> ```

Both unfetch and node-fetch didn't work for me, but your previous solution worked.

**Comment by unitario** [comment]
> The readme gives instructions for this; if you're using node < 18, you need to install a `fetch` polyfill. If you're using node >= 18, `fetch` is installed by default.

He has already installed unfetch (as per documentation) and is till getting this error.

**Comment by hqzhon** [comment]
My problem  solved by this way.

You can refer to this code : [[fix "fetch is not defined"](https://github.com/transitive-bullshit/chatgpt-api/compare/main...hqzhon:chatgpt-api:main)]

or you can try my other extension [[chatgpt-vscode](https://www.npmjs.com/package/chatgpt-vscode)]
