### ISSUE TITLE
Can you add a method to dynamically set apiKey?

### ISSUE THREAD

**Issue by HttpStatusError** [transitive-bullshit/chatgpt-api#377]
### Describe the feature

Now, the apiKey can only be set when the client is created. When the balance of the apiKey is exhausted, I cannot dynamically change the apiKey, but can only re-create the client. The relevant context disappears after the client is recreated.

e.g.
```js
const client = new ChatGPTAPI()
client .setApiKey('sk-example')
client .sendMessage(...)
````

I'm not a professional front-end developer. I don't know whether this is reasonable, but I still hope that there will be relevant functions to be implemented. Thank you!

**Comment by transitive-bullshit** [comment]
This sounds reasonable. Will add it now.

> The relevant context disappears after the client is recreated.

I'd recommend using a persistent data store to store your messages so this won't be a problem.

**Comment by transitive-bullshit** [comment]
@HttpStatusError actually it looks like this is already supported.

`client.apiKey = 'xk-...`

**Comment by sam-hieken** [comment]
@transitive-bullshit I had to set both the apiKey and _accessToken properties in order for my token to change during the requests.
