### ISSUE TITLE
ChatGPT error 500, type: auth_subrequest_error

### ISSUE THREAD

**Issue by ddkwing** [transitive-bullshit/chatgpt-api#378]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

npx tsx demos/demo.ts

### Describe the Bug

✖ Write a python version of bubble sort. Do not include example usage.
ChatGPTError: ChatGPT error 500: {
    "error": {
        "message": "Internal server error",
        "type": "auth_subrequest_error",
        "param": null,
        "code": "internal_error"
    }
}

    at <anonymous> (....../src/chatgpt-api.ts:295:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5

**Comment by AloneUtopia** [comment]
I just had this problem. It's ok at noon today

**Comment by ddkwing** [comment]
> 

😄How did you solve it? It recovery by it self?

**Comment by transitive-bullshit** [comment]
Hmmm never seen this before.

What version of node.js are you using and on what platform?

A 5XX error means that it's a problem with OpenAI's API. They do occasionally have scaling issues.

**Comment by transitive-bullshit** [comment]
Update: this is apparently an outage with the official OpenAI API, and they are working to resolve the problem.

Details: https://status.openai.com/incidents/mq5jgswy45fr

**Comment by iSonce** [comment]
> I just had this problem. It's ok at noon today

Same as you

**Comment by navopw** [comment]
Can confirm this error, also got this right now.

**Comment by ddkwing** [comment]
> Update: this is apparently an outage with the official OpenAI API, and they are working to resolve the problem.
> 
> Details: https://status.openai.com/incidents/mq5jgswy45fr

Thank you so much. maybe now just wait for them to sort it out 😂

**Comment by iSonce** [comment]
> **Update**: this is apparently an outage with the official OpenAI API, and they are working to resolve the problem.
> 
> Details: https://status.openai.com/incidents/mq5jgswy45fr

Thank you!

**Comment by MukundDaolens** [comment]
Getting the same error

**Comment by LearnerForever** [comment]
> **Update**: this is apparently an outage with the official OpenAI API, and they are working to resolve the problem.
> 
> Details: https://status.openai.com/incidents/mq5jgswy45fr

Thank you so much, I just tried again and again checking my code like a fool... until this light illuminate my mind...

**Comment by transitive-bullshit** [comment]
Looks like OpenIA's servers are back up: https://status.openai.com/incidents/mq5jgswy45fr

There may be some intermittent issues as they roll out the fix, but there's not much we can do about that from our end.

Thanks 🙏

**Comment by kaltoIacono** [comment]
I was able to reproduce again

openai.error.APIError: Internal server error {
    "error": {
        "message": "Internal server error",
        "type": "auth_subrequest_error",
        "param": null,
        "code": "internal_error"
    }
}

**Comment by kaltoIacono** [comment]
openai/api_requestor.py", line 655, in _interpret_response_line
    raise self.handle_error_response

**Comment by transitive-bullshit** [comment]
@kaltoIacono this will happen sometimes when OpenAI's API is having issues. It is usually brief and out of our control.

Also, the example you posted is for python, which is not this lib.
