### ISSUE TITLE
After yesterday's massive Openai outage, ChatGPTUnofficialProxyAPI is no longer available

### ISSUE THREAD

**Issue by SchneeHertz** [transitive-bullshit/chatgpt-api#381]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node 18
window 10 22H2

### Describe the Bug

After yesterday's massive Openai outage, ChatGPTUnofficialProxyAPI is no longer available and keeps timing out after calling sendmessage.

**Comment by transitive-bullshit** [comment]
Hey @SchneeHertz, thanks for the report.

I know there are still some lingering OpenAI server issues that may be affecting things, but as far as I'm aware, the proxy method is still working in general.

The best place to discuss the proxy method and get help for this would be on our [discord](https://discord.gg/v9gERj825w).

Sorry I don't have any more specific help I can give atm.

**Comment by SchneeHertz** [comment]
I used Postman to make a request directly to the reverse proxy and was able to receive the correct response
![](https://p.sda1.dev/10/63b0051c24b43bc4955b3bc916a0f565/Snipaste_2023-02-22_09-46-47.jpg)

**Comment by SchneeHertz** [comment]
I found the reason, I was using the wrong conversation_id, sorry to bother you
