### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by wayward-man** [transitive-bullshit/chatgpt-api#386]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

const chatgpt_1 = require("chatgpt");

Error [ERR_REQUIRE_ESM]: require() of ES Module

How should I do ？

### Describe the Bug

none

**Comment by transitive-bullshit** [comment]
Please search existing issues; there are many replies already :) the readme has a section on "commonjs" as well.

Cheers 😄

**Comment by shanurrahmanpenny** [comment]
Well there is a better solution than using dynamic imports
```
nvm ls
       v16.18.1
->     v18.15.0
default -> 18.15 (-> v18.15.0)
```
---
tsconfig.json
```
{
  "compilerOptions": {
    "module": "ES2022",
    "moduleResolution": "nodenext",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}
```

and in package.json add this entry
"type": "module",
<img width="783" alt="Screen Shot 2023-03-15 at 10 41 53 PM" src="https://user-images.githubusercontent.com/103241318/225424670-147c4d3c-d518-4c10-a259-2bf5577f85fc.png">

After this you need to update imports to use  file extensions like this
```ts
import { User } from './schema/user.schema.js';
```
