### ISSUE TITLE
conversationId does not work in in some cases

### ISSUE THREAD

**Issue by CYBYOB** [transitive-bullshit/chatgpt-api#392]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node.js v14.17.0.
chatgpt ^4.7.2
macOS Monterey 12.0.1

### Describe the Bug

It works in the following code：
```js
try {
    const api = new ChatGPTAPI({
        apiKey,
    });
    const body: IChatGPTBody = req.body;
    // TODO 过滤假值，函数封装
    if (!body.parentMessageId) {
        delete body.parentMessageId;
    }
    if (!body.conversationId) {
        delete body.conversationId;
    }

    const data1 = await api.sendMessage(`Write a quicksort algorithm in JavaScript.`, body);
    const data2 = await api.sendMessage(
        `Change the programming language to go`,
        { conversationId: data1.conversationId, parentMessageId: data1.parentMessageId }
    );
    res.status(200).json({
        data1: { ...data1, body: { conversationId: body.conversationId, parentMessageId: body.parentMessageId }},
        data2: { ...data2, body: { conversationId: data1.conversationId, parentMessageId: data1.parentMessageId } }
    });
} catch (error) {
    res.status(500).json(error);
}
```

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/32217093/221334513-970bd80e-2979-41bb-9adb-4ee05644b905.png">

But it  does not works in the following code：
```js
try {
    const api = new ChatGPTAPI({
        apiKey,
    });
    const body: IChatGPTBody = req.body;
    // TODO 过滤假值，函数封装
    if (!body.parentMessageId) {
        delete body.parentMessageId;
    }
    if (!body.conversationId) {
        delete body.conversationId;
    }
    const data = await api.sendMessage(
        `${message}`,
        { conversationId: body.conversationId, parentMessageId: body.parentMessageId }
    );
    res.status(200).json({...data, body: { conversationId: body.conversationId, parentMessageId: body.parentMessageId }});
} catch (error) {
    res.status(500).json(error);
}
```
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/32217093/221334599-e884da42-b850-43f9-9633-92ab9d8f65b2.png">

<img width="899" alt="image" src="https://user-images.githubusercontent.com/32217093/221334644-29d3e992-942b-4c1a-8114-99b399ca5348.png">

**Comment by qianzhiyuan** [comment]
I also encountered this problem

**Comment by CYBYOB** [comment]
> I also encountered this problem

I'm running out of ideas to fix this issue~  Someone can help us solve this problem~

**Comment by transitive-bullshit** [comment]
@CYBYOB your example is using `ChatGPTAPI`, which does not use the official ChatGPT servers.

For `ChatGPTAPI, your `conversationId` and `parentMessageId` are completely local. By default, these previous messages are stored in memory, but if you want them to persist beyond the Node.js process, you need to store them using a persistent `keyv` store. The readme has an example of how to do this.

The other option is to use `ChatGPTUnofficialProxyAPI`, which uses the real ChatGPT servers and all messages are stored there.

**Comment by CYBYOB** [comment]
> @CYBYOB your example is using `ChatGPTAPI`, which does not use the official ChatGPT servers.
> 
> For `ChatGPTAPI`, your `conversationId` and `parentMessageId` are completely local. By default, these previous messages are stored in memory, but if you want them to persist beyond the Node.js process, you need to store them using a persistent `keyv` store. The readme has an example of how to do this.
> 
> The other option is to use `ChatGPTUnofficialProxyAPI`, which uses the real ChatGPT servers and all messages are stored there.

Thank you very much.I will try it tonight~
