### ISSUE TITLE
ChatGPTUnofficialProxyAPI errors

### ISSUE THREAD

**Issue by CYBYOB** [transitive-bullshit/chatgpt-api#395]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node.js v14.17.0.
chatgpt ^4.7.2
macOS Monterey 12.0.1

### Describe the Bug

It does not works in the following code：
```js
try {
    const api = new ChatGPTUnofficialProxyAPI({
        debug: true,
        // got it by link https://chat.openai.com/api/auth/session
        accessToken,
        // https://chat.duti.tech/api/conversation or https://gpt.pawan.krd/backend-api/conversation
        apiReverseProxyUrl,
    });
    const prompt = 'Write a poem about cats.'

    rsp = await oraPromise(api.sendMessage(prompt), {
        text: prompt
    }) as any;

    res.status(200).json({ rsp });
} catch (error) {
    res.status(500).json({ error });
}
```

It doesn't return useful information：
<img width="592" alt="image" src="https://user-images.githubusercontent.com/32217093/221334109-28e4423b-391b-414b-aab1-e69ac07592f1.png">

**Comment by transitive-bullshit** [comment]
@CYBYOB are you running this in Node.js with a debugger attached, or is this screenshot from the browser?

If it's from the browser, that behavior is undefined.

If it's from Node.js, these proxies are run by community members and they appear to be working fine for others. If you're having problems getting the proxy approach to work, please ask follow-up questions in our [discord](https://discord.gg/v9gERj825w), where the devs who run these servers hang out.

Also, I'd highly recommend upgrading to at least `node` 18.
