### ISSUE TITLE
Is there any other available server besides the two reverse proxy servers listed in the readme?

### ISSUE THREAD

**Issue by huluohu** [transitive-bullshit/chatgpt-api#401]
### Describe the feature

Is there any other available server besides the two reverse proxy servers listed in the readme?

**Comment by transitive-bullshit** [comment]
Not at the moment.

What are you seeing that isn't working for you?

**Comment by karl32** [comment]
Hi, till yesterday all my scripts were working fine. But from today im experiencing timeout issue: TimeoutError: ChatGPT timed out waiting for response
My timeout is set to 6 minutes which was enough till yesterday.  Im trying to use both proxy but both returning a timeout..

**Comment by huluohu** [comment]
> 

**Currently, these two often encounter the following errors.**
- {"cause":{"name":"ConnectTimeoutError","code":"UND_ERR_CONNECT_TIMEOUT","message":"Connect Timeout Error"}}
- {"statusCode":504,"statusText":"Gateway Time-out"}

**Comment by transitive-bullshit** [comment]
Maybe ask on our [discord server](https://discord.gg/v9gERj825w)?

**Comment by karl32** [comment]
Till yesterday the first one was working fine. From today it returns TimeouError. The second returns TypeError: fetch failed..

**Comment by karl32** [comment]
> Maybe ask on our [discord server](https://discord.gg/v9gERj825w)?

Already did. In the node-help section...waiting for the answer..

**Comment by acheong08** [comment]
Cloudflare might be blocked in China or other countries. Try using a proxy or VPN

**Comment by karl32** [comment]
Im in Europe. Cloudflare is not blocked here..

**Comment by acheong08** [comment]
Server is definitely running and under pretty low load. Maybe it's an issue with OpenAI

**Comment by karl32** [comment]
Its working now. Thanks all for you help.
