### ISSUE TITLE
_tiktoken_bg.wasm file not found?

### ISSUE THREAD

**Issue by NoodleOfDeath** [transitive-bullshit/chatgpt-api#402]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

I am building using esbuild and docker esnext module. This was not an issue before and just started being an issue today. My last successful build was 15 hours ago

### Describe the Bug

i am getting an ENOENT error looking for a _tiktoken_bg.wasm file... this causes my container to continually fatally crash. im guessing it is because the dep version for tiktoken out of date?

**Comment by NoodleOfDeath** [comment]
i had to manually add copy the wasm file into the build dir in my docker image :(

**Comment by transitive-bullshit** [comment]
Linking this to https://github.com/dqbd/tiktoken/issues/6

We recently switched to using [@dqbd/tiktoken](https://github.com/dqbd/tiktoken), which is a rust wasm port of openai's official tiktoken implementation. Looks like there were some unexpected consequences.

**Comment by transitive-bullshit** [comment]
@NoodleOfDeath thanks for your PR 🙏  https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.8.2

I did a comparison of the various tokenizer packages before making this switch btw: https://github.com/transitive-bullshit/compare-tokenizers

We may have to revert to the JS-only version of the tokenizer logic if it's causing too many issues.

**Comment by NoodleOfDeath** [comment]
You're a champ! Loving this lib though. Using it to power my new news outlet web app!
