### ISSUE TITLE
504 Gateway Time Out

### ISSUE THREAD

**Issue by KevinKaiwenZheng** [transitive-bullshit/chatgpt-api#408]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node JS 18+

### Describe the Bug

Like for my requests, nearly half of them are 504 time out. The following is the output

```
  at fetchSSE (file:///root/PathfinderxHFI/node_modules/chatgpt/build/index.js:52:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 504,
  statusText: 'Gateway Time-out',
  [cause]: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 504,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Gateway Time-out',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}
```

**Comment by transitive-bullshit** [comment]
This happens from time to time when using the unofficial API.

If you want a more robust API, switch to using the official version in https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v5.0.0
