### ISSUE TITLE
When i used the 'gpt-3.5-turbo'  model, I got this error.

### ISSUE THREAD

**Issue by gefeiyanga** [transitive-bullshit/chatgpt-api#411]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node: 18.10.0
chatgpt: lastest

### Describe the Bug

<img width="827" alt="image" src="https://user-images.githubusercontent.com/30728843/222306517-1a773793-9839-42ca-8e90-be1049b43495.png">

**Comment by gefeiyanga** [comment]
I configured like this: 
[OpenAI official doc](https://platform.openai.com/docs/api-reference/completions/create)
```
const api = new ChatGPTAPI({
      apiKey: process.env.OPENAI_API_KEY,
      debug: true,
      apiReverseProxyUrl: 'https://api.openai.com/v1/chat/completions', 
      completionParams: {
        model: 'gpt-3.5-turbo',
      },
    });
```

**Comment by transitive-bullshit** [comment]
I'm working on better support for the official API right now. Expect a release soon.

**Comment by gefeiyanga** [comment]
> I'm working on better support for the official API right now. Expect a release soon.

ok, thanks.

**Comment by transitive-bullshit** [comment]
Please see the updated release, which now has full support for the official API: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v5.0.0

**Comment by egorlas1996** [comment]
> I'm working on better support for the official API right now. Expect a release soon.

When i check your code, in gpt-3.5-turbo change path url from "/v1/completions" to "/v1/chat/completions" and add "messages" field to body request. Hope thing that help you, thank!

**Comment by gefeiyanga** [comment]
> Please see the updated release, which now has full support for the official API: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v5.0.0

The new model is functioning properly, but it still lacks the level of intelligence exhibited by the official website. How do you feel about it?
