### ISSUE TITLE
Cannot find module 'openai'

### ISSUE THREAD

**Issue by saidattax** [transitive-bullshit/chatgpt-api#414]
### Environment details

Node: v18.12.1
chatgpt: ^5.0.1

### Describe the Bug

I'm unable to build a typescript node server. 

Getting a build error

```
yarn run v1.22.19
$ tsc
node_modules/chatgpt/build/index.d.ts:2:25 - error TS2307: Cannot find module 'openai' or its corresponding type declarations.

2 import * as openai from 'openai';
                          ~~~~~~~~


Found 1 error in node_modules/chatgpt/build/index.d.ts:2

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by transitive-bullshit** [comment]
Thanks @saidattax; I had assumed the types would get bundled, but it doesn't look like that was the case.

I just pushed a fix in https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v5.0.3

Plese let me know if that fixes the issue for you.
