### ISSUE TITLE
Can't resolve '@dqbd/tiktoken'

### ISSUE THREAD

**Issue by Leeero** [transitive-bullshit/chatgpt-api#417]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node:v16.13.2
chatgpt:5.0.4

### Describe the Bug

Compiled with problems:X
ERROR in ./node_modules/chatgpt/build/index.js 8:0-52
Module not found: Error: Can't resolve '@dqbd/tiktoken' in '....../node_modules/chatgpt/build'

**Comment by transitive-bullshit** [comment]
@Leeero thanks for the report.

We recently switched tokenizers to a rust/wasm port of openai's official tiktoken tokenizer, after doing some comparison analysis here: https://github.com/transitive-bullshit/compare-tokenizers

Can you give me some more info on how you're using the `chatgpt` package and what your build / toolchain looks like? Also, what package manager and version are you using?

This in in reference to this dep btw: https://github.com/dqbd/tiktoken

**Comment by Leeero** [comment]
> @Leeero thanks for the report.
> 
> We recently switched tokenizers to a rust/wasm port of openai's official tiktoken tokenizer, after doing some comparison analysis here: https://github.com/transitive-bullshit/compare-tokenizers
> 
> Can you give me some more info on how you're using the `chatgpt` package and what your build / toolchain looks like? Also, what package manager and version are you using?
> 
> This in in reference to this dep btw: https://github.com/dqbd/tiktoken

Thanks Reply。
I created the project using create-react-app, and introduced the antd component library, and did not use any other dependencies.
npm: 6.14.8

**Comment by transitive-bullshit** [comment]
@Leeero make sure that you're only using `chatgpt` from backend node.js code. All of the JS code in `create-react-app` by default is targeting the browser, which will not work with this package since it is node.js-only.

Also, I would consider switching from `create-react-app` to [vite](https://vitejs.dev/) or another build tool, since CRA isn't very well maintained at this point: https://transitivebullsh.it/javascript-dev-tools-in-2022

**Comment by Leeero** [comment]
> @Leeero make sure that you're only using `chatgpt` from backend node.js code. All of the JS code in `create-react-app` by default is targeting the browser, which will not work with this package since it is node.js-only.
> 
> Also, I would consider switching from `create-react-app` to [vite](https://vitejs.dev/) or another build tool, since CRA isn't very well maintained at this point: https://transitivebullsh.it/javascript-dev-tools-in-2022

Ok, I see, thank you very much.

**Comment by skychavda** [comment]
I installed `chatgpt-api` into my react project but it is giving me same error.

Is there any solution?
