### ISSUE TITLE
Minor first install issues

### ISSUE THREAD

**Issue by markNZed** [transitive-bullshit/chatgpt-api#418]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node -v v18.14.1
Ubuntu 22.04

### Describe the Bug

Running: npx tsx demos/demo.ts
Cannot find package 'dotenv-safe' imported 
Fix: npm install dotenv 

Running: npx tsx demos/demo-persistence.ts
Error: connect ECONNREFUSED 127.0.0.1:6379
Fix: sudo apt-get install redis-server

Maybe this could be mentioned in the README

**Comment by transitive-bullshit** [comment]
Thanks @markNZed; will take this feedback into consideration.
