### ISSUE TITLE
fetch failed (OpenAI API banned in certain countries like China)

### ISSUE THREAD

**Issue by TyCoding** [transitive-bullshit/chatgpt-api#419]
### Describe the feature

api request error 

fetch failed

**Comment by iAqu** [comment]
same error

**Comment by iSonce** [comment]
same error, error message: "fetch failed"

**Comment by Charhua** [comment]
same error

**Comment by transitive-bullshit** [comment]
Can you please provide more details on the error you're seeing, including some code snippets for how you're using this package?

This error could mean almost anything, and I won't be able to help without more info.

**Comment by ws02589111** [comment]
> Can you please provide more details on the error you're seeing, including some code snippets for how you're using this package?
> 
> This error could mean almost anything, and I won't be able to help without more info.

{"err":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:11118:11)\n    at <anonymous> (/app/node_modules/chatgpt/build/index.js:262:25)"}

**Comment by gefeiyanga** [comment]
> > Can you please provide more details on the error you're seeing, including some code snippets for how you're using this package?
> > This error could mean almost anything, and I won't be able to help without more info.
> 
> {"err":"TypeError: fetch failed\n at Object.fetch (node:internal/deps/undici/undici:11118:11)\n at (/app/node_modules/chatgpt/build/index.js:262:25)"}
好像是中国地区ip被ban了，大家报错的都是在国内吗？

**Comment by ws02589111** [comment]
> > > Can you please provide more details on the error you're seeing, including some code snippets for how you're using this package?
> > > This error could mean almost anything, and I won't be able to help without more info.
> > 
> > 
> > {"err":"TypeError: fetch failed\n at Object.fetch (node:internal/deps/undici/undici:11118:11)\n at (/app/node_modules/chatgpt/build/index.js:262:25)"}
> > 好像是中国地区ip被ban了，大家报错的都是在国内吗？

The http api is worked

**Comment by transitive-bullshit** [comment]
Can you paste the full JS/TS code that you're using to call `ChatGPTAPI`?

Also, which Node.js version are you using?

**Comment by Charhua** [comment]
> > > 您能否提供有关您看到的错误的更多详细信息，包括您如何使用此软件包的一些代码片段？此错误可能意味着几乎任何事情，如果没有更多信息，我将无法提供帮助。
> > 
> > 
> > {“err”：“TypeError： fetch failed\n at Object.fetch （node：internal/deps/undici/undici：11118：11）\n at （/app/node_modules/chatgpt/build/index.js：262：25）”} 好像是中国地区ip被ban了，大家报错的都是在国内吗？

yes

**Comment by ws02589111** [comment]
> > > Can you please provide more details on the error you're seeing, including some code snippets for how you're using this package?
> > > This error could mean almost anything, and I won't be able to help without more info.
> > 
> > 
> > {"err":"TypeError: fetch failed\n at Object.fetch (node:internal/deps/undici/undici:11118:11)\n at (/app/node_modules/chatgpt/build/index.js:262:25)"}
> > 好像是中国地区ip被ban了，大家报错的都是在国内吗？

Sorry，maybe this is really true

**Comment by ZoeLeee** [comment]
same error
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11118:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/lizhou/projects/chatgpt/node_modules/chatgpt/build/index.js:265:25 {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:6625:28)
      at node:internal/deps/undici/undici:6583:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:6614:13)
      at process.processImmediate (node:internal/timers:471:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
```

**Comment by transitive-bullshit** [comment]
Yes, **I believe that IP addresses in China are banned from calling the OpenAI API.**

If you have this problem, you have a few workarounds:

1. Use a proxy and pass a custom `fetch` to the `ChatGPTAPI` constructor which uses you proxy. Note: you'll still need a valid OpenAI API key from their website.
2. Using a VPN might solve your problem, depending on how aggressive the firewall is.
3. Use `ChatGPTUnofficialProxyAPI` instead of `ChatGPTAPI`, which may not have the same IP bans.

**Comment by Kylin93CN** [comment]
axios has  the "proxy" function, but chatGPTAPI use the 'origin fetch'  TAT

**Comment by iSonce** [comment]
> 

Thanks for your help!

**Comment by iSonce** [comment]
> Yes, **I believe that IP addresses in China are banned from calling the OpenAI API.**
> 
> If you have this problem, you have a few workarounds:
> 
> 1. Use a proxy and pass a custom `fetch` to the `ChatGPTAPI` constructor which uses you proxy. Note: you'll still need a valid OpenAI API key from their website.
> 2. Using a VPN might solve your problem, depending on how aggressive the firewall is.
> 3. Use `ChatGPTUnofficialProxyAPI` instead of `ChatGPTAPI`, which may not have the same IP bans.

Thanks for your help!

**Comment by Charhua** [comment]
> Yes, **I believe that IP addresses in China are banned from calling the OpenAI API.**
> 
> If you have this problem, you have a few workarounds:
> 
> 1. Use a proxy and pass a custom  to the  constructor which uses you proxy. Note: you'll still need a valid OpenAI API key from their website.`fetch``ChatGPTAPI`
> 2. Using a VPN might solve your problem, depending on how aggressive the firewall is.
> 3. Use  instead of , which may not have the same IP bans.`ChatGPTUnofficialProxyAPI``ChatGPTAPI`

Thanks

**Comment by huluohu** [comment]
> 

Can you add a proxy option in ChatGPTAPI, please?

**Comment by ws02589111** [comment]
> > 
> 
> Can you add a proxy option in ChatGPTAPI, please?

This code can help you 
```
npm install https-proxy-agent node-fetch
const api = new ChatGPTAPI({
  fetch: (url, options = {}) => {
        const defaultOptions = {
            agent: require('https-proxy-agent')('http://your-proxy-address:port')
        };

        const mergedOptions = {
            ...defaultOptions,
            ...options
        };

        return require('node-fetch').default(url, mergedOptions);
    }
})
```

**Comment by huluohu** [comment]
> > > 
> > 
> > 
> > Can you add a proxy option in ChatGPTAPI, please?
> 
> This code can help you
> 
> ```
> npm install https-proxy-agent node-fetch
> ```
> 
> ```
> const api = new ChatGPTAPI({
>   fetch: (url, options = {}) => {
>         const defaultOptions = {
>             agent: require('https-proxy-agent')('http://your-proxy-address:port')
>         };
> 
>         const mergedOptions = {
>             ...defaultOptions,
>             ...options
>         };
> 
>         return require('node-fetch').default(url, mergedOptions);
>     }
> })
> ```

ok, i'm try ,Thank you!

**Comment by Get-wy** [comment]
> 同样的错误
> 
> ```
> TypeError: fetch failed
>     at Object.fetch (node:internal/deps/undici/undici:11118:11)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async file:///home/lizhou/projects/chatgpt/node_modules/chatgpt/build/index.js:265:25 {
>   cause: ConnectTimeoutError: Connect Timeout Error
>       at onConnectTimeout (node:internal/deps/undici/undici:6625:28)
>       at node:internal/deps/undici/undici:6583:50
>       at Immediate._onImmediate (node:internal/deps/undici/undici:6614:13)
>       at process.processImmediate (node:internal/timers:471:21) {
>     code: 'UND_ERR_CONNECT_TIMEOUT'
>   }
> }
> ```

Yes, I encountered the same mistake. My project has been put into operation in production

**Comment by Get-wy** [comment]
> Yes, **I believe that IP addresses in China are banned from calling the OpenAI API.**
> 
> If you have this problem, you have a few workarounds:
> 
> 1. Use a proxy and pass a custom `fetch` to the `ChatGPTAPI` constructor which uses you proxy. Note: you'll still need a valid OpenAI API key from their website.
> 2. Using a VPN might solve your problem, depending on how aggressive the firewall is.
> 3. Use `ChatGPTUnofficialProxyAPI` instead of `ChatGPTAPI`, which may not have the same IP bans.

Using ` ChatGPTUnofficialProxyAPI ` also can not in China

**Comment by gefeiyanga** [comment]
![image](https://user-images.githubusercontent.com/30728843/222612368-d8ba7391-9c0c-41e4-a1dd-971ba5166494.png)
<img width="728" alt="image" src="https://user-images.githubusercontent.com/30728843/222612477-d030c548-b008-49cf-b907-d4a81df4af3d.png">


I can get result by using curl, but also fetch failed.

**Comment by mamahui** [comment]
> you

i tryed but i'm not fine . please help me check the code thanks
`const api = new ChatGPTAPI({
  apiKey,
  fetch: (url, options = {}) => {
    const defaultOptions = {
      agent: require('https-proxy-agent')('http://127.0.0.1:8899')
    };
    
    const mergedOptions = {
      ...defaultOptions,
      ...options
    };
    
    return require('node-fetch').default(url, mergedOptions);
  }
});`

**Comment by mamahui** [comment]
> ok, i tried， but i'm fialed;

this is my code   please help me check this code  thanks;

const api = new ChatGPTAPI({
  apiKey,
  fetch: (url, options = {}) => {
    const defaultOptions = {
      agent: require('https-proxy-agent')('http://127.0.0.1:8899')
    };
    
    const mergedOptions = {
      ...defaultOptions,
      ...options
    };
    
    return require('node-fetch').default(url, mergedOptions);
  }
});

**Comment by mamahui** [comment]
sorry to ask ; but i really want to know how to get the  'http://your-proxy-address:port'   thanks

**Comment by brooklynb7** [comment]
This works for me. 
Thanks all guys!

```
import { ChatGPTAPI } from "chatgpt";
import proxy from "https-proxy-agent";
import nodeFetch from "node-fetch";

async function example() {
  const api = new ChatGPTAPI({
    apiKey: process.env.OPENAI_API_KEY || "",
    fetch: (url, options = {}) => {
      const defaultOptions = {
        agent: proxy("http://proxy"),
      };

      const mergedOptions = {
        ...defaultOptions,
        ...options,
      };

      return nodeFetch(url, mergedOptions);
    },
  });

  const res = await api.sendMessage("Hello World!");
  console.log(res.text);
}
```

**Comment by mamahui** [comment]
" http://proxy" this address get from where  thanks

**Comment by gefeiyanga** [comment]
> " http://proxy" this address get from where thanks

Such as http://127.0.0.1:1234 
It is your Proxy address.

**Comment by gefeiyanga** [comment]
But I got 'Error: OpenAI error 503' sometimes.

**Comment by mamahui** [comment]
> 

i set this. but get no replay from openAI

**Comment by huluohu** [comment]
> 

It's Work

**Comment by huluohu** [comment]
`const keyChat = new ChatGPTAPI({
    apiKey: process.env.OPENAI_API_KEY || "",
    debug: chatDebug,
    fetch: openaiProxy ? (url, options = {}) => {
        const defaultOptions = {
            agent: require('https-proxy-agent')(openaiProxy)
        };

        const mergedOptions = {
            ...defaultOptions,
            ...options
        };

        return require('node-fetch').default(url, mergedOptions);
    } : fetch
})
`
The proxy configuration can be set to `optional `

**Comment by mamahui** [comment]
> ```js
> openaiProxy
> ```

hey , I want to get openaiProxy how can i get it

**Comment by huluohu** [comment]
> > 
> 
> this address is my server ip address?

Of course

**Comment by BigBroFinch** [comment]
same error

**Comment by transitive-bullshit** [comment]
If you're looking for a proxy, check out https://www.webshare.io

**Comment by xmenbe** [comment]
There is no reliable mainland agent recommended

**Comment by cuicui-V5** [comment]
> This works for me. Thanks all guys!
> 
> ```js
> import { ChatGPTAPI } from "chatgpt";
> import proxy from "https-proxy-agent";
> import nodeFetch from "node-fetch";
> 
> async function example() {
>   const api = new ChatGPTAPI({
>     apiKey: process.env.OPENAI_API_KEY || "",
>     fetch: (url, options = {}) => {
>       const defaultOptions = {
>         agent: proxy("http://proxy"),
>       };
> 
>       const mergedOptions = {
>         ...defaultOptions,
>         ...options,
>       };
> 
>       return nodeFetch(url, mergedOptions);
>     },
>   });
> 
>   const res = await api.sendMessage("Hello World!");
>   console.log(res.text);
> }
> ```

sad , It's not work for me , fxxk gfw
```
FetchError: request to https://api.openai.com/v1/chat/completions failed, reason: Client network socket disconnected before secure TLS connection was established
```

**Comment by Song-Mao** [comment]
> 但我有时会收到“错误：OpenAI 错误 503”。



> 同样的错误，直接使用http api是可行的

I also encountered the same problem when I started the local service using node. Starting the global proxy can be called normally in the browser, but starting the local service using node will time out. Have you solved it?

**Comment by cuicui-V5** [comment]
> 

not yet . 
Maybe we need a transparent proxy, consider a software router.

**Comment by ws02589111** [comment]
> > This works for me. Thanks all guys!
> > ```js
> > import { ChatGPTAPI } from "chatgpt";
> > import proxy from "https-proxy-agent";
> > import nodeFetch from "node-fetch";
> > 
> > async function example() {
> >   const api = new ChatGPTAPI({
> >     apiKey: process.env.OPENAI_API_KEY || "",
> >     fetch: (url, options = {}) => {
> >       const defaultOptions = {
> >         agent: proxy("http://proxy"),
> >       };
> > 
> >       const mergedOptions = {
> >         ...defaultOptions,
> >         ...options,
> >       };
> > 
> >       return nodeFetch(url, mergedOptions);
> >     },
> >   });
> > 
> >   const res = await api.sendMessage("Hello World!");
> >   console.log(res.text);
> > }
> > ```
> 
> sad , It's not work for me , fxxk gfw
> 
> ```
> FetchError: request to https://api.openai.com/v1/chat/completions failed, reason: Client network socket disconnected before secure TLS connection was established
> ```

I had the same issue when I tested， it's because of my proxy is socks5 and http type in different env.
So， you can try `socks-proxy-agent` instead of `https-proxy-agent`

**Comment by chengfengfengwang** [comment]
How to add a proxy when directly running at the CLI, like "npx chatgpt 'your prompt here'"?

**Comment by luuziiyoo** [comment]
> 直接在 CLI 上运行时如何添加代理，例如“npx chatgpt '您的提示'”？
> 
> 我添加了代理“export https_proxy= http://127.0.0.1:7890 http_proxy= http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890”，但它仍然不起作用。
我的路由器已经翻过去了，电脑访问api没问题，同样的网络下还是不行也是那个错误，再电脑上弄一个代理服务器从这个电脑再回到路由器再出去才行

**Comment by cuicui-V5** [comment]
> > same error
> > ```
> > TypeError: fetch failed
> >     at Object.fetch (node:internal/deps/undici/undici:11118:11)
> >     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> >     at async file:///home/lizhou/projects/chatgpt/node_modules/chatgpt/build/index.js:265:25 {
> >   cause: ConnectTimeoutError: Connect Timeout Error
> >       at onConnectTimeout (node:internal/deps/undici/undici:6625:28)
> >       at node:internal/deps/undici/undici:6583:50
> >       at Immediate._onImmediate (node:internal/deps/undici/undici:6614:13)
> >       at process.processImmediate (node:internal/timers:471:21) {
> >     code: 'UND_ERR_CONNECT_TIMEOUT'
> >   }
> > }
> > ```
> 
> I got the same error, have you resolve it?

I solved this problem by nginx reverse proxy, you need a server outside the GFW
- nginx config file

````

server {
	listen 443 ssl;
	server_name api.example.com;
	ssl_certificate /etc/nginx/ssl/cert.pem;
	ssl_certificate_key /etc/nginx/ssl/cert.key;
        ssl_protocols TLSv1.2 TLSv1.3;
	location / {
		proxy_pass https://api.openai.com/;
		proxy_set_header Host api.openai.com;
		proxy_set_header X-Real-IP $remote_addr;
	}
}
 
````
- add the URL to the .env file
````
OPENAI_API_KEY=sk-xxxxxxxxxxxxxxxxxxxxx
OPENAI_BASE_URL=api.example.com/
```` 
- config the api 
````
export const api = new ChatGPTAPI({
    apiKey: process.env.OPENAI_API_KEY,
    apiBaseUrl: process.env.OPENAI_BASE_URL,
});
````

**Comment by ozbillwang** [comment]
got the error, but I tested from oversea (australia)
```
npx chatgpt "hello world"
file:///xxx/node_modules/chatgpt/build/index.js:144
      throw new Error("Invalid environment; fetch is not defined");
            ^
Error: Invalid environment; fetch is not defined
    at new ChatGPTAPI (file:///xxx/node_modules/chatgpt/build/index.js:144:13)
    at CAC.<anonymous> (file:///xxx/node_modules/chatgpt/bin/cli.js:65:19)
    at CAC.runMatchedCommand (file:///xxx/node_modules/cac/dist/index.mjs:610:34)
    at CAC.parse (file:///xxxnode_modules/cac/dist/index.mjs:537:12)
    at main (file:///xxx/node_modules/chatgpt/bin/cli.js:116:9)
 ```

**Comment by cuicui-V5** [comment]
> 



> got the error, but I tested from oversea (australia)
> 
> ```
> # I can confirm the api key is valid, because i used it in vs-code currently
> $ export OPENAI_API_KEY="sk-TODOxxxx" 
> 
> $ npm install chatgpt
> 
> $ npx chatgpt "hello world"
> file:///xxx/node_modules/chatgpt/build/index.js:144
>       throw new Error("Invalid environment; fetch is not defined");
>             ^
> Error: Invalid environment; fetch is not defined
>     at new ChatGPTAPI (file:///xxx/node_modules/chatgpt/build/index.js:144:13)
>     at CAC.<anonymous> (file:///xxx/node_modules/chatgpt/bin/cli.js:65:19)
>     at CAC.runMatchedCommand (file:///xxx/node_modules/cac/dist/index.mjs:610:34)
>     at CAC.parse (file:///xxxnode_modules/cac/dist/index.mjs:537:12)
>     at main (file:///xxx/node_modules/chatgpt/bin/cli.js:116:9)
>     
> $ npx chatgpt -k "sk-TODOxxxx" "hello world"
> # got same error
> 
> # integrate with code to import the package, I got same error
> ```

Looks like this is unrelated to the API key. It seems that you don't have node-fetch installed or haven't configured it correctly

**Comment by ozbillwang** [comment]
> Looks like this is unrelated to the API key. It seems that you don't have node-fetch installed or haven't configured it correctly

I have installed `node-fetch`, got same issue. 

There should be no configure, except the environment variable `OPENAI_API_KEY` required. 

I tested in an empty folder. 
```
$ mkdir test
$ cd test

# I can confirm the api key is valid, because i used it in vs-code currently
$ export OPENAI_API_KEY="sk-TODOxxxx" 

$ npm install chatgpt
$ npm install node-fetch

$ npx chatgpt "hello world"
file:///xxx/node_modules/chatgpt/build/index.js:144
      throw new Error("Invalid environment; fetch is not defined");
            ^
Error: Invalid environment; fetch is not defined
    at new ChatGPTAPI (file:///xxx/node_modules/chatgpt/build/index.js:144:13)
    at CAC.<anonymous> (file:///xxx/node_modules/chatgpt/bin/cli.js:65:19)
    at CAC.runMatchedCommand (file:///xxx/node_modules/cac/dist/index.mjs:610:34)
    at CAC.parse (file:///xxxnode_modules/cac/dist/index.mjs:537:12)
    at main (file:///xxx/node_modules/chatgpt/bin/cli.js:116:9)
    
$ npx chatgpt -k "sk-TODOxxxx" "hello world"
# got same error

# integrate with code to import the package, I got same error
```

let me know what I missed.

**Comment by ozbillwang** [comment]
Know the reason now. 

The package doesn't work with `node:16`, but works in docker image `node:latest`

```
bill in /tmp/test  > docker run -ti --rm node:latest bash
Unable to find image 'node:latest' locally
latest: Pulling from library/node
32fb02163b6b: Pull complete
167c7feebee8: Pull complete
d6dfff1f6f3d: Pull complete
e9cdcd4942eb: Pull complete
ca3bce705f6c: Pull complete
4f4cf292bc62: Pull complete
8347f8b4b86b: Pull complete
c5f20f1b0856: Pull complete
d220dfa3e187: Pull complete
Digest: sha256:83841d113e09345a28b146e431f15b062341c5449218e501ba45ef8f9cff6049
Status: Downloaded newer image for node:latest
root@aa43287f2285:/# mkdir test
root@aa43287f2285:/# cd test
root@aa43287f2285:/test# npm install chatgpt

added 64 packages in 15s

18 packages are looking for funding
  run `npm fund` for details
npm notice
npm notice New minor version of npm available! 9.5.0 -> 9.6.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.1
npm notice Run npm install -g npm@9.6.1 to update!
npm notice
root@aa43287f2285:/test# export OPENAI_API_KEY="sk-TODO"
root@aa43287f2285:/test# npm install node-fetch

added 6 packages, and audited 71 packages in 3s

21 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
root@aa43287f2285:/test# node -v
v19.7.0
root@aa43287f2285:/test# npx chatgpt "hello world"
Hello!
root@aa43287f2285:/test#
```

if I test the same commands, with docker image `node:16`, I saw the issue

```
Error: Invalid environment; fetch is not defined
```

Please confirm.

**Comment by waelramsis** [comment]
I have a problem
I received failed to fetch (forbidden 403) when pressing the web access button only; otherwise, ChatGpt is still working.
This problem occurs in whatever browser I use (GoogleChrome or Mozilla Firefox)
This message keeps appearing on every query only when I use Web Access
Any help to fix this error

**Comment by waelramsis** [comment]
update:
the problem is partially fixed when I either restrict the search to the past year or I do regional restriction (for example search in US only not in any region)

**Comment by youngle316** [comment]
It works for me
```typescript
import { ChatGPTAPI } from "chatgpt";
import { HttpsProxyAgent } from "https-proxy-agent";
import nodeFetch from "node-fetch";

const api = new ChatGPTAPI({
	apiKey: (process.env.NEXT_PUBLIC_OPENAI_API_KEY as string) || "",
	fetch: (url, options = {}) => {
		const defaultOptions = {
			agent: new HttpsProxyAgent("http://127.0.0.1:7890"),
		};

		const mergedOptions = {
			...defaultOptions,
			...options,
		};

		return nodeFetch(url, mergedOptions);
	},
});

export { api };
```

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
