### ISSUE TITLE
Persistence stopped working (not Redis, file-storage)

### ISSUE THREAD

**Issue by yavuzitconsulting** [transitive-bullshit/chatgpt-api#421]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Running in Docker for Linux

### Describe the Bug

Hi!
Before upgrading to the latest release, i was still running on version 4.4.0
My solution for persistence was storing the response received from the chatgpt api on the hard drive via JSON.stringyfy(response).
It worked fine, i was able to use parentmessageId to continue the last conversation, even after restarting the app, just by deserializing the file from the hard drive.
Now, it looks like the parentMessageId is loosing its context, i am unable to understand if this is a local problem or one with the package, but i figured i ask here just in case, since the issue did not exist in the previous version.
Even mid-conversation, the api seems to loose the conversation context, is this a problem with gpt-turbo?
Regards

**Comment by richardjzhang** [comment]
I had a similar issue but realised I was instantiating a new instance of the `ChatGPTAPI` each time I made a new request, which was causing the issue

Just wondering if you are instantiating it more than once?

**Comment by yavuzitconsulting** [comment]
Hi Richard! Thanks for the reply.
I di create a new instance after every docker-restart, which happens sometimes, but that shouldn't be an issue since the parenrmessageid should work cross-instance, e.g. the CLI also has a continue option and continueing in a new instance worked on the older version of the package.
In short, it was possible to continue the conversation after an update/restart/downtime, based on the parenrmessageid.

**Comment by richardjzhang** [comment]
@yavuzitconsulting That's interesting 🤔. Just to clarify, does ChatGPT lose the context of the conversation after an update/restart/downtime? Or does it lose the context after every request?

**Comment by transitive-bullshit** [comment]
The default stores messages in memory, so if you want to persist conversation state across update/restart/downtime, you need to use a persistent message store. The readme has examples of this as well as `demos/demo-persistence.ts`.

You can use any `keyv` database adaptor or fully take control and override the `getMessageById` and `upsertMessage` options to store them however you want.

**Comment by yavuzitconsulting** [comment]
just to note, since this bug was closed without comment.
i do persist the state, as described in my bug description, you just commented that i have to persist the state and then closed the issue which makes no sense at all all.

i also described how i persist the state, and that this way of persisting worked in 4.4.0 but does not in the current version.
