### ISSUE TITLE
adding google search api with chatgpt to get answer like bingai

### ISSUE THREAD

**Issue by analogllp** [transitive-bullshit/chatgpt-api#423]
### Describe the feature

adding google search api with chatgpt to get answer like bingai

**Comment by transitive-bullshit** [comment]
Great idea, but it's outside the scope of this repo.

The goal of this package is to make recreating ChatGPT as simple as possible. If you want to add additional functionality, you're welcome to add it on top of this package.

A good place to start would be checking out LangChain.
