### ISSUE TITLE
Module not found: Can't resolve '@dqbd/tiktoken' in '/vercel/path0/node_modules/chatgpt/build'

### ISSUE THREAD

**Issue by stark-eth** [transitive-bullshit/chatgpt-api#429]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

vercel build environment

### Describe the Bug

when I build my demo in vercel it always build fail.
`Module not found: Can't resolve '@dqbd/tiktoken' in '/vercel/path0/node_modules/chatgpt/build'`

**Comment by transitive-bullshit** [comment]
This may be related: https://github.com/transitive-bullshit/chatgpt-api/issues/413

`@dqbd/tiktoken` uses WASM, which may not be handled correctly in some environments. Can you give me as much detail about your "vercel build environment" as possible? e.g., is it a serverless function or edge function? Is this from next.js and if so, what version? Are you using `appDir`? etc.

**Comment by stark-eth** [comment]
> 

Thanks. I  know that the problem is this api can only run in node.js client  not in browser
