### ISSUE TITLE
thanks for you

### ISSUE THREAD

**Issue by Chanzhaoyu** [transitive-bullshit/chatgpt-api#430]
### Describe the feature

Hi, I have made an open source project using your project and so far got 3.3k Star, thanks a lot for your contribution. The instructions are in Chinese, and my English is not very good. But, thank you very much! [[link](https://github.com/Chanzhaoyu/chatgpt-web)]

**Comment by Chanzhaoyu** [comment]
You can close this issue once you see it XD

**Comment by transitive-bullshit** [comment]
Thanks @Chanzhaoyu && congrats on the success of your project so far 🙏  It looks really, really well done.
