### ISSUE TITLE
Allow modificatons of completionParams via sendMessage 

### ISSUE THREAD

**Issue by markNZed** [transitive-bullshit/chatgpt-api#434]
### Describe the feature

For options like temperature it seems OpenAPI supports changing this per chatCompletion message. For example, on a server we might have one API instance the is sending messages for different clients with different temperature ?

**Comment by transitive-bullshit** [comment]
Makes sense and happy to accept a PR for this.

`completionParams` being part of the constructor is purely because of historical reasons as the package has gone through quite a few iterations.

Thanks!

**Comment by markNZed** [comment]
How would you like the interface to look ? Would we add a public function for updating the params or add options to sendmessage ?

**Comment by transitive-bullshit** [comment]
Just adding it as an additional option to `sendMessage` opts and having it override the defaults like

```ts
const completionParams = { ...this._completionParams, ...opts.completionParams }
```

**Comment by transitive-bullshit** [comment]
@markNZed this is now supported in https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v5.1.1 🔥

**Comment by markNZed** [comment]
I finally got to testing this and ran into problems. Do we need to be able to dynamically set:  maxResponseTokens and maxModelTokens. Is it possible to do this with the OpenAI API ? A minor issues was a change in the artialResponse.delta starting with special characters that no longer went through JSON.stringify(partialResponse.delta) but that is not a big deal.
