### ISSUE TITLE
res.id lost in version^5.0.6, we can not track the conversation.

### ISSUE THREAD

**Issue by assmdx** [transitive-bullshit/chatgpt-api#435]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

version@5.0.6

### Describe the Bug

res.id lost in version^5.0.6, we can not track the conversation.
the response is :
```
{
  errCode: 0,
  msg: '',
  data: { text: 'Hello! How can I assist you today?' }
}
```

**Comment by transitive-bullshit** [comment]
@assmdx Are you using `ChatGPTAPI` or `ChatGPTUnofficialProxyAPI`?

Can you paste the whole code you're using to initialize and call `sendMessage`? Your JSON example isn't in the format that this package uses, so it's likely that some wires are getting crossed somewhere.

**Comment by assmdx** [comment]
@transitive-bullshit the  code is :
```
import { ChatGPTAPI } from "chatgpt"
import Keyv from "keyv"
import express from "express"
import bodyParser from "body-parser"

const chatgptApi = new ChatGPTAPI({
    apiKey: "XXXXXXXXXXXXXXXXXXXXXXXX"
})
const app = express()
app.use(bodyParser.urlencoded({extended:true}))
app.use(bodyParser.json())

const kv = new Keyv()

app.post(`/message`, async (req, res) => {
    try {
      const { message, conversationId } = req.body
      if (!message) {
        return res.json({
            errCode: 1,
            msg: "message can not be empty"
        })
      }
      let parentMessageId = ""
      if (conversationId) {
        parentMessageId = kv.get(conversationId)
      }
      let reply = null 
      if (parentMessageId && conversationId) {
        reply = await chatgptApi.sendMessage(message, {
            conversationId,
            parentMessageId
        })
      } else {
        reply = await chatgptApi.sendMessage(message)
      }
      if (reply) {
        const {text, id, conversationId} = reply
        kv.set(conversationId, id)
        return res.json({
            errCode: 0,
            msg: "",
            data: {
                conversationId,
                text
            }
        })
      } else {
        console.error(e)
        return res.json({
            errCode: 1,
            msg: "server error"
        })
      }
    } catch (e) {
      console.error(e)
      return res.status(500).json({
        errCode: 1,
        msg: "server error"
      })
    }
})

app.listen(22040,  () => {
    console.log('slow chatgpt server is listen on 22040')
})


```

**Comment by transitive-bullshit** [comment]
@assmdx the latest version doesn't use `conversationId`, because it's not used by the official API. Just use `res.id` as the `parentMessageId`.

**Comment by assmdx** [comment]
thank you , it works.

**Comment by assmdx** [comment]
res.id is still not work. what does res.id and res.parentMessageId means?

Whether I use the reply.parentMessageId or reply.id as the next request's parentMessageId， chatgpt can always dont know what I asked past, this is a bug.

**Comment by maciej-trebacz** [comment]
It also doesn't work for me, It looks like the request that's getting sent to the ChatGPT API is correct (it contains the whole conversation history) but the bot always insists that it doesn't remember what was going on before. Anyone else having this kind of issue?

**Comment by BigBroFinch** [comment]
:d  I also have the same problem, AI can't connect to context anymore.

**Comment by BigBroFinch** [comment]
:d I also have the same problem

**Comment by transitive-bullshit** [comment]
@maciej-trebacz @BigBroFinch may be due to the differences in the ChatGPT webapp's behavior versus the behavior of the Chat completions API. I'd love to try and improve support here, though.

Can you paste some example conversations (`messages` JSON by enabling `debug` mode) where you're seeing unexpected outputs? That will help me try and reproduce the issue and give better advice or make changes to the lib.

Thanks!

**Comment by assmdx** [comment]
> @maciej-trebacz @BigBroFinch may be due to the differences in the ChatGPT webapp's behavior versus the behavior of the Chat completions API. I'd love to try and improve support here, though.
> 
> Can you paste some example conversations (`messages` JSON by enabling `debug` mode) where you're seeing unexpected outputs? That will help me try and reproduce the issue and give better advice or make changes to the lib.
> 
> Thanks!

question1: When did Gauss and his wife get married？
question2: How long have they been in love？

chatgpt will reply: "I don't know who is they..."

**Comment by artemquel** [comment]
I've got same issue.

First message debug:
```
sendMessage (54 tokens) {
  max_tokens: 1000,
  model: 'gpt-3.5-turbo',
  temperature: 0.8,
  top_p: 1,
  presence_penalty: 1,
  messages: [
    {
      role: 'system',
      content: 'You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\n' +
        'Knowledge cutoff: 2021-09-01\n' +
        'Current date: 2023-03-15'
    },
    {
      role: 'user',
      content: 'Write an example react component',
      name: undefined
    }
  ],
  stream: false
}
{
  id: 'chatcmpl-6uTDgs5Hn5rfnJaehix7MSdA6weAn',
  object: 'chat.completion',
  created: 1678916708,
  model: 'gpt-3.5-turbo-0301',
  usage: { prompt_tokens: 61, completion_tokens: 115, total_tokens: 176 },
  choices: [ { message: [Object], finish_reason: 'stop', index: 0 } ]
}
``` 

Second message debug:
```
sendMessage (54 tokens) {
  max_tokens: 1000,
  model: 'gpt-3.5-turbo',
  temperature: 0.8,
  top_p: 1,
  presence_penalty: 1,
  messages: [
    {
      role: 'system',
      content: 'You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\n' +
        'Knowledge cutoff: 2021-09-01\n' +
        'Current date: 2023-03-15'
    },
    {
      role: 'user',
      content: 'Rewrite it with TypeScript',
      name: undefined
    }
  ],
  stream: false
}
{
  id: 'chatcmpl-6uTF1UAftO4iv52i8bJD3m9U4P9CH',
  object: 'chat.completion',
  created: 1678916791,
  model: 'gpt-3.5-turbo-0301',
  usage: { prompt_tokens: 61, completion_tokens: 23, total_tokens: 84 },
  choices: [ { message: [Object], finish_reason: 'stop', index: 0 } ]
}
```

The first time he sent me a component, the second time he replied "I'm sorry, but could you please provide me with the original code or statement to be rewritten in TypeScript?"

**Comment by discoteq-cmd** [comment]
I have the same issue

**Comment by artemquel** [comment]
In my case, the problem was that I was initializing a new instance of the ChatGPTAPI class every time through a factory. As a result, every time I initialized it, my keyv instance, which stores message history, was reset. Initializing keyv outside of my factory and passing the instance through messageStore in the constructor of ChatGPTAPI helped me.

**Comment by BigBroFinch** [comment]
> @maciej-trebacz @BigBroFinch may be due to the differences in the ChatGPT webapp's behavior versus the behavior of the Chat completions API. I'd love to try and improve support here, though.
> 
> Can you paste some example conversations (`messages` JSON by enabling `debug` mode) where you're seeing unexpected outputs? That will help me try and reproduce the issue and give better advice or make changes to the lib.
> 
> Thanks!

hello bro @transitive-bullshit 

![image](https://user-images.githubusercontent.com/84056084/225820193-f6333be9-4452-4b6c-a7f0-af18781301db.png)
this is my nestjs server 
and whatever i send msg width **parentMessageId** 

and this is  debug log   

`sendMessage (46 tokens) {
  max_tokens: 1000,
  model: 'gpt-3.5-turbo',
  temperature: 0.8,
  top_p: 1,
  presence_penalty: 1,
  messages: [
    {
      role: 'system',
      content: 'You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\n' +
        'Knowledge cutoff: 2021-09-01\n' +
        'Current date: 2023-03-17'
    }
  ],
  stream: false
}
{
  id: 'chatcmpl-6uwzPVrszdmNrvGsVTopp2tolRUB2',
  object: 'chat.completion',
  created: 1679031143,
  model: 'gpt-3.5-turbo-0301',
  usage: { prompt_tokens: 51, completion_tokens: 33, total_tokens: 84 },
  choices: [ { message: [Object], finish_reason: 'stop', index: 0 } ]
}`

Even if I include the parentMessageId when sending a message, the debug log only returns two messages each time  

thanks

**Comment by maciej-trebacz** [comment]
I finally resolved this issue on my end. There are two things to keep in mind, one in hindsight was kind of obvious, the other not so much:

1. The ChatGPTAPI needs to be instantiated globally and not on every request, because it stores the message history within the object itself (the API itself doesn't store your message history for you).
2. You *need* to supply a `systemMessage` parameter with a system prompt when creating a ChatGPTAPI instance in order for the conversation tracking feature to work. This requirement is not documented anywhere (at least I didn't see it anywhere, the OpenAI documentation just says that "typically" this is how people do it). When you supply a correct system message and  turn on the `debug` flag when you instantiate the API object your debug log should looks as follows:

```
...
  messages: [
    {
      role: 'system',
      content: " your system message prompt here "
    },
    { role: 'user', content: 'hey there AI, how are you today?', name: undefined },
    {
      role: 'assistant',
      content: "Thanks, I'm good, how about you?",
      name: undefined
    },
...
```

**Comment by inannan423** [comment]
The day before yesterday was a normal situation, yesterday suddenly encountered this problem, see [issue-1728724329](https://github.com/transitive-bullshit/chatgpt-api/issues/576#issue-1728724329), does anyone have a solution ？

**Comment by inannan423** [comment]
# Problem Solved
**The problem is solved**, because my code is not perfect, so there is an error above the API request, this error causes the code of Next.js to be recompiled, so ChatGPTAPI is also reinitialized, naturally it will forget the conversation, if you encounter similar problems, please troubleshoot two aspects: 
1. Put the initialization of the API at the top of the module, instead of initializing it every time you request the interface. 
2. **_Is there some bugs in the code that will cause dev to restart_**.

Thanks @maciej-trebacz for the reminder.

> The day before yesterday was a normal situation, yesterday suddenly encountered this problem, see [issue-1728724329](https://github.com/transitive-bullshit/chatgpt-api/issues/576#issue-1728724329), does anyone have a solution ？

**Comment by JS-an** [comment]
> # 问题解决了
> **问题解决了**，因为我的代码不完美，所以API请求上面有一个错误，这个错误导致Next.js的代码被重新编译，所以ChatGPTAPI也被重新初始化，自然会忘记对话，如果你遇到类似问题，请从两个方面排查：
> 
> 1. 将API的初始化放在模块的顶部，而不是每次请求接口时都初始化。
> 2. **_代码中是否存在一些错误会导致开发重新启动_**。
> 
> 谢谢@maciej-trebacz为了提醒。
> 
> > 前天还正常的情况，昨天突然遇到这个问题，查看[issue-1728724329](https://github.com/transitive-bullshit/chatgpt-api/issues/576#issue-1728724329)，有谁有解决办法吗？

This is very useful to me

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
