### ISSUE TITLE
Progress demo file printing new line for each chunk

### ISSUE THREAD

**Issue by giabertu** [transitive-bullshit/chatgpt-api#436]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node version: v18.14.2
OS: macOS Ventura 13.2.1

### Describe the Bug

I forked the repository, and tried running one of the demo files given, using the ```npx tsx demos/demo-on-progress.ts```. The output seems to result from a new line being created for each chunk appended. See the image for context.

![image](https://user-images.githubusercontent.com/75525883/222965639-ee8c28e0-2a18-4c35-83c2-b3205646aa86.png)

**Comment by tynguyen** [comment]
You're printing "Partial messages" which consists of all token generated so far for a given prompt. Use "delta" instead. 
For example: 
`onProgress: (partialResponse) => console.log(partialResponse.delta) `
This will print out token by token with a breakline after each token (due to console.log())

**Comment by transitive-bullshit** [comment]
Check out the included [cli.js](https://github.com/transitive-bullshit/chatgpt-api/blob/0ed1ad003568eba776da2dbd78a4edc73f8acad3/bin/cli.js#L91) for an example of how to print the output without newlines.

The demo is only included for example purposes, so it's verbose by default.

**Comment by giabertu** [comment]
Thank you both for clarifying. Wans't aware of ```process.stdout.write(partialResponse.delta)``` in the cli.js file!

**Comment by BDSalt** [comment]
I used this: onProgress: (partialResponse) => console.log(partialResponse.delta)  in node 18.12.1, but I'm getting undefined. My partialResponse object looks like this: 
{
  role: 'assistant',
  id: 'e7e8a046-ff4b-47f4-8685-025381d862dc',
  parentMessageId: 'd36c91a7-bd0e-44a2-ac3a-3049eb51e8aa',
  conversationId: '6e6ee5ae-e578-4d51-929b-f87261e645b4',
  text: 'They met'
}

**Comment by transitive-bullshit** [comment]
@BDSalt it looks like you're either not using `ChatGPTAPI` or you're using an earlier version of the package. Double check to make sure you're not using the unofficial proxy (which doesn't support deltas), and double check your package version.

**Comment by BDSalt** [comment]
> ### Verify latest release
> * [x]  I verified that the issue exists in the latest `chatgpt` release
> 
> ### Verify webapp is working
> * [x]  I verify that the ChatGPT webapp is working properly for this account.
> 
> ### Environment details
> Node version: v18.14.2 OS: macOS Ventura 13.2.1
> 
> ### Describe the Bug
> I forked the repository, and tried running one of the demo files given, using the `npx tsx demos/demo-on-progress.ts`. The output seems to result from a new line being created for each chunk appended. See the image for context.
> 
> ![image](https://user-images.githubusercontent.com/75525883/222965639-ee8c28e0-2a18-4c35-83c2-b3205646aa86.png)

Thank you. I fixed it by upgrading to the newest version.

**Comment by BDSalt** [comment]
> @BDSalt it looks like you're either not using `ChatGPTAPI` or you're using an earlier version of the package. Double check to make sure you're not using the unofficial proxy (which doesn't support deltas), and double check your package version.

@transitive-bullshit Thank you! I fixed it by upgrading to the newest version.
