### ISSUE TITLE
Add Simple TTS for prompts generated through CLI (using say?)

### ISSUE THREAD

**Issue by giabertu** [transitive-bullshit/chatgpt-api#437]
### Describe the feature

Personally, I would find the option of adding TTS for prompts being generated to be useful. Perhaps this could be done through the use of another cli option, which specifies that we would like the text to be read aloud as well. 

To implement TTS one could use an API service or simply use the ```say``` command. 

A command like the following: ```npx chatgpt "write a poem" |  say ``` already works as intended, but doesn't allow for the output to be printed out. 

A command like ```npx chatgpt "write a poem" | tee>(say) ``` would also duplicate the output returned by chatgpt to the terminal, but delays the TTS from the say command. 

I just presented some ideas, but I am not 100% sure how they would be implemented. The say command could be triggered using a library like https://github.com/Marak/say.js/ for each chunk being returned by the API, while also streaming the text to the console.

**Comment by transitive-bullshit** [comment]
Thanks @giabertu; I like the idea, but I'm not sure if it makes sense for this package to support TTS directly beyond the CLI stdout it already supports.

I think this use case would work better as a separate package / CLI that was optimized for this purpose, perhaps calling into `chatgpt`'s `sendMessage` with an `onProgress` handler under the hood.

I'm going to close this for now as out of scope, but if you have a more concrete suggestion for the CLI that wouldn't involve adding any additional complexity, I'm happy to consider it.

Thanks again 🙏
