### ISSUE TITLE
Automatically delete previous conversations to prevent Token from exceeding the maximum limit

### ISSUE THREAD

**Issue by TheLittleB** [transitive-bullshit/chatgpt-api#438]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

[Related](https://github.com/Chanzhaoyu/chatgpt-web/issues/324)

This model's maximum context length is 4096 tokens.

Automatically delete the initial conversation to reduce the Token size and prevent errors.

### Describe the Bug

If the Token limit is reached without automatically deleting the previous conversation, then an error will occur.

**Comment by wejudging** [comment]
期待更新！

**Comment by transitive-bullshit** [comment]
@TheLittleB we have logic which attempts to count the number of tokens and not use any previous messages that would push the context length over. That being said, this logic isn't full-proof, and I'm sure it can be improved.

Either way, we wouldn't want to delete previous messages from the conversation; we just want to improve our logic for estimating context length.

**Comment by Nicolas-Gong** [comment]
> @TheLittleB we have logic which attempts to count the number of tokens and not use any previous messages that would push the context length over. That being said, this logic isn't full-proof, and I'm sure it can be improved.
> 
> Either way, we wouldn't want to delete previous messages from the conversation; we just want to improve our logic for estimating context length.

I have coded a solution in Python to bypass the max_token issue. The workflow involves storing the number of tokens consumed in each conversation and then reversing the conversation order. Once the token usage exceeds a certain threshold (set at 2500 by me), previous chat records are discarded. However, these records still appear on the page, and only a portion of the chat history is passed to the chatgpt API, ensuring that chat records are kept while also preserving some chat memory.

![image](https://user-images.githubusercontent.com/23067153/223058320-23f68774-320d-42c8-bf8d-398be4b4116c.png)

```
[
    {
        "role": "user",
        "content": "\u6211\u7528python\u5199\u8FC7\u4E00\u4E2A\u7ED5\u8FC7max_token\u7684\u95EE\u9898\uFF0C\u6D41\u7A0B\u5C31\u662F\u5728\u6BCF\u4E2A\u5BF9\u8BDD\u65F6\u90FD\u5B58\u4E86\u6D88\u8017\u7684token\u6570\u91CF\uFF0C\u7136\u540E\u628A\u4F1A\u8BDD\u5012\u8FC7\u6765\u8BA1\u7B97\uFF0C\u5F53\u8FBE\u5230\u4E00\u5B9A\u7684\u91CF\u7EA7\u540E\uFF08\u6211\u81EA\u5DF1\u8BBE\u7F6E\u76842500\uFF09\uFF0C\u5C06\u820D\u5F03\u4EE5\u524D\u7684\u804A\u5929\u8BB0\u5F55\uFF0C\u4F46\u662F\u5728\u9875\u9762\u8FD8\u662F\u663E\u793A\uFF0C\u53EA\u662F\u8C03\u7528chatgpt\u7684api\u65F6\u53EA\u4F20\u8FD9\u4E48\u591A\u804A\u5929\u8BB0\u5F55\u8FC7\u53BB\uFF0C\u8FD9\u6837\u65E2\u6EE1\u8DB3\u4E86\u804A\u5929\u8BB0\u5F55\u4FDD\u5B58\uFF0C\u4E5F\u6EE1\u8DB3\u4E86\u90E8\u5206\u804A\u5929\u8BB0\u5FC6\u3002%5Cn\u7FFB\u8BD1\u6210\u6D41\u884C\u4E14\u6807\u51C6\u7684\u82F1\u8BED\u3002"
    },
    {
        "role": "token",
        "completion_tokens": 98,
        "total_tokens": 261
    },
    {
        "role": "assistant",
        "content": "%5Cn%5CnI have coded a solution in Python to bypass the max_token issue. The workflow involves storing the number of tokens consumed in each conversation and then reversing the conversation order. Once the token usage exceeds a certain threshold %28set at 2500 by me%29, previous chat records are discarded. However, these records still appear on the page, and only a portion of the chat history is passed to the chatgpt API, ensuring that chat records are kept while also preserving some chat memory."
    }
]
```

**Comment by Nicolas-Gong** [comment]
```
ChatGPT error 400: {
  "error": {
    "message": "This model's maximum context length is 4096 tokens. However, you requested 4109 tokens (3109 in the messages, 1000 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}
```

For example, when the initial 3000 is not enough, it can be seen when reporting this error. The specific value can be seen in the information returned by the error, `you requested 4109 tokens (3109 in the messages, 1000 in the completion)`, so we still need 1000 `tokens`, you can further increase the threshold for recursive calls, or allow users to request the API again on their own initiative.

**Comment by transitive-bullshit** [comment]
The latest update sets a more conservative `maxModelTokens`, which should help mitigate this error: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v5.0.8

It's using 4000 as suggested by @yuezk 👍 

It's unfortunately not possible to completely remove the possibility for this error at the moment, because we don't have access to how OpenAI's chat endpoint is calculating token lengths for the `messages`, so we're currently using an estimate.

**Comment by leobaldoneto** [comment]
@transitive-bullshit There's an OpenAI's lib that counts tokens, but it is in python: https://github.com/openai/tiktoken

> To see how many tokens are in a text string without making an API call, use OpenAI’s [tiktoken](https://github.com/openai/tiktoken) Python library. Example code can be found in the OpenAI Cookbook’s guide on [how to count tokens with tiktoken](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb).

Source: https://platform.openai.com/docs/guides/chat/introduction

**Comment by transitive-bullshit** [comment]
Closing as [v5.0.8 (release)](https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v5.0.8) contains a suitable temporary fix.
