### ISSUE TITLE
Look forward to the author adding agents for Chinese developers in the code, thanks a lot!

### ISSUE THREAD

**Issue by Song-Mao** [transitive-bullshit/chatgpt-api#441]
### Describe the feature

Look forward to the author adding agents for Chinese developers in the code, thanks a lot!

**Comment by lzfxxx** [comment]
You can try adding a proxy by replacing the default fetch: https://github.com/transitive-bullshit/chatgpt-api/issues/419#issuecomment-1452108845

**Comment by transitive-bullshit** [comment]
I'd be very open to a PR which improves the readme around how to use a proxy here.

**Comment by transitive-bullshit** [comment]
Closing this now as stale; feel free to follow up in the chinese section of our discord https://www.chatgpthackers.dev
