### ISSUE TITLE
The systemMessage in api.sendMessage doesn't work properly

### ISSUE THREAD

**Issue by rever273** [transitive-bullshit/chatgpt-api#446]
### Verify latest release

- [X] I verify that the ChatGPT webapp is working properly for this account.
- [X] I verified that the issue exists in the latest `chatgpt` release

### Environment details

Node.js 8.12.2

### Describe the Bug

`"choices": [
      {
        "message": {
          "role": "assistant",
          "content": "am just a computer program ready to help you with any questions or tasks! You can contact me on any topic, and I'll try to help."
        },
        "finish_reason": "stop",
        "index": 0
      }
    ]`

When I send a message in response I get no data about the role: system.
ChapGPT does not respond to the role I give it. Let's say I ask him to be Mickey Mouse and talk about Disney. When asked "who are you" he gives the standard answer without mentioning that role.
In version 4, everything worked correctly with "promt".

**Comment by transitive-bullshit** [comment]
Hey @rever273, just curious what you ended up finding with this?

**Comment by rever273** [comment]
> 

Sorry, everything work's fine. 
There is no "role: system" in return message, but all work good!
I just made wrong prompt for my language. Change it and ChatGPT start understand me.

Thanks again for this good code!
