### ISSUE TITLE
UND_ERR_HEADERS_TIMEOUT 访问经常返回

### ISSUE THREAD

**Issue by youminxue** [transitive-bullshit/chatgpt-api#448]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

centos

### Describe the Bug

0|main  | send error: TypeError: fetch failed
0|main  |     at Object.fetch (node:internal/deps/undici/undici:11404:11)
0|main  |     at async file:///tmp/18890990/chat/node_modules/chatgpt/build/index.js:265:25 {
0|main  |   cause: HeadersTimeoutError: Headers Timeout Error
0|main  |       at Timeout.onParserTimeout [as callback] (node:internal/deps/undici/undici:9596:32)
0|main  |       at Timeout.onTimeout [as _onTimeout] (node:internal/deps/undici/undici:7899:17)
0|main  |       at listOnTimeout (node:internal/timers:568:17)
0|main  |       at process.processTimers (node:internal/timers:511:7) {
0|main  |     code: 'UND_ERR_HEADERS_TIMEOUT'
0|main  |   }
0|main  | }

**Comment by youminxue** [comment]
请问这个有什么解决办法

**Comment by transitive-bullshit** [comment]
@youminxue this may be due to https://github.com/transitive-bullshit/chatgpt-api/issues/419

**Comment by youminxue** [comment]
我的服务部署在国外的机器上，应该不是类似的问题，而且不是所有的请求都这样，复杂的问题比较容易出现。

**Comment by transitive-bullshit** [comment]
@youminxue can you paste as much code as possible with how you're using the API, so I can take a look? Right now, I don't have enough information to try and help.

**Comment by transitive-bullshit** [comment]
@youminxue it's likely that the IP you're using has been blocked for some reason.

Also see #453

**Comment by youminxue** [comment]
openai在封锁商用行为，需要研究一下如何解决

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
