### ISSUE TITLE
使用这个库有没有可能会导致账号被封禁？

### ISSUE THREAD

**Issue by HttpStatusOK** [transitive-bullshit/chatgpt-api#449]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

nodejs -> 18
pkg -> 5.0.8

### Describe the Bug

今天下午开始大量账号被封禁了，我用的是official模式，有没有遇到相同问题的？
{
    "error": {
        "message": "Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.",
        "type": "access_terminated",
        "param": null,
        "code": null
    }
}

**Comment by azbh111** [comment]
我也遇到同样问题了，主要是不知道为啥被封，头疼

**Comment by transitive-bullshit** [comment]
No; if you are using this library correctly, you will not get banned. `ChatGPTAPI` uses the official OpenAI chat completions API.

You _can_ get banned if your inputs to their API routinely violate their terms of service (e.g., excessive content that is harmful, violent, sexual, nsfw, etc).

I highly recommend integrating OpenAI's moderation endpoints if you're dealing with end-user input that you don't control. I gave more info on this here: https://github.com/transitive-bullshit/chatgpt-api/issues/383#issuecomment-1439673436
