### ISSUE TITLE
How to enable internet function in unofficial mode

### ISSUE THREAD

**Issue by huluohu** [transitive-bullshit/chatgpt-api#450]
### Describe the feature

when I use unofficial API，How to enable internet function.

**Comment by transitive-bullshit** [comment]
@huluohu the unofficial API has been patched by OpenAI and will no longer work. See #453 for details, and please use the official API `ChatGPTAPI` instead.

**Comment by huluohu** [comment]
> @huluohu the unofficial API has been patched by OpenAI and will no longer work. See #453 for details, and please use the official API `ChatGPTAPI` instead.



> @huluohu the unofficial API has been patched by OpenAI and will no longer work. See #453 for details, and please use the official API `ChatGPTAPI` instead.

Okay, I understand.
