### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by xithalius** [transitive-bullshit/chatgpt-api#451]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Vercel Edge Functions - Node 18.x

### Describe the Bug

As soon as I try to create a ChatGPTAPI instance I'm getting the following error.

```
error - node_modules/keyv/src/index.js (37:0) @ <unknown>
error - Class extends value #<Object> is not a constructor or null
null
warn  - ./node_modules/keyv/src/index.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/keyv/src/index.js
./node_modules/chatgpt/build/index.js
```

I might be doing something wrong, is there a Vercel Edge Function example using this package I can take a look at?

**Sample code:**
```
import { ChatGPTAPI } from 'chatgpt';
import { NextRequest, NextResponse } from 'next/server';

export const config = {
  runtime: 'edge',
};

const handler = async (req: NextRequest, res: NextResponse) => {
  const api = new ChatGPTAPI({
    apiKey: process.env.OPENAI_API_KEY ?? '',
  });

  return new Response(JSON.stringify({}), {
    status: 200,
  });
};

export default handler;
```

**Comment by xithalius** [comment]
Yes, now that I see it, it is indeed related to #413. Although I did use pages/api (API Route) instead of the new Next.js 13 Route Handler (hence I created a new issue). So #413 is not a Next.js bug but is environment related I suppose. Will close this awaiting Edge support. (Vercel) Serverless Functions are not an option for me as they do not support streaming.

**Comment by MaxLeiter** [comment]
hey @xithalius, just an fyi that Vercel Serverless Functions do support streaming: https://vercel.com/blog/streaming-for-serverless-node-js-and-edge-runtimes-with-vercel-functions
 
@transitive-bullshit I'm another user who would like to use this library in an edge function
