### ISSUE TITLE
This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

### ISSUE THREAD

**Issue by stark-eth** [transitive-bullshit/chatgpt-api#452]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node version 16.x

### Describe the Bug

1 import Keyv from 'keyv';
         ~~~~

  node_modules/keyv/src/index.d.ts:116:1
    116 export = Keyv;
        ~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

node_modules/chatgpt/build/index.d.ts:4:23 - error TS2304: Cannot find name 'fetch'.

4 type FetchFn = typeof fetch;
                        ~~~~~


Found 2 errors.

**Comment by PluginsKers** [comment]
```ts
{
  "compilerOptions": {
    ...
    "esModuleInterop": true,
    ...
  }
}
```

**Comment by alan890104** [comment]
I have found another solution when i'm creating a vscode-plugin with `node 18` 

## In your command line
```bash
yarn add node-fetch
yarn add @types/node-fetch --dev
```

## Modify your `tsconfig`
```json
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "ES2020",
		"outDir": "out",
		"lib": [
			"ES2020",
			"DOM", # Important
		],
		"sourceMap": true,
		"rootDir": "src",
		"esModuleInterop": true, # Important
	}
}
```

**Comment by jmejiamu** [comment]
Hey everyone, I have this error
```bash
src/Routes/post/events/index.ts:1:8 - error TS1259: Module '"/Users/josemejia/Desktop/RN/walk-smart-api/node_modules/@types/express/index"' can only be default-imported using the 'esModuleInterop' flag

1 import express from "express";
         ~~~~~~~

  node_modules/@types/express/index.d.ts:128:1
    128 export = e;
        ~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```

I have this in my `tsconfig.json`

```javascript
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "ES2020",
		"outDir": "out",
		"lib": [
			"ES2020",
			"DOM", # Important
		],
		"sourceMap": true,
		"rootDir": "src",
		"esModuleInterop": true, 
	}
}

```

Add this to the `package.json`

`"type": "module",`

Any idea what I am missing here?

**Comment by SherAtrium** [comment]
adding include to ts config file is helped me.

// ...
"include": [
  "src"
]
// ...
