### ISSUE TITLE
ChatGPTUnofficialProxyAPI no longer works – use ChatGPTAPI instead

### ISSUE THREAD

**Issue by transitive-bullshit** [transitive-bullshit/chatgpt-api#453]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

n/a

### Describe the Bug

The **bypass appears to have been patched by OpenAI** for `ChatGPTUnofficialProxyAPI`. It's possible this is related to a temporary [OpenAI server outage](https://status.openai.com/), but I think that's unlikely.

For the time being, `ChatGPTUnofficialProxyAPI` is unlikely to work until our [community](https://discord.gg/v9gERj825w) finds a different workaround.

If you haven't already switched to the official API (`ChatGPTAPI`), now might be a good time to try it out. It requires an OpenAI API key and is paid beyond the $18 free tier, but OpenAI recently dropped their prices 90%, so it's still pretty affordable.

**I highly suggest moving to use the official API via `ChatGPTAPI`.**

I will be updating this thread and [our discord](https://discord.gg/v9gERj825w) as we make progress, and I will likely push an update to the readme soon with the same info.

**Comment by ludashi2020** [comment]
![WeChat截图_20230309190702.png](https://pic.shenbian.tv/2023/03/09/c35f09eae8e4a.png)

**Comment by transitive-bullshit** [comment]
Update: Upgrade to https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v5.0.10 which uses a new proxy by @acheong08

**Comment by tayron1** [comment]
Yea now that release isnt working too

**Comment by acheong08** [comment]
> Yea now that release isnt working too

I think there was some downtime on the part of OpenAI. I just checked and it worked.

**Comment by tayron1** [comment]
Then imma try again today, maybe it works now

**Comment by slayer1551** [comment]
Do you not also have to provide your cookie? When testing it on Postman it only works when I also grab the cookie after logging in

**Comment by neelhabib** [comment]
not working. node is exit with blank

**Comment by rzfzr** [comment]
Is the unofficial api completely dead now? I'm getting 403 forbidden errors

**Comment by schalkburger** [comment]
The Discord invite code is invalid, does anyone have an updated link?

**Comment by acheong08** [comment]
@schalkburger

https://github.com/transitive-bullshit/chatgpt-hackers/issues/3

I've also checked with one of the members currently in the server and apparently new invites are disabled.

(I was one of the original admins in the server but left a few months ago)

**Comment by stephanvebrian** [comment]
@transitive-bullshit 

Can i get the discord invite code ? seems like its invalid

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package.
