### ISSUE TITLE
Do you have a plan to add networking to the API?

### ISSUE THREAD

**Issue by huluohu** [transitive-bullshit/chatgpt-api#455]
### Describe the feature

Excuse me, do you have plans to add networking capabilities for ChatGPT API?

like this: https://github.com/tobiasbueschel/search-gpt

**Comment by transitive-bullshit** [comment]
No plan at the moment; it's a really cool feature, but I think it's out of scope for now. You can always implement the search / networking logic on top of the `chatgpt` package.

Thanks! 🙏
