### ISSUE TITLE
import { get_encoding } from "@dqbd/tiktoken" 报错

### ISSUE THREAD

**Issue by wode0weiyi** [transitive-bullshit/chatgpt-api#456]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node 16.13.1
chrome 108.0.5359.71
macOs Catalina

### Describe the Bug

<img width="382" alt="image" src="https://user-images.githubusercontent.com/36390107/223937201-a9b93d42-e7b1-4196-9b80-ccf555435817.png">

**Comment by ishan-flek-ai** [comment]
My issue was I was trying to run in the browser env. This only works in a backend.

**Comment by aslanTT** [comment]
I  got the same error
`      const { ChatGPTAPI } = await import('chatgpt')
      const api = new ChatGPTAPI({
        apiKey: "xxxx"
      })
    
      var error, res;
      [error, res] = await To(api.sendMessage(command))`

I use express

the error is
`SyntaxError: The requested module '@dqbd/tiktoken' does not provide an export named 'get_encoding'`

**Comment by mlsjla** [comment]
me too

**Comment by InsightfulFuture** [comment]
I am using React and I am getting the error `Can't resolve '@dqbd/tiktoken'`.

**Comment by dqbd** [comment]
Hello 😄 

@transitive-bullshit I've released a new major version of tiktoken (`1.0.0`), which should fix bundling issues and clarify the necessary steps needed to support Vite and other browser environments. 

Alternatively, I would suggest using a pure-JS version if browser environment is detected.

**Comment by FerrazLeandro** [comment]
Estou com o mesmo erro, não entendi como resolver :(

**Comment by transitive-bullshit** [comment]
@dqbd awesome; will update now 🚀 

Thanks!!

**Comment by transitive-bullshit** [comment]
@wode0weiyi @dqbd see https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v5.1.2

btw, if you're getting this error, double check that you're not trying to use it from browser / frontend code. This package is focused on Node.js / backend only, and it is not secure to use your OpenAI API key from browser code.

Thanks!

**Comment by transitive-bullshit** [comment]
Closing for now since we've upgraded to a major version bump of `@dqbd/tiktoken`.

If you're still running into this and are sure your code is being run on the backend only, feel free to re-open or create a new issue.

Thanks!
