### ISSUE TITLE
Just Getting "fetch failed" in console

### ISSUE THREAD

**Issue by sromexs** [transitive-bullshit/chatgpt-api#461]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Nothing

### Describe the Bug

i updated to the last version of the app and i getting fetch failed message instead of response

**Comment by transitive-bullshit** [comment]
Make sure you read the readme's "install" instructions. You need node >= 18 or to install a `fetch` polyfill.

**Comment by sromexs** [comment]
ChatGPTUnofficialProxyAPI
i think they blocked the bot api

**Comment by transitive-bullshit** [comment]
Yes, they did. See #453 for details.
