### ISSUE TITLE
How to get the name/title of a conversation?

### ISSUE THREAD

**Issue by Eyon** [transitive-bullshit/chatgpt-api#467]
### Describe the feature

pls let me know?

**Comment by tynguyen** [comment]
I am not so sure what you meant but you can trim() the 1st user message (question) to name the conversation.

**Comment by transitive-bullshit** [comment]
you can use prompt engineering to create a prompt which asks chatgpt what the title of a conversation should be given it's contents.

this is outside the scope of this repo, but you can use the `chatgpt` package to accomplish this 😄 

also see the official examples in https://github.com/openai/openai-cookbook for guidance
