### ISSUE TITLE
can anyone tell me how to build this : https://your-example-server.com/api/conversation

### ISSUE THREAD

**Issue by JeazW** [transitive-bullshit/chatgpt-api#468]
### Describe the feature

anyone succeed?

**Comment by huluohu** [comment]
> ### Describe the feature
> anyone succeed?

no open souce.

**Comment by SmileSmith** [comment]
> ### Describe the feature
> anyone succeed?

if you want build a proxy server, maybe this repo help you : https://github.com/SmileSmith/chatgpt-proxy

**Comment by mengdodo** [comment]
Look readme 

Note: info on how the reverse proxies work is not being published at this time in order to prevent OpenAI from disabling access.

**Comment by transitive-bullshit** [comment]
Closing as off-topic; a better place to discuss these types of topics is in our [ChatGPT Hackers Discord](https://www.chatgpthackers.dev/).
