### ISSUE TITLE
How to set proxy when requesting ChatGPT?

### ISSUE THREAD

**Issue by BobH233** [transitive-bullshit/chatgpt-api#47]
Because my network environment is not that good, I need a proxy option to use the chatgpt

**Comment by transitive-bullshit** [comment]
This is a great feature to add. PRs welcome 😄

**Comment by wlemuel** [comment]
The proxy function has been completed with #78

**Comment by BobH233** [comment]
> The proxy function has been completed with #78

Thank you!

**Comment by TheDAS-designer** [comment]
windows下开发用[这个](https://github.com/shunf4/proxychains-windows), 配置非常简单创建一个文件夹就ok了

**Comment by transitive-bullshit** [comment]
We still need to add support or this, but in general, the new Cloudflare protections have made it much harder to use proxies.

**Comment by mack007liu** [comment]
"Not available
OpenAI's services are not available in your country."  你的创建API没有这个提示吗？我这边用不了他们的api.

**Comment by transitive-bullshit** [comment]
Support added by @waylaidwanderer in https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v3.3.0 🔥

Please open a new issue if you have trouble getting the proxy support working.

Thanks!

**Comment by CiaranYoung** [comment]
cool, need it
