### ISSUE TITLE
model param is not working

### ISSUE THREAD

**Issue by khrigo** [transitive-bullshit/chatgpt-api#472]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

 "chatgpt": "^5.0.9",

### Describe the Bug

```js
new ChatGPTAPI({
    apiKey: process.env.OPENAI_API_KEY,
    model: 'gpt-3.5-turbo'
```

I am passing args about model turbo, but in my usage history used gpt-3.5-turbo-0301

<img width="829" alt="Screenshot 2023-03-15 at 00 59 31" src="https://user-images.githubusercontent.com/6208966/225168192-edf6b9e3-1fb3-4e29-a43b-2081a2e8319a.png">

**Comment by khrigo** [comment]
@transitive-bullshit ok, now I am using text-davinci-002? but in usage it is still gpt-3.5-turbo-0301.

<img width="346" alt="Screenshot 2023-03-15 at 09 10 55" src="https://user-images.githubusercontent.com/6208966/225247022-355615d9-acfe-4c17-b214-20ff8387e964.png">

**Comment by transitive-bullshit** [comment]
@khrigo the chat completions endpoint doesn't support `text-davinci-002`, only the text completions endpoint. since we're using the chat completions endpoint, if you pass an unsupported model, it'll default to `gpt-3.5-turbo`
