### ISSUE TITLE
Unofficial API Proxy Ban

### ISSUE THREAD

**Issue by CMarker** [transitive-bullshit/chatgpt-api#474]
### Describe the feature

This feature should be removed, or more prominent warnings - people who used the default proxy got banned

> What were you using to access ChatGPT? It looks like you were part of the ban of users using unofficial ChatGPT APIs.

comment from discord

**Comment by JunaGanz** [comment]
> It's happened to me

**Comment by transitive-bullshit** [comment]
Yes, OpenAI has been cracking down on the unofficial API, and I'm planning on focusing 100% of my efforts on the official API going forwards. You will **not** get banned using the official API.

If you haven't already switched to using `ChatGPTAPI`, now's a great time to do so.

If you want to discuss the unofficial API or other alternatives more, the best place is our [discord community](https://www.chatgpthackers.dev/) with 7k+ devs.
