### ISSUE TITLE
Incorrect API key error with proxyAPI

### ISSUE THREAD

**Issue by DrakoHyena** [transitive-bullshit/chatgpt-api#478]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node 19
NPM 8.19.2

### Describe the Bug

This code which is exampled on the docs returns this error when running
```js
import {ChatGPTUnofficialProxyAPI} from 'chatgpt'
import Authenticator from "openai-authenticator";

async function example() {
    const auth = new Authenticator()
    await auth.login("<valid acc email>", "<valid acc pass>")
    
    const api = new ChatGPTUnofficialProxyAPI({
        accessToken: auth
    })

    const res = await api.sendMessage('Hello World!')
    console.log(res.text)
}

example()
```
```error
file:///C:/Users/ayden/Downloads/Programs/chatgpt-djs/node_modules/chatgpt/build/index.js:55
    const error = new ChatGPTError(msg, { cause: res });
                  ^

ChatGPTError: ChatGPT error 401: {"detail":{"message":"Incorrect API key provided: [object ***ect]. You can find your API key at https://platform.openai.com/account/api-keys.","type":"invalid_request_error","param":null,"code":"invalid_api_key"}}
```

**Comment by transitive-bullshit** [comment]
@DrakoHyena what error did you run into with `openai-authenticator`? cc @acheong08 who's the author

**Comment by acheong08** [comment]
The JS version of `openai-authenticator` isn't mine.

**Comment by acheong08** [comment]
But this doesn't look like a suspension unlike
- https://github.com/acheong08/ChatGPT/issues/1158

**Comment by transitive-bullshit** [comment]
Thanks @acheong08

For now, I strongly recommend switching to using the official API via `ChatGPTAPI`.

**Comment by acheong08** [comment]
I just checked and the Python version is working. No API change with authentication
