### ISSUE TITLE
TypeError: fetch failed | or fails silently

### ISSUE THREAD

**Issue by Elitezen** [transitive-bullshit/chatgpt-api#482]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

- Node.js v18.3.0
- Chrome Version 111.0.5563.65 (Official Build) (64-bit)
- Windows 11 Home 10.0.22621 Build 22621

### Describe the Bug

This library was working fine a day earlier. However, I now get following error:

```ssh
node:internal/deps/undici/undici:5536
          p.reject(Object.assign(new TypeError("fetch failed"), { cause: response.error }));
                                 ^

TypeError: fetch failed
    at Object.processResponse (node:internal/deps/undici/undici:5536:34)
    at node:internal/deps/undici/undici:5858:42
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (C:\Users\aleja\Documents\workspace\npm_modules\discordjs-chatgpt\node_modules\undici\lib\core\connect.js:182:24)
      at C:\Users\aleja\Documents\workspace\npm_modules\discordjs-chatgpt\node_modules\undici\lib\core\connect.js:129:46
      at Immediate._onImmediate (C:\Users\aleja\Documents\workspace\npm_modules\discordjs-chatgpt\node_modules\undici\lib\core\connect.js:168:33)
      at process.processImmediate (node:internal/timers:471:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
```

This will occur rarely. Currently, the vast majority of my attempts fail silently and I do not get any sort of response even when using streaming with `onProgress()`

```js
const api = new ChatGPTAPI({
  apiKey: '...'
})
  
const res = await api.sendMessage('Hello World!', {
  onProgress: (partialResponse) => console.log(partialResponse.text)
})

console.log(res.text)
```

Chat-GPT responds fine on OpenAI

**Comment by transitive-bullshit** [comment]
OpenAI's API has been having some downtime today Check their status page for details.

**Comment by transitive-bullshit** [comment]
https://status.openai.com/

**Comment by cyrusssschen** [comment]
getting the same error today.

**Comment by ChuckJonas** [comment]
ya this library seems to fail silently without throwing.  Seems like every other request hangs indefinitely.   I'm running a the equivalent fetch query in parallel just to see if it's a server issue and it responds every time.

This, plus the lack of commonjs support making it a pain to use this library in legacy project, plus the stateful design has me looking for something else.

Anyone know if there is a lightweight npm package that pretty much just provide typed guardrails for interacting with the openAI apis?

**Comment by transitive-bullshit** [comment]
I see this occasionally from OpenAI's API. Unfortunately, I don't think there's much we can do about it.

If anyone finds more information and is able to create a reproducible test case for this, I'd be interested in a follow-up.

Closing for now as unfortunately not actionable on our end.
