### ISSUE TITLE
ChatGPTError: ChatGPT error 500: Internal Server Error Used with ChatGPTUnofficialProxyAPI

### ISSUE THREAD

**Issue by ashuvax** [transitive-bullshit/chatgpt-api#483]
### Verify latest release

- [x] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node: v17.4.0

### Describe the Bug

I am using with ChatGPTUnofficialProxyAPI
And after every few requests I get ChatGPTError: ChatGPT error 500: Internal Server Error

**Comment by transitive-bullshit** [comment]
This may happen from time to time if you're trying to use unofficial proxies. See https://github.com/transitive-bullshit/chatgpt-api/issues/453 for details.

Note: I do not plan to support the unofficial proxy APIs for much longer. Now that the official OpenAI chat completion API is stable, I strongly recommend migrating over to it.
