### ISSUE TITLE
Why conversationId is not working?

### ISSUE THREAD

**Issue by khrigo** [transitive-bullshit/chatgpt-api#484]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

last version

### Describe the Bug

I am using conversationId in request tot ChatGPT:
<img width="499" alt="Screenshot 2023-03-20 at 12 27 23" src="https://user-images.githubusercontent.com/6208966/226326487-6b755a58-f4cf-44bc-9ee5-96be908d3b4e.png">
But it is not working, all massages answered with another id and chat does not remember previous messages:
<img width="804" alt="Screenshot 2023-03-20 at 12 28 55" src="https://user-images.githubusercontent.com/6208966/226326809-8babff8f-a296-4d6b-be2d-8bc8b98670ee.png">

**Comment by transitive-bullshit** [comment]
There is no `conversationId` with `ChatGPTAPI`. Only `parentMessageId`.

The unofficial proxy API requires both `conversationId` and `parentMessageId`. If you only pass one, it won't work.

**Comment by kuangxiaoye** [comment]
I want to achieve multi-user use, conversationId seems to be indispensable, why has this parameter been ignored so far?
