### ISSUE TITLE
Can you make a function that supports systemMessages  for ChatGPTUnofficialProxyAPI

### ISSUE THREAD

**Issue by zhengdechang** [transitive-bullshit/chatgpt-api#488]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

none

### Describe the Bug

I want to use token access and then carry systemM
essage

**Comment by zhengdechang** [comment]
I did not see the promptPrefix parameter in the ChatGPTAPIOptions type,Can you provide examples?

**Comment by ashuvax** [comment]
@transitive-bullshit We would be happy to receive your answer, it's important to me too
