### ISSUE TITLE
Callout the stateful nature of "parentMessageId" in the docs

### ISSUE THREAD

**Issue by ChuckJonas** [transitive-bullshit/chatgpt-api#489]
### Describe the feature

If you aren't familiar with the ChatGPT API, you probably will think that `parentMessageId` is a feature of the OpenAI API itself.  I had to dig into the code just to double check it wasn't some "undocumented" feature.

Instead it is a stateful implementation, locally managed by and scoped to each instantiated client.   This makes the library a bad choice for stateless use-cases like serverless functions (at least until https://github.com/transitive-bullshit/chatgpt-api/issues/416 is implemented).

I think it would be worth adding a note to the readme so developers understand the limitations of `parentMessageId`.

**Comment by transitive-bullshit** [comment]
this is a very good point.

this package has gone through many iterations over the past few months, and what previously worked well for the unofficial api may no longer be the best SDK for the official api.

i'm considering removing all of the stateful aspects of this library related to `keyv` and pushing these responsibilities up to the user of this package. this would take care of most of these types of issues / feedback, and it would make this package simpler.

the downside to this change is that it wouldn't "just work" for some users.

100% agreed that I'd like to support stateless serverless functions (and edge functions!). a previous version of this package explicitly supported vercel and CF edge functions. I'd love to make this work again, including proper streaming support.

the challenge for me is bandwidth. I have so many other things I'm excited to build with AI that properly maintaining this package now that the official api has released has become more of a chore than something I look forward to.

thanks for your great feedback && I'm very open to these changes + PRs. I won't always be able to review them right away, but I will get to them eventually 🙏  I also respond more quickly on our [chatgpt hackers discord](https://www.chatgpthackers.dev/)

**Comment by transitive-bullshit** [comment]
this issue directly affects #519, #517, #503, #490, #436, and probably others I'm missing. it's an important issue that causes a lot of other smaller issues, so thanks for calling it out @ChuckJonas 🙏

**Comment by ChuckJonas** [comment]
The approach I ended up with was a bare bones, stateless API client and then a stateful lib for caching and restoring message history (similar in approach to this library, but bit more flexible). This simple composition allows for both ease of use & complete control.

Ends up looking something like this:

```typescript
const { getChat, addChat } = initMessageStore(new Keyv<ChatClientResult>());
const chatClient = initChatClient({ token: process.env.OAI_TOKEN });

//one shot setup
const result1 = await chatClient([
   { role: "system", content: "Your job is to determine if a text pertains to music or not" },
   { role: "user", content: "Who are the members of the Beatles?" },
   { role: "assistant", content: "music" },
   { role: "user", content: "List the planets in our solar system, ordered by size:" },
   { role: "assistant", content: "not_music" },
   { role: "user", content: userQuery1 }
]);

addChat(result1);

const previousChat = getChat(result1.id);

const result2 = await chatClient([
   ...previousChat.messages, 
   { role: "user", content: userQuery2 }
]);
```

Although I think moving towards this type of approach would be a major departure for this project...

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
