### ISSUE TITLE
Why throw this error (`ChatGPTAPI error ${res.status || res.statusText}`)

### ISSUE THREAD

**Issue by AutumnWhj** [transitive-bullshit/chatgpt-api#49]
```
file:///code/node_modules/chatgpt/src/fetch-sse.ts:13
    throw new Error(`ChatGPTAPI error ${res.status || res.statusText}`)
          ^
Error: ChatGPTAPI error 503
    at fetchSSE (file:///code/node_modules/chatgpt/src/fetch-sse.ts:13:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
env version: node: 16.18.0

<img width="602" alt="image" src="https://user-images.githubusercontent.com/39156049/206262609-7d1de5a4-8df3-46d1-b1bb-6d64620f7546.png">

**Comment by transitive-bullshit** [comment]
This means that the ChatGPT API returned an [HTTP 503 error.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503) 

This is likely due to OpenAI's servers being slammed.

**Comment by AutumnWhj** [comment]
thanks
