### ISSUE TITLE
Is there a plan to support Azure OpenAI?

### ISSUE THREAD

**Issue by stulzq** [transitive-bullshit/chatgpt-api#492]
### Describe the feature

Api Doc：https://learn.microsoft.com/en-us/azure/cognitive-services/openai/chatgpt-quickstart?tabs=command-line&pivots=rest-api

**Comment by transitive-bullshit** [comment]
Yes, this is planned.

Closing as a duplicate of https://github.com/transitive-bullshit/chatgpt-api/issues/352
