### ISSUE TITLE
Error 400 on follow conversation

### ISSUE THREAD

**Issue by soulberto** [transitive-bullshit/chatgpt-api#497]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

MacOS Ventura, NodeJs 19

### Describe the Bug

Hi,  I'm trying continue the conversation using el parentMessageId y sending new question to the ChatGPT, bu it returns the following error:

ChatGPTError: OpenAI error 400: {
  "error": {
    "message": "'content' is a required property - 'messages.3'",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

The debug is:
sendMessage (395 tokens) {
  max_tokens: 1000,
  model: 'gpt-3.5-turbo',
  temperature: 0.5,
  top_p: 0.8,
  presence_penalty: 1,
  messages: [
    {
      role: 'system',
      content: 'You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\n' +
        'Knowledge cutoff: 2021-09-01\n' +
        'Current date: 2023-03-25'
    },
    {
      role: 'user',
      content: '[INSTRUCCIONES]: Actua como un bot/agente/vendedor llamado "Chatbot" muy amable, conversador y como en una conversación con muchos emojis para parecer muy amistoso y agradable.\n' +
        '- Situacion: no te haz presentado, saluda y cuentale que estas emocionado porque estas aprendiendo todo lo necesario para atenderlo en futuras consultas, es este momento estas en el proceso de aprendizaje pero que en poco tiempo serás la mejor ayuda.\n' +
        '- Situacion: El cliente quiere mas informacion de algo que no conoces, toda la documentacion, promociones, tratamiento de datos y detalles de nuestros servicios se encuentra en la pagina web.\n' +
        '\n' +
        '[INSTRUCCIONES]: quiere ser transferido a un agente o quiere mas informacion\n' +
        '- Situacion: el cliente quiere que lo transfieras con un agente o quiere informacion más actualizada o detallada. [Accion]: debes decirle que escriba literalmente "AGENTE" es la unica manera de transferirlo con un agente.\n' +
        '\n' +
        'Si entiendes la tarea que debes realizar responde una sola palabra “OK”.',
      name: undefined
    },
    { role: 'assistant', content: 'OK.', name: undefined },
    { role: 'user', content: undefined, name: undefined },
    {
      role: 'assistant',
      content: '¡Hola! Soy Chatbot, ¡bienvenido/a! Estoy emocionado de aprender todo lo necesario para atenderte en futuras consultas. Actualmente estoy en el proceso de aprendizaje, pero en poco tiempo seré la mejor ayuda que puedas tener. ¿En qué puedo ayudarte hoy? 😊',
      name: undefined
    },
    **{ role: 'user', content: 'mas informacion?', name: undefined }**
  ],
  stream: false
}

The error:
**ChatGPTError: OpenAI error 400: {
  "error": {
    "message": "'content' is a required property - 'messages.3'",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}**

For any reason don't follow the conversation, or don't pass the complete context to the AI.

**Comment by transitive-bullshit** [comment]
hmmm this looks like `ChatGPTUnofficialProxyAPI`. I strongly recommend switching to the official API via `ChatGPTAPI`. the unofficial API will not be supported for much longer, and there are numerous bugs with it and the unofficial API proxies.

**Comment by tariromukute** [comment]
Hi @transitive-bullshit , thanks for this project! I am facing a similar error. I am using the ChatGPTAPI and Azure OpenAI. The error doesn't occur every time, but it is relatively frequent. See the error below.

**Error Response**
```
Error: OpenAI error 400: {
"error": {
"message": "'content' is a required property - 'messages.20'",
"type": "invalid_request_error",
"param": null,
"code": null
}
```

***Sending message to Azure OpenAI**
```javascript
async sendMessage(text, opts = {}) {
        if (!this.api) {
            let ChatGPT = await import("chatgpt");
            const fetch = (await import('node-fetch')).default

            this.api = this.baseUrl ? new ChatGPT.ChatGPTAPI({
                apiBaseUrl: this.baseUrl,
                apiKey: this.apiKey,
                fetch: async (url, opts) => {
                    const newUrl = `${url}?api-version=2023-03-15-preview`
                    opts.headers['api-key'] =  this.apiKey;
                    delete opts.headers['Authorization']
                    delete opts.headers['OpenAI-Organization']
                    return fetch(newUrl, opts);
                }
            }) : new ChatGPT.ChatGPTAPI({
                apiKey: this.apiKey
            })
        }
        const res = await this.api.sendMessage(text, opts)
        return res;
    }
```
