### ISSUE TITLE
Defer saving new message(question) in ChatGPTAPI.sendMessage

### ISSUE THREAD

**Issue by 189** [transitive-bullshit/chatgpt-api#503]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Nodejs 16.17.0
Windows 11

### Describe the Bug

Saving the new message/question before receive response from openAI will cause something unexpected. 

For some reasons (bad network, rate-limit, or user cancel or withdraw the request,  so on), the request send to `api.openai.com` will be failed/abort, and the result will not be saved. But the user's message(user's question) has been saved before request sent, make it become orphan in database, no parentMessageId will point to it。If we query all message according conversationId from database, the orphan message will be received, it's redundant

**Comment by transitive-bullshit** [comment]
merged #504 – thanks @189 🙏 

new release will be published shortly
