### ISSUE TITLE
getting _undici.fetch error

### ISSUE THREAD

**Issue by dskill** [transitive-bullshit/chatgpt-api#51]
I'm getting this error when authenticating, but I did verify I have the undici library installed.  I'm on windows... maybe doing something dumb?

(node:11744) UnhandledPromiseRejectionWarning: Error: ChatGPT failed to refresh auth token. TypeError: _undici.fetch is not a function

**Comment by dskill** [comment]
i verified my SESSION_TOKEN is correct and I can still use the earlier version of chatgpt (1.4.0)

**Comment by dskill** [comment]
Oh!  As I was pasting my dependencies output I saw an extremely helpful (and something I should have caught earlier) note that I'm on an older and unsupported version of node (14). 

I updated to a newer version and now chatgpt works.  Thanks!

**Comment by transitive-bullshit** [comment]
Thanks @dskill 

I just released an update that throws a better error if this is the case https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v2.0.4

**Comment by dskill** [comment]
awesome. thx for making this amazing project happen!
