### ISSUE TITLE
Do I need to check `message_type`

### ISSUE THREAD

**Issue by bincooo** [transitive-bullshit/chatgpt-api#512]
### Describe the feature

Do I need to check `message_type`?
```code
{"message_type": "next", "model_slug": "text-davinci-002-render-sha"}
```
When the data is "prompt" too much, it will return the user's 'prompt' !

**Comment by transitive-bullshit** [comment]
`message_type` is an internal implementation detail in the unofficial chatgpt webapp's api. you can safely ignore it.

I strongly recommend switching to the official chatgpt api via `ChatGPTAPI`. the unofficial api will not be supported for much longer going forwards.
