### ISSUE TITLE
 Dynamically set maxResponseTokens and maxModelTokens

### ISSUE THREAD

**Issue by markNZed** [transitive-bullshit/chatgpt-api#515]
### Describe the feature

 Do we need to be able to dynamically set: maxResponseTokens and maxModelTokens with sendMessage ? Is it possible to do this with the OpenAI API ?

**Comment by transitive-bullshit** [comment]
currently, you can just re-create the `ChatGPTAPI` each time you want to reset these parameters since they're tied to `completionParams.model`

we don't currently have a way of setting `completionParams` and these related options on a `sendMessage` basis.

**Comment by christophebe** [comment]
And what about other params like presence_penalty, top_p, ... ? Is it possible to change their value when calling sendMessage ? 

I would like to track the conversation but change the parameters in function of my prompt (sendMessage).

**Comment by christophebe** [comment]
Sorry, I didn't see this : https://github.com/transitive-bullshit/chatgpt-api/issues/434
