### ISSUE TITLE
When I use onProgress, parentMessageId can not work

### ISSUE THREAD

**Issue by Maikscau** [transitive-bullshit/chatgpt-api#519]
`###` Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node v16

### Describe the Bug

```
const res = await api.sendMessage(params.query, {
  parentMessageId: params.parentMessageId,
  onProgress: (partialResponse) => {
     console.log(partialResponse)
  },
})
```

**Comment by Jakeroid** [comment]
I have same issue.

**Comment by rifalgrp** [comment]
same here, parent id not work

**Comment by hongguang-alt** [comment]
I am same issue.

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
