### ISSUE TITLE
It lets' sendMessage 'unblock early, but' onMessage 'still executes.

### ISSUE THREAD

**Issue by bincooo** [transitive-bullshit/chatgpt-api#521]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Nodejs18
chatgpt > "5.2.2"

### Describe the Bug

https://github.com/transitive-bullshit/chatgpt-api/blob/07dcc5df31476fb773a46d103136632e12762179/src/chatgpt-unofficial-proxy-api.ts#L221

========
Do you mean anything by 'reject(err)'?
It lets' sendMessage 'unblock early, but' onMessage 'still executes.
So, I can't tell when it's over.

**Comment by transitive-bullshit** [comment]
it'd prolly be nice to add a flag and some logic to not call `onProgress` and `onMessage` in this case, but it should be pretty rare.

also, I strongly recommend switching to the official api via `ChatGPTAPI`. the unofficial api is not reliable
