### ISSUE TITLE
How about making voice AI?

### ISSUE THREAD

**Issue by hartpoli** [transitive-bullshit/chatgpt-api#522]
### Describe the feature

writing text with AI.

**Comment by transitive-bullshit** [comment]
definitely a great feature; there are lots of STT (speech-to-text) APIs out there :)

I'd like to keep this module focused on core chat functionality, but it's 100% possible to build voice STT & TTS on top of this package

thanks!

**Comment by hartpoli** [comment]
impatient to wait. 

Good luck!
