### ISSUE TITLE
Are there other APIs planned to connect with the official website?

### ISSUE THREAD

**Issue by ltinerary** [transitive-bullshit/chatgpt-api#523]
### Describe the feature

**Such as：[Audio api](https://platform.openai.com/docs/api-reference/audio/create)、[Image api](https://platform.openai.com/docs/api-reference/images/create)?**

Although they are still in Beta

---------------------------------------------------------

![image](https://user-images.githubusercontent.com/79144923/229715390-84109278-8a3f-4fb3-af52-afa59d8b910d.png)
[CHATGPT API REFERENCE](https://platform.openai.com/docs/api-reference/introduction)

**Comment by transitive-bullshit** [comment]
You're looking for the official OpenAI npm package here: https://github.com/openai/openai-node

This package is focused solely on chatgpt-like functionality wrapping the official OpenAI chat completions API.
