### ISSUE TITLE
SyntaxError: Unexpected number in JSON at position

### ISSUE THREAD

**Issue by leochen-g** [transitive-bullshit/chatgpt-api#526]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

When I was using the UnofficialProxyAPI and used the await method to wait for the results to return, I received a JSON parsing error.

### Describe the Bug

After debugging, I found that there is a time interval when querying a specific question, which causes the JSON parsing to fail. The question is `我需要写一个wechaty的功能介绍`， I have tried this issue many times and encounter the same problem every time.

```
...
const chatGPT = new ChatGPTUnofficialProxyAPI({...})
const { conversationId, text, id } = await chatGPT.sendMessage(content);
...
```

<img width="937" alt="image" src="https://user-images.githubusercontent.com/20028566/230082557-e53bfb42-c7fc-494c-a4a6-a316c985d66e.png">
<img width="685" alt="image" src="https://user-images.githubusercontent.com/20028566/230082615-ac84c210-f33e-4627-9eab-d5822775d51b.png">

**Comment by liunice** [comment]
yes, I just encountered this issue a few minutes ago with UnofficialProxyAPI...

**Comment by Prottoy2938** [comment]
same here

**Comment by ashuvax** [comment]
I also encountered a problem, we would appreciate it if you could fix it as soon as possible

**Comment by ElenaChes** [comment]
Been encountering this error a lot lately as well

**Comment by KirillPirinen** [comment]
is there any updates ?

**Comment by Jxells** [comment]
也遇到了一样的问题

**Comment by transitive-bullshit** [comment]
Thanks for the report, @leochen-g.

Closing as a duplicate of #557. See my previous response there https://github.com/transitive-bullshit/chatgpt-api/issues/557#issuecomment-1530795074
