### ISSUE TITLE
Additional properties are not allowed ('id' was unexpected) - 'messages.0'

### ISSUE THREAD

**Issue by leviluo** [transitive-bullshit/chatgpt-api#531]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

nodejs 18.15

### Describe the Bug

my code:
const { ChatGPTUnofficialProxyAPI } = await import('chatgpt')
			const api = new ChatGPTUnofficialProxyAPI({
				model:"gpt-3.5-turbo",
				accessToken: "sk-**********",
				apiReverseProxyUrl: 'https://*******/v1/chat/completions'
			})
			const res = await api.sendMessage(text)

reply:
Error: ChatGPT error 400: {
    "error": {
      "message": "Additional properties are not allowed ('id' was unexpected) - 'messages.0'",
      "type": "invalid_request_error",
      "param": null,
      "code": null
    }
  }

**Comment by walker-peng22** [comment]
same

**Comment by gvao** [comment]
some

**Comment by TimGin117** [comment]
same，I change to opanai npm (

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
