### ISSUE TITLE
Fetch failed

### ISSUE THREAD

**Issue by laza-niaina** [transitive-bullshit/chatgpt-api#536]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [x] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

**Node.js** version 18.12.1 

### Describe the Bug

**Error: Client network socket disconnected before secure TLS connection was established**

`  code: 'ECONNRESET',

    path: undefined,

    host: 'explorer.api.openai.com',

    port: 443,

    localAddress: undefined`

**Comment by transitive-bullshit** [comment]
`explorer.api.openai.com` was an old endpoint which is unofficial and deprecated.

I think you're experiencing an error trying to use one of the unofficial API auth token fetchers, which is unrelated to this repo and not supported by this package.

You may want to try asking for help in our discord https://www.chatgpthackers.dev
