### ISSUE TITLE
使用第三方反代报错

### ISSUE THREAD

**Issue by sadasdfrex** [transitive-bullshit/chatgpt-api#539]
### Describe the feature

<img width="321" alt="image" src="https://user-images.githubusercontent.com/129033354/232673696-57b679e3-b5d6-42b6-aeb5-d90a0c91811b.png">
<img width="448" alt="image" src="https://user-images.githubusercontent.com/129033354/232673734-5b69148d-7b5f-4a40-848f-88d31c11804b.png">

**Comment by transitive-bullshit** [comment]
For any questions regarding the unofficial API proxies, please ask in https://www.chatgpthackers.dev
