### ISSUE TITLE
When I use the Onprogress mode, I cannot display tokens

### ISSUE THREAD

**Issue by nightwhite** [transitive-bullshit/chatgpt-api#541]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node 18

### Describe the Bug

When I use the Onprogress mode, I cannot display tokens

![image](https://user-images.githubusercontent.com/22722256/232959090-4d1b8372-3a99-4152-b1a0-e9daebc50b0b.png)

and Onprogress mode without usage

![image](https://user-images.githubusercontent.com/22722256/232959489-e7643857-6b82-413d-a240-f946474919ee.png)

**Comment by Boyuan-Deng** [comment]
Experienced the same problem

**Comment by transitive-bullshit** [comment]
You're seeing the `delta` be empty for every `onProgress` call?

Does the provided example `demos/demo-on-progress.ts` work for you?

```ts
  const api = new ChatGPTAPI({ apiKey: process.env.OPENAI_API_KEY })

  const prompt =
    'Write a python version of bubble sort. Do not include example usage.'

  console.log(prompt)
  const res = await api.sendMessage(prompt, {
    onProgress: (partialResponse) => {
      console.log(partialResponse.text)
    }
  })
  console.log(res.text)
```

This code works as expected for me, so there's probably something subtle going on here.

Can you provide more details on how you're invoking `sendMessage`?

Thanks!

**Comment by nightwhite** [comment]
> 

The code of code is the same as you, but there is no token about consumed in the res

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
