### ISSUE TITLE
Make maximum context length limit

### ISSUE THREAD

**Issue by rever273** [transitive-bullshit/chatgpt-api#542]
### Describe the feature

Using chatgpt-3.5-turbo I have an error:

```
"error": {
    "message": "This model's maximum context length is 4097 tokens. However, you requested 4562 tokens (3062 in the messages, 1500 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
```

I use **max_tokens: 1500** parameter, but as I can see, it doesn't work.

Can you add **maximum context length** option?

**Comment by transitive-bullshit** [comment]
hmmm can you give more details on how you're invoking this library, both the constructor and your call to `sendMessage`?

We already have logic which is supposed to protect against this issue to constrain the maximum context length, but it's definitely not bulletproof.

**Comment by rever273** [comment]
Hi. Here:
`
const { ChatGPTAPI } = await import('chatgpt');

api = await new ChatGPTAPI({
    apiKey: config.chatGPT_api_key,
    completionParams: {
        model: "gpt-3.5-turbo",
        max_tokens: 1500,
        //temperature: temperature,
        top_p: 0.4
    }
})
`
And sending message:
`
const res = await api.sendMessage(user_text, {
    timeoutMs: 5 * 60 * 1000,
    systemMessage = 'bla bla bla',
    conversationId = user_data.conversationId || '',
    parentMessageId = user_data.parentMessageId
});
`

If I send very big prompt (full detailed description) and do not mention in the text "set maximum token amount 1500", the error occur sometime.

**Comment by longyanjiang** [comment]
The same issue seems to have appeared in the latest version

**Comment by longyanjiang** [comment]
"error": {
      "message": "This model's maximum context length is 4097 tokens. However, you requested 4346 tokens (2298 in the messages, 2048 in the completion). Please reduce the length of the messages or completion.",
      "type": "invalid_request_error",
      "param": "messages",
      "code": "context_length_exceeded"
    }
  }
      at fetchSSE (file:///root/nineai/node_modules/.pnpm/chatgpt@5.2.4/node_modules/chatgpt/src/fetch-sse.ts:27:19)
      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    statusCode: 400,
    statusText: 'Bad Request',
    [cause]: Response {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
      [Symbol(Response internals)]: {
        url: 'https://api.openai.com/v1/chat/completions',
        status: 400,
        statusText: 'Bad Request',
        headers: [Headers],
        counter: 0
      }
    }
  }

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
