### ISSUE TITLE
allow to pass callback to debug function to prefix logs ?

### ISSUE THREAD

**Issue by mtariqsajid** [transitive-bullshit/chatgpt-api#544]
### Describe the feature

is there a way pass callback to debug function instead of standout out. or maybe sendMessage function return more detail when debug is set to true.

maybe something like this

```js
  const chatGPT= new ChatGPTAPI({
      apiKey: OPENAI_API_KEY,
      completionParams: {
        model: OPENAI_MODEL,
      },
      debug: (parms1 , parms2) => {
        console.log('### my prefix  ###', parms1);
      }
    });
```

**Comment by transitive-bullshit** [comment]
I think you probably want to pass a custom `log` function which isn't currently supported.

Would be a great feature request, though.

**Comment by mtariqsajid** [comment]
any update on this @transitive-bullshit

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
