### ISSUE TITLE
error FetchError: request to https://api.openai.com/v1/chat/completions failed reason: connect ETIMEDOUT

### ISSUE THREAD

**Issue by lok6666** [transitive-bullshit/chatgpt-api#545]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node v18.16.0
win 10

### Describe the Bug

node v18.16.0
import { ChatGPTAPI } from 'chatgpt'
// fixed load esm module
export const importDynamic = new Function(
  'modulePath',
  'return import(modulePath)',
);
let fetch = await importDynamic('node-fetch');
fetch = fetch.default;
async function example() {
  const api = new ChatGPTAPI({
    apiKey: 'apiKey',
    fetch
  })

  const res = await api.sendMessage('Hello World!')
  console.log(res.text)
}

(async() => {
    try {
      await example()
    } catch (error) {
      console.log('------', error);
    }
})()

------ FetchError: request to https://api.openai.com/v1/chat/completions failed, reason: connect ETIMEDOUT 157.240.2.14:443

**Comment by transitive-bullshit** [comment]
timeouts may happen from time to time. this is a general networking thing that we unfortunately don't have any control over.

If this is happening consistently for you, then there may be a problem with your setup.

taking a quick look at your code snippet, it looks like you're using `node-fetch` which is not standard. In node.js >= 18, `fetch` is available by default. You do not need to install a polyfill such as `node-fetch`, and if you do try to replace the system `fetch` with `node-fetch`, bad things are likely to happen. this is most likely the crux of your problem.
