### ISSUE TITLE
offer free proxy

### ISSUE THREAD

**Issue by gcslaoli** [transitive-bullshit/chatgpt-api#549]
### Describe the feature

https://freechat.xyhelper.cn/backend-api/conversation
this is my free proxy, support this repo

**Comment by Ghost3972** [comment]
It works well,thanks

**Comment by zjy2931** [comment]
how to use it？

**Comment by transitive-bullshit** [comment]
Thanks @gcslaoli 

For anyone else looking for this type of functionality, you can check out our discord: https://www.chatgpthackers.dev

Note, however, that I strongly encourage you to use the official API. It is much more robust and will be the only API supported long-term.
