### ISSUE TITLE
[Request] Supports event-streams

### ISSUE THREAD

**Issue by gtk2k** [transitive-bullshit/chatgpt-api#55]
By supporting event-stream, the response will be experientially faster.
![image](https://user-images.githubusercontent.com/309829/206372280-f8266ba6-d080-4092-be08-cd608fd5e52c.png)

**Comment by transitive-bullshit** [comment]
@gtk2k we're already using an event-stream parser for responding to the request. Is there a specific change that you're suggesting?

**Comment by transitive-bullshit** [comment]
I just performed a few tests with and without the `Accept: 'text/event-stream'` header. I wasn't able to notice any significant difference between the two.

One thing to keep in mind is that it can feel like the responses take longer when you're not seeing the partial response as ChatGPT is "typing". If you compare the time it takes to fully resolve an `api.sendMessage` vs your browser devtools, it will be very similar.

To view the stream of partial responses with `chatgpt`, you can use the `onProgress` or `onConversationResponse` parameters to `api.sendMessage`.

**Comment by gtk2k** [comment]
Thank you. I got the expected behavior.
If possible, it would be nice if onProgress was also written in the README.

**Comment by transitive-bullshit** [comment]
Just added a note to the readme 👍
