### ISSUE TITLE
How can you use the promptPrefix in the ChatGPTUnofficialProxyAPI?

### ISSUE THREAD

**Issue by ashuvax** [transitive-bullshit/chatgpt-api#550]
### Describe the feature

How can you use the promptPrefix in the ChatGPTUnofficialProxyAPI?

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
