### ISSUE TITLE
SyntaxError: Unexpected non-whitespace character after JSON at position 4

### ISSUE THREAD

**Issue by seckingyo** [transitive-bullshit/chatgpt-api#555]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node v20

### Describe the Bug

SyntaxError: Unexpected non-whitespace character after JSON at position 4

while using 

import { ChatGPTUnofficialProxyAPI } from '../src'

**Comment by Jxells** [comment]
出现了同样的问题
