### ISSUE TITLE
https://api.pawan.krd/backend-api/conversation	 Not working

### ISSUE THREAD

**Issue by seckingyo** [transitive-bullshit/chatgpt-api#556]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

https://api.pawan.krd/backend-api/conversation	api not working

please fix or remove

### Describe the Bug

https://api.pawan.krd/backend-api/conversation	api not working

please fix or remove

**Comment by transitive-bullshit** [comment]
You can ask questions about unofficial API proxies in https://www.chatgpthackers.dev

I will likely be removing this soon. Thanks for bringing it to my attention. Note that I strongly recommend using the official API via `ChatGPTAPI` instead of the deprecated unofficial API proxies.
