### ISSUE TITLE
SyntaxError: Unexpected number in JSON at position 4

### ISSUE THREAD

**Issue by kirito141211** [transitive-bullshit/chatgpt-api#557]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node v18.12.1

### Describe the Bug

When I use ChatGPTUnofficialProxyAPI, "SyntaxError: Unexpected number in JSON at position 4" happens sometimes .
I found the point of the problem here`chatgpt/src/chatgpt-unofficial-proxy-api.ts:197:22`
OPENAI will send data like "2023-05-01 02:34:13.241659"
It's not a json, so the bug happens
Please fix it, thank you.

**Comment by transitive-bullshit** [comment]
I'm likely going to deprecate the unofficial API soon due to too many issues like this. See also https://github.com/transitive-bullshit/chatgpt-api/issues/453

**Comment by transitive-bullshit** [comment]
The latest release relaxes the JSON parsing for the unofficial API which should resolve this issue: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v5.2.4

Please re-open if you're still seeing it.
