### ISSUE TITLE
Hope to add the ability to clear historical conversations

### ISSUE THREAD

**Issue by Jxells** [transitive-bullshit/chatgpt-api#558]
### Describe the feature

Can you add a function to clear the history dialog, like the official clear dialog, thank you.
![image](https://user-images.githubusercontent.com/94813798/235569987-a5dd4a5c-f710-4e8e-85cf-59f9e7e2ad38.png)

**Comment by transitive-bullshit** [comment]
We're focusing more on the official OpenAI chat completions API and moving away from the unofficial ChatGPT webapp's API (which is not official supported by OpenAI and is unlikely to be supported by them in the future).

For the official API `ChatGPTAPI`, there is no persistent / stored conversations on OpenAI's side of things, so the clear conversations functionality doesn't apply. You have access to the local KV store if you'd like to clear it at any point.

Hope that makes sense && thanks!
