### ISSUE TITLE
ChatGPTUnofficialProxyAPI GPT-4

### ISSUE THREAD

**Issue by joseph27** [transitive-bullshit/chatgpt-api#560]
### Describe the feature

Greetings,
I have openaI API access but chatgpt-4 is not available for me yet, at the same time I have a plus chatgpt account with Chatgpt 4 accesss. can i use the ChatGPTUnofficialProxyAPI to  access the chatgpt 4 ( knowing that the limit is about 25 msgs every 3 hours).

Looking forward to hearing a response.

**Comment by trentluo** [comment]
yes you can use gpt4,just past the parameter like this    model: 'gpt-4'

**Comment by andrewoodleyjr** [comment]
@trentluo The model: `gpt-4` does not exist"

**Comment by simonwcode** [comment]
const uapi = new ChatGPTUnofficialProxyAPI({		
		accessToken:"xxxxxxxxxx",
		apiReverseProxyUrl: "https://ai.fakeopen.com/api/conversation",
		completionParams: {
			model: 'gpt-4',
			temperature: 0.2,
		  }
	});
it does not work, still show gpt3.5 model, I also want to know how to make it supprot gpt-4, looks dont have place to input puid

**Comment by chichuchi** [comment]
> @trentluo The model: `gpt-4` does not exist"

I have the same prob :/

**Comment by ViniChab** [comment]
Same here
I have access to ChatGPT 4 and wanted to use ChatGPTUnofficialProxyAPI with it :(

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
