### ISSUE TITLE
Feat: Support proxy 

### ISSUE THREAD

**Issue by bumu** [transitive-bullshit/chatgpt-api#563]
### Describe the feature

Due to the Chinese mainland cannot use oepnai directly. 

Does it possible support custom BaseURL for call openai proxy address? 
https://github.com/transitive-bullshit/chatgpt-api/blob/main/src/chatgpt-api.ts#LL55C9-L55C9

**Comment by Grey0520** [comment]
yeah, I am Chinese man.

Luckily, you can add this:

``` js
const api = new ChatGPTAPI({
        apiKey: process.env.OPENAI_API_KEY,
        apiBaseUrl: 'https://proxy_address/v1',
        completionParams: {
          model: 'gpt-3.5-turbo',
          temperature: 0.5,
          top_p: 0.8,
        },
      })
```

**Comment by bumu** [comment]
@Grey0520  thank you so much.
