### ISSUE TITLE
Incorrent value of maxModelTokens for gpt-3.5-turbo

### ISSUE THREAD

**Issue by yaojingguo** [transitive-bullshit/chatgpt-api#566]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node version: v16.16.0
macOS 12.4

### Describe the Bug

https://github.com/transitive-bullshit/chatgpt-api/blob/main/src/chatgpt-api.ts#L60 sets `maxModelTokens = 4000`.
But [gpt-3.5-turbo](https://platform.openai.com/docs/models/gpt-3-5) `max tokens` setting is 4096.

Should we set maxModelTokens to 4096?

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
