### ISSUE TITLE
Model gpt 4 don't work

### ISSUE THREAD

**Issue by photoongit** [transitive-bullshit/chatgpt-api#567]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

The gpt 4 template does not work. The package says: Open API error model not found

### Describe the Bug

.

**Comment by andrewoodleyjr** [comment]
The model: `gpt-4` does not exist"

**Comment by MicroGalaxy** [comment]
> The model: `gpt-4` does not exist"

same，with accesstoken ， did you solved

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
