### ISSUE TITLE
Need help setting up.

### ISSUE THREAD

**Issue by H4RRY-B4WLS** [transitive-bullshit/chatgpt-api#569]
### Describe the feature

ive gotten to the point where i can run the command help with npx chatgpt -h, but i cant figure out where or how to set my api key. i use npx chatgpt -k 'My API Key' and it doesnt work. ive tried entering my api key without quotes, with single and with double quotes. plz help

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
