### ISSUE TITLE
Can I use Chatgpt api in react-native app?

### ISSUE THREAD

**Issue by stack-guru** [transitive-bullshit/chatgpt-api#57]
Hi, first of all thanks for your effort for publishing this api.
This is greatly helpful for making project in my side.
Due to problem for implementing this api to my hybrid app, I am asking this question.
Is it possible to use this api in my react-native app?
Please give me an answer with update.
Regards.

**Comment by transitive-bullshit** [comment]
Hey @stack-guru, honestly I'm not sure. This package should be compatible with any environment that has `fetch`, as long as the `fetch` implementation is standards compliant.

Nothing Node.js-specific is used that would prevent it from being used in an RN app, so I'd recommend trying it out and seeing for yourself.

Note: I think it'd probably be a better idea to use `chatgpt` from a server-side API since it'll be easier to update things like the session token on the server as opposed to all of your client RN instances.

Hope that helps && let me know how it goes.

**Comment by transitive-bullshit** [comment]
Closing for now as answered; please do follow up and let the community know how it goes with RN.

**Comment by alex12058** [comment]
I tried using this library in the frontend in react and it did not work. I got the "failed to refresh auth token. Error: Unauthorized" error even when I used [koa](https://www.thisdot.co/blog/how-to-solve-cors-using-a-proxy-server-and-koa) to try to get around an issue with CORS. I found using this library in an [express api](https://stackabuse.com/building-a-rest-api-with-node-and-express/) works perfectly and I highly recommend this approach.

Here is my express server I have in a file named `rest-gateway.mjs`

```mjs
import { ChatGPTAPI } from "chatgpt";
import express from "express";
const app = express();
const port = 8080;

const api = new ChatGPTAPI({
	sessionToken: "{YourTokenHere}",
});

async function message(req, res, message) {
	try {
		await api.ensureAuth();
	}
	catch (e) {
		console.log(e);
		res.writeHead(401);
		return res.send({ error: e.toString() });
	}
	res.send(await api.sendMessage(message));
}

app.get(
	"/",
	(req, res) => {
		res.send("Hello World, from express");
	},
);
app.get(
	"/describe",
	async (req, res) => {
		const id = req.query.id;
		if (!id) return res.send({ error: `Missing id query param` });
		message(req, res, `Write a short paragraph describing a ${id}`);
	},
);


app.listen(port, () => console.log(`listening on port ${port}`));
```

You can start the express server via node. e.g. `node path/to/rest-gateway.mjs`.

WIth my express server running I can make a query to `localhost:8080/describe?id=fox` and I get this response from ChatGPT:
> A fox is a small, carnivorous mammal that belongs to the family Canidae. It is known for its sharp, pointed ears, slender snout, and bushy tail. Foxes are usually reddish-brown or gray in color, and are most active at dawn and dusk. They are intelligent animals that are skilled at hunting small prey such as birds and rodents. In some cultures, foxes are considered to be cunning and sly, while in others they are seen as a symbol of good luck.

**Comment by stack-guru** [comment]
Thanks alex12058.
This app can't work without SESSION_TOKEN. In other word without login this chatgpt site this app doesn't work.
I am trying to use this chatgpt int my proudct.
What do you think about this?

**Comment by alex12058** [comment]
I'm not sure I'm the best person to answer this. I think @transitive-bullshit would have more insight.

ChatGPT has added cloudflare which makes the ChatGPTAPI more difficult to use as you need to have a session token, cloudflare clearance token (which expire in 2 hours) and the ip address and user agent need to match the cloudflare clearance token as cloudflare does fingerprinting.

My current approach is to run ChatGPTAPI in an express service api and store the `SESSION_TOKEN`, `CLEARANCE_TOKEN` and `USER_AGENT` in a `.env` file which can be read by `dotenv`. I get these tokens by visiting https://chat.openai.com/chat on the computer that hosts the express api and [copying the cookie values](https://github.com/transitive-bullshit/chatgpt-api#session-tokens). The user agent can be found in the request header for the `session` request. The cloudflare clearance token only lasts for 2 hours though so I will need to replace it manually when it expires.

If there was a way to automate the process to get the tokens this would make the library easier to use. This is discussed in https://github.com/transitive-bullshit/chatgpt-api/issues/96
