### ISSUE TITLE
fetch is not defined

### ISSUE THREAD

**Issue by didoee** [transitive-bullshit/chatgpt-api#572]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node 16.20.0
win11

### Describe the Bug

I have installed unfetch, but this problem is still occurring
![image](https://github.com/transitive-bullshit/chatgpt-api/assets/112919246/29831484-2934-420b-a37a-396ab8d0cf37)

**Comment by thititongumpun** [comment]
Hi, in docs. -> Make sure you're using node >= 18 so fetch is available (or node >= 14 if you install a [fetch polyfill](https://github.com/developit/unfetch#usage-as-a-polyfill)).

**Comment by didoee** [comment]
> Hi, in docs. -> Make sure you're using node >= 18 so fetch is available (or node >= 14 if you install a [fetch polyfill](https://github.com/developit/unfetch#usage-as-a-polyfill)).

I have installed fetch polyfill as documented

![image](https://github.com/transitive-bullshit/chatgpt-api/assets/112919246/9c579d50-befe-4646-aaa5-578ff8c4e940)

**Comment by transitive-bullshit** [comment]
@didoee you also need to initialize the fetch polyfill. Please double check the docs.

**Comment by inannan423** [comment]
@didoee  Are you from China? OpenAI's API is not accessible in China, so consider proxies. Solve this problem and it will work.
[chatgptProxyAPI]https://github.com/x-dr/chatgptProxyAPI
