### ISSUE TITLE
Why does the returned content often contain '�'

### ISSUE THREAD

**Issue by walker-peng22** [transitive-bullshit/chatgpt-api#573]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

chatgpt: "^5.2.4"
node: v18.15.0
macos

### Describe the Bug

I use onProgress to return a stream, but the content often contains '�'. Is the encoding format incorrect?

![image](https://github.com/transitive-bullshit/chatgpt-api/assets/26086540/4fbf6ce3-af3c-4f1a-9144-fc5e5ad3c1c0)

```
 const res = await this.chatGPTProvider.sendMessage(searchDto.content, {
      systemMessage: '首选用中文回复',
      parentMessageId,
      onProgress: (partialResponse) => {
        if (partialResponse.delta) {
          response.write(partialResponse.delta);
        }
      },
    });
```

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
