### ISSUE TITLE
"You did not write down any '// @ai' comment lines

### ISSUE THREAD

**Issue by dupiesdupreez** [transitive-bullshit/chatgpt-api#575]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Visual studio code
Angular 
Javascript

### Describe the Bug

Making the comment and running generate give the following error

`You did not write down any '// @ai' comment lines`

```
  doSubscriptionCalls(userDataSubscription : IUserDataSubscription){

   // @ai generate a switch statement here with userDataSubscription as the switch value
   
  }
```

![image](https://github.com/transitive-bullshit/chatgpt-api/assets/6910085/1460dafa-ce35-494e-a922-6197ce2f5e2d)

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
