### ISSUE TITLE
Token Usage Counter?

### ISSUE THREAD

**Issue by HarveyLijh** [transitive-bullshit/chatgpt-api#579]
### Describe the feature

First of all, awesome tool! Thanks for the dedicated work! I've been looking into Issues tickets and code, but still wondering if there is a way I can counter the token usage of each request I made to openAI? I saw an import and usage of tiktoken, but it seems irrelevant to usage counting. Cheers

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
