### ISSUE TITLE
Support for Function calling

### ISSUE THREAD

**Issue by ChoqueCastroLD** [transitive-bullshit/chatgpt-api#584]
### Describe the feature

It would be nice to have support for function calling as seen in https://platform.openai.com/docs/guides/gpt/function-calling
for the models gpt-3.5-turbo-0613 and gpt-4-0613

**Comment by transitive-bullshit** [comment]
Agreed.

I added a preliminary version to `openai-fetch` here: https://github.com/rileytomasek/openai-fetch/pull/26

Support for this package would definitely be appreciated.

**Comment by marknauf** [comment]
This would be a huge feature upgrade. Is anyone currently working on this?

**Comment by liyf1** [comment]
Looking forward to ！！

**Comment by Zedmerlol** [comment]
+1

**Comment by panlina** [comment]
When can we expect this to be in?

**Comment by adi6409** [comment]
I _might_ give it a try and start working on an implementation.

**Comment by adi6409** [comment]
Alright so i'll use this issue as a live updates "blog".
First thing: most likely will need a function to manually feed the conversation with a function result.

**Comment by shiyuesong** [comment]
Any news?

**Comment by panlina** [comment]
This repo and issue has been inactive for long. Is there any one working on this feature now?

**Comment by mrahmadt** [comment]
Function calling is working fine with the current code. The issue is with returning the function call output to chatgpt

@transitive-bullshit I'm working on modifying the code to accept function output and (Role function) and send it to chatgpt

I hope you can let us know if you are already doing it or if you will accept the changes (I can see many pull requests are not accepted/rejected)

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
