### ISSUE TITLE
When sending a request, how can I not include the 'max_tokens' parameter by default?

### ISSUE THREAD

**Issue by quzard** [transitive-bullshit/chatgpt-api#585]
### Describe the feature

When sending a request, how can I not include the 'max_tokens' parameter by default?

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
