### ISSUE TITLE
Support disabling storing message context

### ISSUE THREAD

**Issue by kibertoad** [transitive-bullshit/chatgpt-api#586]
### Describe the feature

In case whole conversation is short, it doesn't make sense to waste memory and CPU by keeping its context, it is sufficient to pass prior context manually.

For such use-cases it would be great if there was an option to disable context storing entirely.

If this is approved, I can prepare a PR.

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
