### ISSUE TITLE
Error: The text contains a special token that is not allowed: <|endofprompt|>

### ISSUE THREAD

**Issue by yokebtc** [transitive-bullshit/chatgpt-api#589]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

nodejs 16.x  mobile

### Describe the Bug

![image](https://github.com/transitive-bullshit/chatgpt-api/assets/43801754/d90019c2-6c9f-45e4-ac12-cbfe0870e6cb)
Does the latest version have the same problem

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
