### ISSUE TITLE
how to send last 5 message by user_id ?

### ISSUE THREAD

**Issue by mtariqsajid** [transitive-bullshit/chatgpt-api#591]
### Describe the feature

I want to know is there a way to send last 5 message of the user in sendMessage method

```js
let options: any = {
   completionParams: {
      model: openAIModelDB,
      messages: [{
            role: 'user',
            content: 'when obama was born'
         },
         {
            role: 'assistant',
            content: 'Barack Obama was born on August 4, 1961.'
         },
         {
            role: 'user',
            content: 'when obama was born'
         },
         {
            role: 'assistant',
            content: 'Barack Obama was born on August 4, 1961.'
         }
      ]
   }
};

   options.completionParams = {
      ...options.completionParams,
      stop: data?.stopSequences,
      temperature: data?.temperature,
      top_p: data?.topP,
      presence_penalty: data?.presencePenalty,
      frequency_penalty: data?.frequencyPenalty,
   };

const res = await ChatGpt.ChatGPTClient.sendMessage(message, options);
```

right now Messages are omit in sendMessage method

what i am trying to do is create a chat message like chatgpt and i want to get all message by user id then send last 5 message to chatgpt right now we can only send last message parent id to chatgpt. and parent message is change every time new message is return is there is a possibility to keep parent message id same but change the chat message id

**Comment by mtariqsajid** [comment]
anyone help me here @transitive-bullshit

**Comment by chenweiyi** [comment]
maybe this [pr](https://github.com/transitive-bullshit/chatgpt-api/pull/559) can help you.

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
