### ISSUE TITLE
Chinese documents?

### ISSUE THREAD

**Issue by quinn-getty** [transitive-bullshit/chatgpt-api#594]
### Describe the feature

Do you have any Chinese documents?

**Comment by zsh2401** [comment]
There is no need for this， all apis is so clear that everyone can understand it.

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
