### ISSUE TITLE
@dqbd/tiktoken  no such file or directory, t_tiktoken_bg.wasm

### ISSUE THREAD

**Issue by kiraraty** [transitive-bullshit/chatgpt-api#595]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

@dqbd/tiktoken  no such file or directory, t_tiktoken_bg.wasm

### Describe the Bug

@dqbd/tiktoken  no such file or directory, t_tiktoken_bg.wasm

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
