### ISSUE TITLE
Continue generating in ChatGPTUnofficialProxyAPI

### ISSUE THREAD

**Issue by maisyshantelle** [transitive-bullshit/chatgpt-api#599]
### Describe the feature

As you may know, in generating long texts, sometimes ChatGPT will temporarily pause and request the user to click the "continue generating" button. If the ChatGPTUnofficialProxyAPI is used, the text may be delivered incomplete. Is it possible to also receive the continuation of the text?

**Comment by thanhtoan1196** [comment]
any updates?

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
