### ISSUE TITLE
Fetch 

### ISSUE THREAD

**Issue by amosayomide05** [transitive-bullshit/chatgpt-api#60]
(node:17[5](https://github.com/amosayomide05/scraping/actions/runs/3648131455/jobs/6161192237#step:5:6)4) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

How do i get rid of it?, this is generated when I used console.log();

**Comment by amosayomide05** [comment]
never mind

**Comment by transitive-bullshit** [comment]
@amosayomide05 what version of node.js were you using?

**Comment by amosayomide05** [comment]
> @amosayomide05 what version of node.js were you using?

19.0.0

**Comment by transitive-bullshit** [comment]
Ahhh haven't tested on v19 yet. Let me know how it works for you.

**Comment by amosayomide05** [comment]
> Ahhh haven't tested on v19 yet. Let me know how it works for you.

Never mind bro

I don't affect me, it only output that on console.log()
