### ISSUE TITLE
这个跟直接调用官方api有什么区别嘛 ，另外报错超时443是怎么回事？

### ISSUE THREAD

**Issue by SJQSSS** [transitive-bullshit/chatgpt-api#600]
### Describe the feature

这个跟直接调用官方api有什么区别嘛 ，另外报错超时443是怎么回事

**Comment by panlina** [comment]
帮你维护聊天记录，官方的要你自己每次发送整个聊天记录。

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
