### ISSUE TITLE
ChatGPTUnofficialProxyAPI invalid Token

### ISSUE THREAD

**Issue by Criztiandev** [transitive-bullshit/chatgpt-api#602]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Im testing the ChatGPTUnofficialProxyAPI which I provide the access token thru https://chat.openai.com/api/auth/session

### Describe the Bug

When I run the ChatGPTUnofficialProxyAPI  it returns me a invalid token error but the token is valid

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
