### ISSUE TITLE
messageStore How To

### ISSUE THREAD

**Issue by mrahmadt** [transitive-bullshit/chatgpt-api#608]
### Describe the feature

Hello @transitive-bullshit ,

It would be very useful if you could please write an example in README of how to use messageStore, it will help many people (including me :) ) in how to add history to chatgpt-api

**Comment by markNZed** [comment]
See https://github.com/transitive-bullshit/chatgpt-api/blob/main/demos/demo-persistence.ts

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
