### ISSUE TITLE
Status/plans for this project?

### ISSUE THREAD

**Issue by markNZed** [transitive-bullshit/chatgpt-api#611]
### Describe the feature

I see many attempts to contact @transitive-bullshit regarding this repository and no commits for several months. Does anyone know more about the current situation and future plans? I would like to experiment with the function feature which seems to not be supported so I am thinking about moving to another package (any suggestions welcome!) One option is https://github.com/vercel/ai

**Comment by transitive-bullshit** [comment]
Hey @markNZed, feel free to DM me on twitter https://twitter.com/transitive_bs

This project is undergoing a major revamp; closing out old issues as part of the prep process.

I think you'll like the new version that I've been working on :)

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
