### ISSUE TITLE
Bug of not remembering old message

### ISSUE THREAD

**Issue by zfcsoftware** [transitive-bullshit/chatgpt-api#613]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

![image](https://github.com/transitive-bullshit/chatgpt-api/assets/123484092/8b06e78d-1481-4c22-9d13-12da73f6c546)

The example given works fine, but there is a problem. When the code is not asked repeatedly in this way, it cannot remember the old message.
![image](https://github.com/transitive-bullshit/chatgpt-api/assets/123484092/c811cf9e-1dc0-4304-98d4-1e41cfe8fdc7)

I asked him to name two things about Github. He did. Now I want him to count more to check if he can remember.

![image](https://github.com/transitive-bullshit/chatgpt-api/assets/123484092/2d0a8f05-e8c2-4c9f-942a-228231d1401d)

As you can see, it doesn't remember the previous message even though I ask it with the id value of the previous message, and it's just nonsense. It works when used as it is in the npm library, but it doesn't remember when used sequentially like this.
I had this problem in one of my projects, thanks.

**Comment by brenc** [comment]
FYI you exposed your API key there in one of the screenshots.

**Comment by zfcsoftware** [comment]
> FYI you exposed your API key there in a few of the screenshots.

5 dollars is a trial key with a balance. It is not a problem for me, I have more than 60. Thank you very much for your warning.

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
