### ISSUE TITLE
Model GPT-4 does not exist or you do not have access to it

### ISSUE THREAD

**Issue by mmaestrini** [transitive-bullshit/chatgpt-api#615]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node 18, OSX

### Describe the Bug

Apologies if I am mistakenly open an issue about this, but I am following the instructions and initialising using gpt-4 and i get "The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4."

I am a paid chatgpt-4 organization and I can use gpt4 on web no problem.

Any help is greatly appreciated.

**Comment by kubk** [comment]
Read this: https://help.openai.com/en/articles/8264644-what-is-prepaid-billing

You need to top up your balance with money first (gpt on web is a different story)

**Comment by mmaestrini** [comment]
@kubk So the API is paid separately compared to the paid chatgptplus ?

**Comment by kubk** [comment]
@mmaestrini Yes, billing is separate

**Comment by mmaestrini** [comment]
Understood @kubk - but would me adding a credit card to my account already be good enough? Because like i said i do not have any option as in the link you sent to prepay credits... but I am getting charged already per usage.. so i assume this should be good to go?

**Comment by mmaestrini** [comment]
Ok never mind i think it will work now. I setup my payment a while back, and now i cancelled the payment methods and re added them and now i asked me to precharge :) hope this can be useful to someone else if they find the same issue.
