### ISSUE TITLE
Add plugins, images, code interpretation etc.. feacture for UnofficialProxy 

### ISSUE THREAD

**Issue by yhhit** [transitive-bullshit/chatgpt-api#619]
### Describe the feature

Add plugins, images, code interpretation etc.. feacture for UnofficialProxy

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
