### ISSUE TITLE
Front-end cross-domain

### ISSUE THREAD

**Issue by JACK-ZHANG-coming** [transitive-bullshit/chatgpt-api#62]
hi ,I'm use react.js build，but show a CORS error ：

`Access to fetch at 'https://chat.openai.com/api/auth/session' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by transitive-bullshit** [comment]
@JACK-ZHANG-coming This package is not meant to be used from client-side browser code. See the compatibility section in the readme for details https://github.com/transitive-bullshit/chatgpt-api#compatibility
