### ISSUE TITLE
ChatGPT 4 vision - send image?

### ISSUE THREAD

**Issue by mmaestrini** [transitive-bullshit/chatgpt-api#623]
### Describe the feature

Hi there,

is it already possible here to use the new chatgpt 4 vision that can interpret / analyse images? in the web is the default mode, not referring to the advanced data analysis.

**Comment by raisonqyc** [comment]
Looking forward to the addition of image input for gpt-api  !!!!

**Comment by jobpassion** [comment]
you can use my fork:https://github.com/jobpassion/chatgpt-api ,add support for images and multimodal

**Comment by assassinliujie** [comment]
> 你可以使用 my fork：https://github.com/jobpassion/chatgpt-api ，添加对图像和多模态的支持

would you add the support for api?

**Comment by jobpassion** [comment]
> would you add the support for api?

Currently only images and multimodal are supported for UnofficialProxyAPI, and there are no plans to add support for ChatGPTAPI at the moment.

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead. They both have support for multimodal messages.
