### ISSUE TITLE
Upload image

### ISSUE THREAD

**Issue by dichen2013** [transitive-bullshit/chatgpt-api#625]
### Describe the feature

Can this support image uploading? Look forword the image upload feature....

**Comment by jobpassion** [comment]
you can use my fork:https://github.com/jobpassion/chatgpt-api ,add support for images and multimodal

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
