### ISSUE TITLE
Error: It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy

### ISSUE THREAD

**Issue by Justin-van-der-Velden** [transitive-bullshit/chatgpt-api#630]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node.js version: 21.1.0
macOS: Ventura 13.5.2

### Describe the Bug

Since today I'm seeing this error with the `ChatGPTUnofficialProxyAPI`:

`ChatGPT error 429: {"detail":"It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy"}`

I don't see PandoraNext in the package.json so it could also be something on the ChatGpt side

**Comment by Justin-van-der-Velden** [comment]
After digging a bit more into the issue I found out it has something to do with the Reverse Proxy

`{
  res: Response (107 bytes) {
    ok: false,
    url: "https://ai.fakeopen.com/api/conversation",
    status: 429,
    statusText: "Too Many Requests",
    headers: Headers {
      "date": "Tue, 21 Nov 2023 10:10:48 GMT",
      "content-type": "application/json",
      "content-length": "107",
      "connection": "keep-alive",
      "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=cWY2J%2BHNy%2BlsEBKlhtRRgeTSIquHiC4cVsgCLTmYqrZslzpT4%2FnFraQaro3JG08jaNYJjNZOyFh7MkEN9MYUpsOBjJGj2%2Fi7rw7dd4gRNPYlJBYv8xgsnaX2%2FvG9SxiOPA%3D%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
      "vary": "Accept-Encoding",
      "strict-transport-security": "max-age=15552000; includeSubDomains; preload",
      "x-content-type-options": "nosniff",
      "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}",
      "server": "cloudflare",
      "cf-ray": "8298251fccc30e34-AMS",
      "alt-svc": "h3=\":443\"; ma=86400"
    },
    redirected: false,
    bodyUsed: false,
    Blob (107 bytes)
  }
}`

seem like `https://ai.fakeopen.com/api/conversation` had to many requests

**Comment by safakseyrek** [comment]
i have the same problem

![image](https://github.com/transitive-bullshit/chatgpt-api/assets/58136093/cb283e5c-0801-410e-bf92-cdabdeabf2a5)

**Comment by JustAnEric** [comment]
I just started getting this same error on my Python project.

**Comment by JustAnEric** [comment]
@safakseyrek I found out that https://ai.fakeopen.com/v1 is the problem here. It kept giving the same errors over and over again. I think a better solution would be just to switch to another OpenAI proxy.

**Comment by assassinliujie** [comment]
please build your own proxy by using https://github.com/pandora-next/deploy

**Comment by deadmenrr** [comment]
> please build your own proxy by using https://github.com/pandora-next/deploy

limit: 100 request - really???

**Comment by jerry-f** [comment]
现在还可以使用么， 该如何创建自己的代理呢

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
