### ISSUE TITLE
After call AbortController. abort(), it did not stop immediately and only returned after timeout

### ISSUE THREAD

**Issue by CytFree** [transitive-bullshit/chatgpt-api#631]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node  v16.20.2 
os   macOS  12.7.1

### Describe the Bug

When using ChatGPTAPI, when I set the custom abortSignal and timeout, and the stream is true, and call abort(), the response will stop outputting, but the timeout is not canceled and will wait until the timeout is reached

![image](https://github.com/transitive-bullshit/chatgpt-api/assets/34176334/b216d46a-8bcb-4696-8a45-b417c6b2ce92)

**Comment by pai4451** [comment]
I have the same issue

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
