### ISSUE TITLE
ChatGPTUnofficialProxyAPI Not Working

### ISSUE THREAD

**Issue by asad-ullah321** [transitive-bullshit/chatgpt-api#632]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

{
  "name": "tempproject",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "nodemon index.mjs"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "chat-gpt-authenticator": "^0.5.0",
    "chatgpt": "^5.2.5",
    "chatgpt-io": "^1.1.4",
    "dotenv": "^16.3.1",
    "nodemon": "^3.0.2",
    "openai-authenticator": "^0.0.3",
    "openai-token": "^1.0.0",
    "ora": "^7.0.1",
    "puppeteer": "^21.5.2",
    "unofficial-chatgpt-api": "^1.6.0"
  }
}
Node: 18v
OS: Windows 10
Browser: Chrome 

### Describe the Bug

When I request using ChatGPTUnofficialProxyAPI it get stuck and didn't get the response. 
Code:
import { ChatGPTUnofficialProxyAPI } from 'chatgpt'
import { oraPromise } from 'ora'
import { configDotenv } from 'dotenv'
configDotenv()

async function example() {
  //console.log(process.env.ACCESS_TOKEN)
  const api = new ChatGPTUnofficialProxyAPI({
    accessToken: process.env.ACCESS_TOKEN
    
  })
  
  const prompt = 'Hi how are you'
  let res = await oraPromise(api.sendMessage(prompt), {
    text: prompt
  })

  console.log('\n' + res.text + '\n')
  // let chatResponse = await api.sendMessage(prompt)
  // console.log(chatResponse)
  // console.log("asad2")

  
}

example().catch((err) => {
  console.error(err)
  process.exit(1)
})

**Comment by ezekiel747** [comment]
is anyone able to use the unofficial proxy API? 
it was still working fine about 2-3 weeks ago.

Also, where can i see a more comprehensive list of reverse proxies?
I've tried with both of those that are listed in the Readme.

Thanks in advance.

**Comment by Polydynamical** [comment]
Yeah I'm having the same problem :(

**Comment by devadigapratham** [comment]
can i be assigned to solve this

**Comment by deadmenrr** [comment]
same problem :(
Pandora proxy has 100 req/day limit =(

**Comment by ezekiel747** [comment]
> same problem :( Pandora proxy has 100 req/day limit =(

pandora proxy? where can i see its address? or a list of another available addresses?
I only have those two from the Readme file.

**Comment by deadmenrr** [comment]
> > same problem :( Pandora proxy has 100 req/day limit =(
> 
> pandora proxy? where can i see its address? or a list of another available addresses? I only have those two from the Readme file.

You need install it on vps and config

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
