### ISSUE TITLE
support pip

### ISSUE THREAD

**Issue by axhlzy** [transitive-bullshit/chatgpt-api#635]
### Describe the feature

┌──(lzy㉿kali)-[~]
└─$ ls | chatgpt "how many icons in my desktop" 
As an AI language model, I don't have direct access to your desktop or personal files. Therefore, I cannot provide you with the exact number of icons on your desktop. However, you can manually count the icons displayed on your desktop screen.

ls output stream might be > to chatgpt msg

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
