### ISSUE TITLE
It is not work when use gpt-4 model！ha ha

### ISSUE THREAD

**Issue by HuangJT** [transitive-bullshit/chatgpt-api#636]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node.js version: v20.3.1

### Describe the Bug

when I use model gpt-4，it always not work！

```shell
[hello@xxx temp]# npx chatgpt@latest --model gpt-4 "what is your GPT version?what time do your knowledge cutoff?"
 I am based on GPT-3, which is the latest version as of my knowledge cutoff in September 2021. 
```
And the bill at openAI console haved pay for gpt-4。It is so weird ， until see the code  
[chatgpt-api.ts#L83](https://github.com/transitive-bullshit/chatgpt-api/blob/73fb30bc11b7b7d05409fe491562c2a4546cbd80/src/chatgpt-api.ts#L83)
```js
if (this._systemMessage === undefined) {
      const currentDate = new Date().toISOString().split('T')[0]
      this._systemMessage = `You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\nKnowledge cutoff: 2021-09-01\nCurrent date: ${currentDate}`
    }
```

**Comment by tedy5** [comment]
Looks like this is not issue with this library but rather OpenAI disabled gpt4.

**Comment by Jakeroid** [comment]
Probably the issue should be closed.

**Comment by HuangJT** [comment]
the default systemMessage shoud not include “Knowledge cutoff: 2021-09-01”，this will make the chatgpt answer “I am based on GPT-3”。
[chatgpt-api.ts#L83](https://github.com/transitive-bullshit/chatgpt-api/blob/73fb30bc11b7b7d05409fe491562c2a4546cbd80/src/chatgpt-api.ts#L83)

> Probably the issue should be closed.

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
