### ISSUE TITLE
assistant

### ISSUE THREAD

**Issue by WindSing-zhang** [transitive-bullshit/chatgpt-api#638]
### Describe the feature

Hello, can you access the assistant api? It is very helpful to me

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package.
