### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by troyam** [transitive-bullshit/chatgpt-api#639]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

New Account and API KEY

### Describe the Bug

ChatGPTError: ChatGPT error 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

**Comment by transitive-bullshit** [comment]
The OpenAI API has rate limits. This error is telling you that you've exceeded your quota and need to request more from the OpenAI dashboard.

**Comment by troyam** [comment]
Just explained the issue: We need to charge 5$ to be able to consume now.
So just go to Billing section and register any credit card to charge.
And it works again.

Bye!
