### ISSUE TITLE
[ChatGPTUnofficialProxyAPI] ChatGPT Web has switched from SSE to WebSockets.

### ISSUE THREAD

**Issue by yjmp14** [transitive-bullshit/chatgpt-api#640]
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

.

### Describe the Bug

ChatGPT Web has switched from SSE to WebSockets, as a result, the ChatGPTUnofficialProxyAPI is no longer functional. The SSE-related code needs to be updated.

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old issues as part of the prep process.

The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package instead.
