### ISSUE TITLE
webpack bundle error

### ISSUE THREAD

**Issue by PengBoUESTC** [transitive-bullshit/chatgpt-api#69]
webpack 5.66.0 compiled successfully in 3940 ms
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: xxx/node_modules/chatgpt/build/index.js
require() of ES modules is not supported.
require() of xxx/node_modules/chatgpt/build/index.js from xxx/dist/src/modules/chat/Chat.service.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from xxx/node_modules/chatgpt/package.json.

**Comment by transitive-bullshit** [comment]
From the readme:

```ts
async function example() {
  // To use ESM in CommonJS, you can use a dynamic import
  const { ChatGPTAPI } = await import('chatgpt')

  const api = new ChatGPTAPI({
    sessionToken: process.env.SESSION_TOKEN
  })
  await api.ensureAuth()

  const response = await api.sendMessage('Hello World!')
  console.log(response)
}
```

(This project does not support commonjs exports because they are deprecated for all intents and purposes and it is a huge pain for maintainers to support.)

Here's [a solid guide](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) on other ways to use ESM modules like `chatgpt`.

**Comment by PengBoUESTC** [comment]
> From the readme:
> 
> ```ts
> async function example() {
>   // To use ESM in CommonJS, you can use a dynamic import
>   const { ChatGPTAPI } = await import('chatgpt')
> 
>   const api = new ChatGPTAPI({
>     sessionToken: process.env.SESSION_TOKEN
>   })
>   await api.ensureAuth()
> 
>   const response = await api.sendMessage('Hello World!')
>   console.log(response)
> }
> ```
> 
> (This project does not support commonjs exports because they are deprecated for all intents and purposes and it is a huge pain for maintainers to support.)
> 
> Here's [a solid guide](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) on other ways to use ESM modules like `chatgpt`.

maybe that is not same as what did i say, your module is declare as a `module` by `type: module`, but, in your dependency package(expiry-map), it use `require` to import module ,

**Comment by transitive-bullshit** [comment]
@PengBoUESTC ESM modules can import commonjs modules, but commonjs cannot synchronously import ESM modules.

**Comment by PengBoUESTC** [comment]
> @PengBoUESTC ESM modules can import commonjs modules, but commonjs cannot synchronously import ESM modules.

that's may be my fault, build tool transform import to require

**Comment by rzfzr** [comment]
> > @PengBoUESTC ESM modules can import commonjs modules, but commonjs cannot synchronously import ESM modules.
> 
> that's may be my fault, build tool transform import to require

I believe it was the case with ` "vue-cli-plugin-electron-builder": "~2.1.1"`

[This ](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1622#issuecomment-1008253317) solved it for me!
