### ISSUE TITLE
 failed to refresh auth token

### ISSUE THREAD

**Issue by zhuaoshuai13** [transitive-bullshit/chatgpt-api#70]
Uncaught (in promise) Error: ChatGPT failed to refresh auth token. Error: Unauthorized

**Comment by transitive-bullshit** [comment]
This may happen from time to time. Either that or your session token is no longer valid.

I would recommend handling errors gracefully and adding timeout / retry logic around the API in case it fails.

For a robust example of this working in production, check out how I'm using it in my twitter bot: https://github.com/transitive-bullshit/chatgpt-twitter-bot/blob/main/src/respond-to-new-mentions.ts#L414
