### ISSUE TITLE
ChatGPT failed to refresh auth token. Error: Unauthorized, request returns code 304

### ISSUE THREAD

**Issue by thijsheijden** [transitive-bullshit/chatgpt-api#76]
Hi! Very excited to use this lib, looks very polished for the amount of time that has passed since chatGPT was launched! I am trying to initialise a client, but keep getting an `ChatGPT failed to refresh auth token. Error: Unauthorized` error. I copy the value for the `__Secure-next-auth.session-token` cookie. Have tried the other ones as well, but they don't work either.

When I look at the requests being sent, I can see that the session request returns a 304, and the body is empty. I assume that that is not what is supposed to happen, as the same request on the openAI website does not return an empty body. Any ideas why this could be happening?

**Comment by transitive-bullshit** [comment]
@thijsheijden what ended up happening for you?

**Comment by thijsheijden** [comment]
@transitive-bullshit still does not work, but I assume it is probably because I am trying to run this on a client side application (Svelte). Had to turn off CORS restrictions in Safari to even get the request to go through, and I think that might be where it is breaking. Currently adding a local proxy to try and circumvent both issues.
