### ISSUE TITLE
Seeing two session cookies 

### ISSUE THREAD

**Issue by ericmigi** [transitive-bullshit/chatgpt-api#77]
<img width="317" alt="CleanShot 2022-12-09 at 10 50 20@2x" src="https://user-images.githubusercontent.com/1048265/206772878-0327add5-f8bb-48af-84b2-d08b5b7d1c25.png">

Both are failing with 
<img width="478" alt="CleanShot 2022-12-09 at 10 50 38@2x" src="https://user-images.githubusercontent.com/1048265/206772999-346e1cd7-ae11-4383-b4b8-33beb80d04d6.png">

**Comment by transitive-bullshit** [comment]
Interesting. Maybe try erasing your local application cache from devtools which will log you out, and then try logging back in?

I just tried this and I'm still seeing the same single session token on my end. It's possible that OpenAI is actively testing new things, so let me know if you keep experiencing this.

**Comment by ericmigi** [comment]
I signed in using a different google account and got a single session token. Odd!

**Comment by abacaj** [comment]
Can confirm there is a dual token system in place, wasn't clear to me what causes this but one of my accounts is a paying openapi account:

![image](https://user-images.githubusercontent.com/7272343/206810660-2a496666-71ef-4a21-b56b-c40dd0faf497.png)

**Comment by maksim-romanov** [comment]
this is problem accounts logged in via google auth acc seems

**Comment by transitive-bullshit** [comment]
I'm using a google-authorized account and am only seeing a single session token. So it has to be either something else of a combination of factors.

**Comment by acheong08** [comment]
I also encounter this issue quite often. Both tokens are valid though so you can just select the first one if multiple are detected
https://github.com/acheong08/ChatGPT/blob/7be51f67fd1087d1c4d0672f40b225d8c57bdf2f/src/revChatGPT/revChatGPT.py#L363-L378
