### ISSUE TITLE
Instead change the require of index.js  to a dynamic import() which is available in all CommonJS modules

### ISSUE THREAD

**Issue by badboy-tian** [transitive-bullshit/chatgpt-api#80]
```
"chatgpt": "^2.0.5",
```
![image](https://user-images.githubusercontent.com/2835129/206825219-8adad7a9-665b-404f-bc82-43e2c6f1f79d.png)

```
 Error [ERR_REQUIRE_ESM]: require() of ES Module xxx.js not supported
```

how to fix this ?

**Comment by transitive-bullshit** [comment]
From the readme:

```ts
async function example() {
  // To use ESM in CommonJS, you can use a dynamic import
  const { ChatGPTAPI } = await import('chatgpt')

  const api = new ChatGPTAPI({
    sessionToken: process.env.SESSION_TOKEN
  })
  await api.ensureAuth()

  const response = await api.sendMessage('Hello World!')
  console.log(response)
}
```

(This project does not support commonjs exports because they are deprecated for all intents and purposes and it is a huge pain for maintainers to support.)

Here's [a solid guide](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) on other ways to use ESM modules like `chatgpt`.

**Comment by badboy-tian** [comment]
```
{"code":"ERR_REQUIRE_ESM","error":"require() of ES Module D:\\Android\\variable_speaker_cloud_code\\node_modules\\chatgpt\\build\\index.js from D:\\Android\\variable_speaker_cloud_code\\dist\\cloudjs\\cloud_test.js not supported.\nInstead change the require of index.js in D:\\Android\\variable_speaker_cloud_code\\dist\\cloudjs\\cloud_test.js to a dynamic import() which is available in all CommonJS modules."}

```

![image](https://user-images.githubusercontent.com/2835129/206826086-ac316036-dcaf-408e-aefc-6d2f85fd40bc.png)

same error

**Comment by badboy-tian** [comment]
@transitive-bullshit hello, same error

**Comment by transitive-bullshit** [comment]
@badboy-tian Helping developers fix CommonJS/ESM issues in their projects is well outside the scope of this repo.

**Comment by badboy-tian** [comment]
ok , thanks

**Comment by GhyslainBruno** [comment]
@anirkm Thanks a lot for this tip. 

I've never seen this before, but it helped me so much ! 

Good to know for every now and then when we have to deal with this kind of (annoying) error.
