### ISSUE TITLE
How can I close a conversation?

### ISSUE THREAD

**Issue by linsyking** [transitive-bullshit/chatgpt-api#82]
It seems that if I don't close a conversion, the speed will become slower and slower.

Is there a way to close a conversation?

**Comment by transitive-bullshit** [comment]
I'm guessing what you're seeing has less to do with conversations and more to do with OpenAI slowly rate-limiting you and/or your account over time.

I haven't noticed any degradation in performance when it comes to long conversations (though it may still exist). I'm not aware of any way using the current API to close a conversation.

**Comment by linsyking** [comment]
Get it, Thanks! :+1:
