### ISSUE TITLE
Add ability to override auth url

### ISSUE THREAD

**Issue by alex12058** [transitive-bullshit/chatgpt-api#91]
Currently the `ChatGPTAPI` constructor allows you to set the `apiBaseURL` and the `backendAPIBaseURL` however the auth url used for authentication in the `refreshAccessTokens` function is hardcoded to https://chat.openai.com/api/auth/session. To avoid issues with CORS I would like to be able to modify the auth url so it would go through a [koa proxy](https://www.thisdot.co/blog/how-to-solve-cors-using-a-proxy-server-and-koa).

Alternatively this could be resolved by implementing a proxy configuration as described by https://github.com/transitive-bullshit/chatgpt-api/issues/47

**Comment by alex12058** [comment]
I'm not sure what I am doing wrong but `/api/auth/session` through my proxy is returning an empty object.

**Comment by gd1m3y** [comment]
i think the api is down none of the wrappers are working at the moment

**Comment by transitive-bullshit** [comment]
@gd1m3y hmmm my twitter bot is still chugging along without any abnormal errors, though I'm not sure about re-authenticating.

**Comment by transitive-bullshit** [comment]
> Currently the ChatGPTAPI constructor allows you to set the apiBaseURL and the backendAPIBaseURL however the auth url used for authentication in the refreshAccessTokens function is hardcoded to [chat.openai.com/api/auth/session](https://chat.openai.com/api/auth/session). To avoid issues with CORS I would like to be able to modify the auth url so it would go through a [koa proxy](https://www.thisdot.co/blog/how-to-solve-cors-using-a-proxy-server-and-koa).

Ahhh yep, this is a bug as it should be using `apiBaseUrl` instead of being hard-coded.

**Comment by transitive-bullshit** [comment]
@alex12058 the auth url now uses `apiBaseUrl` if you update to latest. Fixed in https://github.com/transitive-bullshit/chatgpt-api/commit/14ac1af64be310c2bb39bceaa2225e4aa0671a9f#diff-c7628976638668a93f62ca0fa70570d31dd189f29e93f62f48d4a404e9bf46cfR261

**Comment by alex12058** [comment]
@transitive-bullshit Brialliant. Thank you for the quick fix.
